### PR TITLE
cocoa-cb: fix race on shutdown and toggling fullscreen

### LINKED ISSUE #14810: Crash in Common.getTargetScreen(forFullscreen:)
### mpv Information

```bash
/Applications/mpv.app/Contents/MacOS/mpv
mpv version: git-2024-07-31-0647089
FFmpeg version: git-2024-07-31-43f702a
```

### Other Information

```text
Process:               mpv
Path:                  /Applications/mpv.app/Contents/MacOS/mpv
Identifier:            io.mpv
Version:               0.38.0-UNKNOWN (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-07 08:13:00.4739 +0200
OS Version:            macOS 14.6.1 (23G93)
Report Version:        12
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001049ee090

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [58992]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   mpv                           	       0x1049ee090 Common.getTargetScreen(forFullscreen:) + 168
1   mpv                           	       0x1049f2a98 Window.toggleFullScreen(_:) + 164
2   mpv                           	       0x1049f2e84 @objc Window.toggleFullScreen(_:) + 88
3   mpv                           	       0x1049ed0f0 thunk for @escaping @callee_guaranteed () -> () + 28
4   libdispatch.dylib             	       0x18983b750 _dispatch_call_block_and_release + 32
5   libdispatch.dylib             	       0x18983d3e8 _dispatch_client_callout + 20
6   libdispatch.dylib             	       0x18984bbb8 _dispatch_main_queue_drain + 988
7   libdispatch.dylib             	       0x18984b7cc _dispatch_main_queue_callback_4CF + 44
8   CoreFoundation                	       0x189b0ead4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
9   CoreFoundation                	       0x189acc258 __CFRunLoopRun + 1996
10  CoreFoundation                	       0x189acb434 CFRunLoopRunSpecific + 608
11  HIToolbox                     	       0x19427519c RunCurrentEventLoopInMode + 292
12  HIToolbox                     	       0x194274fd8 ReceiveNextEventCommon + 648
13  HIToolbox                     	       0x194274d30 _BlockUntilNextEventMatchingListInModeWithFilter + 76
14  AppKit                        	       0x18d32acc8 _DPSNextEvent + 660
15  AppKit                        	       0x18db214d0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
16  AppKit                        	       0x18d31dffc -[NSApplication run] + 476
17  mpv                           	       0x1049e1eec Application.main(_:_:) + 440
18  mpv                           	       0x1049e1fdc @objc Application.main(_:_:) + 48
19  mpv                           	       0x104b01684 cocoa_main + 44
20  dyld                          	       0x189663154 start + 2476
```

### Reproduction Steps

Happened on casual exit. First time. No reproduction method atm.

### Expected Behavior

No crash

### Actual Behavior

Crash

### Log File

[mpv.log](https://github.com/user-attachments/files/16915077/mpv.log)

### Sample Files

_No response_

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

### PR DESCRIPTION
**Pull request by Akemi**
since commit 15c48f3 we were force to start drawing on the main queue again. this has several unintended side effects due to the nature of the main queue. in this case fullscreen event and shutdown event are executed out of order and fullscreening is done after shutdown, leading to accessing options that are already de-initialised.

just nil the window on shutdown and make it impossible to fullscreen after shutdown.

Fixes #14810

### CODE REVIEW

File: video/out/cocoa_cb_common.swift [hunk 1]
```diff
@@ -262,6 +262,7 @@ class CocoaCB: Common, EventSubscriber {
 
         uninit()
         uninitCommon()
+        window = nil
```
Comment (kasper93) [inline video/out/cocoa_cb_common.swift:265]: Can `shutdown()` be called again? Because if we null window here, those checks about wouldn't work anymore
```
isShuttingDown = window?.isAnimating ?? false ||
                         window?.isInFullscreen ?? false && option.vo.native_fs
        if window?.isInFullscreen ?? false && !(window?.isAnimating ?? false) {
            window?.close()
        }
if isShuttingDown { return }
```
but I don't fully follow what why this is checking all those things, so maybe it is ok. Just want to make sure.

Comment (kasper93) [reply video/out/cocoa_cb_common.swift:265]: Ok, it is hard for me to follow. But I just wanted to make sure that we are certain reference to window won't be needed after this point. Thanks.
