### PR TITLE
auto_profiles: try to distinguish invalid properties better

### LINKED ISSUE #11550: [auto_profiles] The conditional auto profiles using the property of `user-data` no longer works
### Important Information

Provide following Information:
- mpv version: https://github.com/mpv-player/mpv/commit/9feeb324eddd9ed73ae667e10275f663d70f7544
- Platform and Version: Windows 11
- Source of the mpv binary: https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230405

### Reproduction steps

Open any file using the following test lua script and conditional auto profile:
test lua script
```lua
mp.register_event("file-loaded", function()
    mp.set_property_native("user-data/test/a", "test")
end)
```
conditional auto profile in mpv.conf
```
[test]
profile-cond=p["user-data/test/a"] == "test"
profile-restore=copy-equal
pause
```
### Expected behavior

The conditional auto profile can work normally

### Actual behavior

Commit https://github.com/mpv-player/mpv/commit/6e4a76db0862303ae7f0f9fd7bdddff128fbd2f0 has broken the normal work of the conditional auto profile that uses property of `user-data`, and it no longer works.

### Log file

[test.log](https://github.com/mpv-player/mpv/files/11157376/test.log)

### PR DESCRIPTION
**Pull request by Dudemanguy**
Here's a way to fix #11550 but still keep the behavior of rejecting invalid properties. The downside is that something like `track-list/0/fake` wouldn't be rejected with this method, but I don't think there's a practical way for that.

### CODE REVIEW

File: player/lua/auto_profiles.lua [hunk 1]
```diff
@@ -14,6 +14,9 @@ local pending_hooks = {}            -- as set (keys only, meaningless values)
 -- profile the condition is evaluated for.
 local current_profile = nil
 
+-- Cached list of all top-level mpv properities. Only used for extra validation.
+local property_list = mp.get_property_native("property-list")
```
Comment (christoph-heinrich) [inline player/lua/auto_profiles.lua:18]: Turning that into a set would allow you to check for the existence of properties without iterating over it `property_set[name]`

File: player/lua/auto_profiles.lua [hunk 2]
```diff
@@ -40,6 +43,20 @@ local function evaluate(profile)
     profile.dirty = false
 end
 
+local function guess_invalid_property(name)
+    local toplevel_property = nil
+    for property in name:gmatch("([^/]+)") do
```
Comment (christoph-heinrich) [inline player/lua/auto_profiles.lua:48]: with `match()` instead of `gmatch()` you could avoid the loop

**Review by christoph-heinrich — CHANGES_REQUESTED** [review]

File: player/lua/auto_profiles.lua (hunk 1 above)
Comment (Dudemanguy) [reply player/lua/auto_profiles.lua]: Yeah duh, use a better data structure. Not sure if there's a more elegant way to turn that table to a list in lua but this works.

File: player/lua/auto_profiles.lua (hunk 2 above)
Comment (Dudemanguy) [reply player/lua/auto_profiles.lua]: Ended up code golfing it but with some comments.

**Review by christoph-heinrich — APPROVED** [review]
