### PR TITLE
ytdl_hook: fix clip start and end

### LINKED ISSUE #11567: ytdl_hook: clip extraction fails
### Important Information

Provide following Information:
- mpv version

```
mpv 0.35.1-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Wed Mar 22 08:19:26 2023
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
FFmpeg version: n6.0

```

- Platform and Version
`Linux panta 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux`
- Source of the mpv binary
pacman

### Reproduction steps
Run ` mpv --no-config https://www.youtube.com/clip/Ugkx4kxZma7m7VvYKV4R1k-KKuYkf_VlvI9U`.

### Expected behavior
Only a clip of the video plays.

### Actual behavior
The entire video plays.

### Log file
[log](https://0x0.st/HXYR.txt)
### Sample files
None.

### PR DESCRIPTION
**Pull request by stanoarn**
Fixes the issue where an entire youtube video would be played instead of just the specified clip.
Also adds previously unsupported reading of yt-dlp's end_time parameter.

Fixes #11567

### CODE REVIEW

File: player/lua/ytdl_hook.lua [hunk 1]
```diff
@@ -693,11 +693,21 @@ local function add_single_video(json)
     end
 
     -- set start time
-    if not (json.start_time == nil) and
+    if (not (json.start_time == nil) or not (json.section_start == nil)) and
```
Comment (christoph-heinrich) [inline player/lua/ytdl_hook.lua:696]: `not (var == nil)` can be replaced with `var`, because in lua anything that is not nil nor false is truthy.

`if (json.start_time or json.section_start) and ...`

File: player/lua/ytdl_hook.lua [hunk 2]
```diff
@@ -693,11 +693,21 @@ local function add_single_video(json)
...
         not option_was_set_locally("start") then
-        msg.debug("Setting start to: " .. json.start_time .. " secs")
-        mp.set_property("file-local-options/start", json.start_time)
+        start_time = json.start_time or json.section_start
+        msg.debug("Setting start to: " .. start_time .. " secs")
+        mp.set_property("file-local-options/start", start_time)
+    end
+
+    -- set end time
+    if (not (json.end_time == nil) or not (json.section_end == nil)) and
```
Comment (christoph-heinrich) [inline player/lua/ytdl_hook.lua:705]: same thing as the other if

File: player/lua/ytdl_hook.lua [hunk 3]
```diff
@@ -693,11 +693,21 @@ local function add_single_video(json)
     end
 
     -- set start time
-    if not (json.start_time == nil) and
+    if (not (json.start_time == nil) or not (json.section_start == nil)) and
         not option_was_set("start") and
         not option_was_set_locally("start") then
-        msg.debug("Setting start to: " .. json.start_time .. " secs")
-        mp.set_property("file-local-options/start", json.start_time)
+        start_time = json.start_time or json.section_start
```
Comment (christoph-heinrich) [inline player/lua/ytdl_hook.lua:699]: Please make that local

File: player/lua/ytdl_hook.lua [hunk 4]
```diff
@@ -693,11 +693,21 @@ local function add_single_video(json)
...
+        msg.debug("Setting start to: " .. start_time .. " secs")
+        mp.set_property("file-local-options/start", start_time)
+    end
+
+    -- set end time
+    if (not (json.end_time == nil) or not (json.section_end == nil)) and
+        not option_was_set("end") and
+        not option_was_set_locally("end") then
+        end_time = json.end_time or json.section_end
```
Comment (christoph-heinrich) [inline player/lua/ytdl_hook.lua:708]: same thing a the other global variable

**Review by christoph-heinrich — CHANGES_REQUESTED** [review]

File: player/lua/ytdl_hook.lua (hunk 1 above)
Comment (stanoarn) [reply player/lua/ytdl_hook.lua]: the rest of the file has quite a few instances of `if not (thing == nil)`. Should those be replaced as well?

Comment (stanoarn) [reply player/lua/ytdl_hook.lua]: Alright then, I'll leave the rest as is.

Fixup commit squashed and ready to be merged.

**Review by christoph-heinrich — APPROVED** [review]

**Review by Dudemanguy — APPROVED** [review]
LGTM and works.
