### PR TITLE
demux_mkv: don't set codec crop rect when there is no crop

### LINKED ISSUE #12680: [regression] mkv/webm with resolution change does not work properly anymore
### Important Information

Provide following Information:
- mpv version ```mpv --version
mpv 0.36.0-UNKNOWN Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Jan  1 1980 00:00:00
libplacebo version: v7.339.0
FFmpeg version: 5.1.git
FFmpeg library versions:
   libavutil       58.27.100
   libavcodec      60.30.102
   libavformat     60.15.100
   libswscale      7.4.100
   libavfilter     9.11.100
   libswresample   4.11.100```
- Platform and Version: `nixos linux 6.5.7`
- Source of the mpv binary: latest master

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. play mkv/webm file with resolution changes

### Expected behavior

resolution should change as it changes in streams in file

### Actual behavior

mpv sticks to initial resolution

### Log file
```
cplayer] Command line options: '--script=/nix/store/yjqima8ni6yvl0kk4n2vr8nz9chwq014-mpv-quality-menu-4.1.0/share/mpv/scripts/quality-menu.lua' '--script=/nix/store/h5pligjrqwq883nhkracc5q8lrlhigyf-mpv_sponsorblock-unstable-2023-01-30/share/mpv/scripts/sponsorblock.lua' '--script=/nix/store/4kgcq0rhpc166bl42jcdaw785ngs3019-mpv-playlistmanager-unstable-2023-08-09/share/mpv/scripts/playlistmanager.lua' '--no-config' './video_test1.mkv' '-v'
[cplayer] mpv 0.36.0-UNKNOWN Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Jan  1 1980 00:00:00
[cplayer] libplacebo version: v7.339.0
[cplayer] FFmpeg version: 5.1.git
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.27.100
[cplayer]    libavcodec      60.30.102
[cplayer]    libavformat     60.15.100
[cplayer]    libswscale      7.4.100
[cplayer]    libavfilter     9.11.100
[cplayer]    libswresample   4.11.100
[cplayer] 
[cplayer] Configuration: -Dauto_features=auto -Dwrap_mode=nodownload -Ddefault_library=shared -Dlibmpv=true -Dlibarchive=enabled -Dmanpage-build=enabled -Dcdda=enabled -Ddvbin=enabled -Ddvdnav=enabled -Dopenal=disabled -Dsdl2=disabled -Dswift-build=disabled -Dmacos-cocoa-cb=disabled -Dcuda-hwaccel=disabled -Dcuda-interop=disabled -Dprefix=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git -Dbindir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/bin -Dincludedir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/include -Dinfodir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/share/info -Dlibdir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/lib -Dlibexecdir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/libexec -Dlocaledir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/share/locale -Dmandir=/nix/store/xyasvk2didd9f0y2n2igichz8if47pip-mpv-git-man/share/man -Dsbindir=/nix/store/4hs8pnb0h3y2paxxy6j0v7ki1v7nwcmk-mpv-git/sbin -Dbuildtype=plain
[cplayer] List of enabled features: alsa av-channel-layout avif-muxer build-date cdda cplugins dmabuf-interop-gl dmabuf-interop-pl drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg gbm gl glibc-thread-name glob glob-posix gpl iconv javascript jpeg jpegxl lavu-uuid lcms2 libarchive libass libavdevice libbluray libdl libm libplacebo librt linux-fstatfs lua manpage-build noexecstack pipewire posix posix-shm ppoll rubberband rubberband-3 shaderc stdatomic threads uchardet vaapi vaapi-drm vaapi-egl vaapi-libplacebo vaapi-x11 vector vk-khr-display vt.h vulkan vulkan-interop x11 xv zimg zimg-st428 zlib
[cplayer] Setting option 'scripts-append' = '/nix/store/yjqima8ni6yvl0kk4n2vr8nz9chwq014-mpv-quality-menu-4.1.0/share/mpv/scripts/quality-menu.lua' (flags = 8)
[cplayer] Setting option 'scripts-append' = '/nix/store/h5pligjrqwq883nhkracc5q8lrlhigyf-mpv_sponsorblock-unstable-2023-01-30/share/mpv/scripts/sponsorblock.lua' (flags = 8)
[cplayer] Setting option 'scripts-append' = '/nix/store/4kgcq0rhpc166bl42jcdaw785ngs3019-mpv-playlistmanager-unstable-2023-08-09/share/mpv/scripts/playlistmanager.lua' (flags = 8)
[cplayer] Setting option 'config' = 'no' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Waiting for scripts...
[cplayer] Can't find script 'uosc' to send message to.
[playlistmanager] updating options 
[cplayer] Set property: user-data/osc/visibility="auto" -> 1
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: quality_menu/on_load
[osd/libass] libass API version: 0x1701000
[osd/libass] libass source: tarball: 0.17.1
[osd/libass] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 7.3.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[ifo_dvdnav] Opening ./video_test1.mkv
[bdmv/bluray] Opening ./video_test1.mkv
[file] Opening ./video_test1.mkv
[demux] Trying demuxers for level=normal.
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[osd/libass] libass API version: 0x1701000
[osd/libass] libass source: tarball: 0.17.1
[mkv] Deferring reading cues.
[mkv] All headers are parsed!
[demux] Detected file format: Matroska
[cplayer] Opening done: ./video_test1.mkv
[osd/libass] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 7.3.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[find_files] Loading external files in ./
[cplayer] Running hook: ytdl_hook/on_preloaded
[mkv] select track 0
[cplayer]  (+) Video --vid=1 (vp9 1024x768)
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0
[vo/gpu/x11] Display 0 (HDMI-1): [0, 0, 1920, 1200] @ 59.950171 FPS
[vo/gpu/x11] Display 1 (DP-1): [3840, 0, 5760, 1200] @ 59.950171 FPS
[vo/gpu/x11] Display 2 (DP-2): [1920, 0, 3840, 1200] @ 59.950171 FPS
[vo/gpu/x11] Current display FPS: 59.950171
[vo/gpu/opengl] EGL_VERSION=1.5
[vo/gpu/opengl] EGL_VENDOR=Mesa Project
[vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] Choosing visual EGL config 0x15, visual ID 0x21
[vo/gpu/x11] The XPresent extension was found.
[vo/gpu/x11] XPresent enabled.
[vo/gpu/opengl] GL_VERSION='4.6 (Core Profile) Mesa 23.0.3'
[vo/gpu/opengl] Detected desktop OpenGL 4.6.
[vo/gpu/opengl] GL_VENDOR='Intel'
[vo/gpu/opengl] GL_RENDERER='Mesa Intel(R) Arc(tm) A380 Graphics (DG2)'
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.60'
[vo/gpu/opengl] Loaded extension GL_KHR_debug.
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Assuming 59.950171 FPS for display sync.
[vd] Container reported FPS: 0.000000
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     vp9_v4l2m2m (vp9) - V4L2 mem2mem VP9 decoder wrapper
[vd]     libvpx-vp9 (vp9) - libvpx VP9
[vd]     vp9_qsv (vp9) - VP9 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder vp9
[vd] No hardware decoding requested.
[vd] Using software decoding.
[vd] Detected 5 logical cores.
[vd] Requesting 6 threads for decoding.
[vd] Selected codec: Google VP9
[vf] User filter list:
[vf]   (empty)
[cplayer] Starting playback...
[vo/gpu] DR path suspected slow/uncached, disabling.
[vd] DR failed - disabling.
[vd] Using software decoding.
[vd] Decoder format: 1920x1080 [0:1] yuv444p auto/auto/auto/limited/auto CL=unknown crop=1920x1080+0+0
[vd] Using container aspect ratio.
[vf] [in] 1920x1080 yuv444p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264 crop=1024x768+0+0
[vf] [userdeint] 1920x1080 yuv444p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264 crop=1024x768+0+0
[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x1080 yuv444p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264 crop=1024x768+0+0
[vf] [autorotate] (disabled)
[vf] [convert] 1920x1080 yuv444p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264 crop=1024x768+0+0
[vf] [convert] (disabled)
[vf] [out] 1920x1080 yuv444p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264 crop=1024x768+0+0
[cplayer] VO: [gpu] 1920x1080 yuv444p
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1920x1080 yuv444p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264 crop=1024x768+0+0
[vo/gpu] Resize: 1024x768
[vo/gpu] Window size: 1024x768 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1024x768 -> (0, 0) 1024x768
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 10
[vo/gpu] Texture for plane 0: 1920x1080
[vo/gpu] Texture for plane 1: 1920x1080
[vo/gpu] Texture for plane 2: 1920x1080
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Dither to 10.
[cplayer] first video frame after restart shown
[cplayer] playback restart complete @ 0.000000, audio=eof, video=playing
[vo/gpu/x11] Disabling screensaver.
[osd/libass] libass API version: 0x1701000
[osd/libass] libass source: tarball: 0.17.1
[osd/libass] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 7.3.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[statusline] V: 00:00:00 / 00:01:16 (0%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:01 / 00:01:16 (1%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:01 / 00:01:16 (1%)
[osd/libass] fontselect: (sans-serif, 400, 0) -> /nix/store/r2nlgqdl274mgsilrj8407gx0s6vailw-dejavu-fonts-2.37/share/fonts/truetype/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[vo/gpu] Reallocating OSD texture to 1024x256.
[statusline] V: 00:00:01 / 00:01:16 (2%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:03 / 00:01:16 (5%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:07 / 00:01:16 (10%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:08 / 00:01:16 (11%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:08 / 00:01:16 (11%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:09 / 00:01:16 (12%)
[cplayer] Set property: user-data/osc/margins={"l":0,"b":0,"r":0,"t":0} -> 1
[statusline] V: 00:00:10 / 00:01:16 (13%)
[mkv] queuing seek to 15.000000
[mkv] execute seek (to 15.000000 flags 4)
[mkv] Seeking to 452399 to read header element 0x1c53bb6b.
[file] stream level seek from 131072 to 452399
[mkv] Parsing cues...
[mkv] Discarding potentially broken or useless index.
[file] stream level seek from 452440 to 416
[mkv] creating index until TC 14995000000
[vo/gpu/x11] Enabling screensaver.
[file] stream level seek from 329023 to 260878
[mkv] seek done
[vd] Decoder format: 1920x1080 [0:1] yuv444p auto/auto/auto/limited/auto CL=unknown crop=1920x1080+0+0
[vd] Using container aspect ratio.
[statusline] V: 00:00:15 / 00:01:16 (20%)
[osd/libass] libass API version: 0x1701000
[osd/libass] libass source: tarball: 0.17.1
[osd/libass] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 7.3.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /nix/store/r2nlgqdl274mgsilrj8407gx0s6vailw-dejavu-fonts-2.37/share/fonts/truetype/DejaVuSans.ttf, 0, DejaVuSans
[vo/gpu] Reallocating OSD texture to 1024x128.
[cplayer] first video frame after restart shown
[cplayer] playback restart complete @ 60.000000, audio=eof, video=playing
[vo/gpu/x11] Disabling screensaver.
[statusline] V: 00:01:00 / 00:01:16 (79%)
[mkv] queuing seek to 65.200000
[mkv] execute seek (to 65.200000 flags 4)
[mkv] creating index until TC 65195000000
[file] stream level seek from 452440 to 260878
[mkv] seek done
[mkv] EOF reached.
[vf] filter input EOF
[vf] filter output EOF
[cplayer] video EOF reached
[cplayer] playback restart complete @ -9223372036854775808.000000, audio=eof, video=eof
[cplayer] EOF code: 1  
[cplayer] finished playback, success (reason 0)
[cplayer] 
[cplayer] Exiting... (End of file)
[vo/gpu/x11] Enabling screensaver.
```

### Sample files

[video_test1.WEBM](https://github.com/mpv-player/mpv/assets/202772/37e3c631-8834-4d6f-9dde-4f7d18e337d4)

### PR DESCRIPTION
**Pull request by Dudemanguy**
track->v_width isn't always the same as track->v_dwidth. So the crop calculation logic here could actually change the dimensions of the video even if there was no crop set simply because track->v_width is a different value. Rearrange the ternary a bit so we keep the same logic as before in the no-crop case. Fixes #12680.

### CODE REVIEW

File: demux/demux_mkv.c [hunk 1]
```diff
@@ -1522,10 +1522,8 @@ static int demux_mkv_open_video(demuxer_t *demuxer, mkv_track_t *track)
 
     sh_v->crop.x0 = track->v_crop_left_set ? track->v_crop_left : 0;
     sh_v->crop.y0 = track->v_crop_top_set ? track->v_crop_top : 0;
-    sh_v->crop.x1 = track->v_width -
-                        (track->v_crop_right_set ? track->v_crop_right : 0);
-    sh_v->crop.y1 = track->v_height -
-                        (track->v_crop_bottom_set ? track->v_crop_bottom : 0);
+    sh_v->crop.x1 = track->v_crop_right_set ? track->v_width - track->v_crop_right : 0;
+    sh_v->crop.y1 = track->v_crop_bottom_set ? track->v_height - track->v_crop_bottom : 0;
```
Comment (kasper93) [inline demux/demux_mkv.c:1526]: This doesn't work, because if you have let's say only `v_crop_right_set == true`, you will end up with crop Wx0+0+0 which is invalid.

Comment (Dudemanguy) [reply demux/demux_mkv.c:1526]: Wouldn't the same thing happen before? I thought detecting a file with broken crop parameters was a feature.

Comment (Dudemanguy) [reply demux/demux_mkv.c:1526]: Oh nevermind I get what you mean now.

File: demux/demux_mkv.c [hunk 2]
```diff
@@ -1522,10 +1522,12 @@ static int demux_mkv_open_video(demuxer_t *demuxer, mkv_track_t *track)
 
     sh_v->crop.x0 = track->v_crop_left_set ? track->v_crop_left : 0;
     sh_v->crop.y0 = track->v_crop_top_set ? track->v_crop_top : 0;
-    sh_v->crop.x1 = track->v_width -
+    if (track->v_crop_right_set || track->v_crop_bottom_set) {
```
Comment (kasper93) [inline demux/demux_mkv.c:1525]: This also doesn't work, because you can end up with crop `0x0+X+Y` which is invalid. Could you explain why you are trying to change the cropping logic here?

Comment (Dudemanguy) [reply demux/demux_mkv.c:1525]: Because this is what's causing #12680. That file doesn't have crop metadata. It stupidly has both `width` and `Original width`. Because `track->v_width` isn't the same as `track->v_dwidth` (ditto for the height), it causes a crop to be applied. ffplay, vlc and mpv before 338f31e0b694eec2f250b62cf7707ec9bdf71daf use the 1920x1080 dimensions which is what I presume is desired.

Basically I'm just trying to keep everything 0 if there's no actual crop set. I'm assuming that's valid (seems like it should be).

Comment (kasper93) [reply demux/demux_mkv.c:1525]: > Because this is what's causing https://github.com/mpv-player/mpv/issues/12680.

Well, yes. But the code is correct. Container is lying, so there is no good way to handle that. Like I said we can add an option to ignore container and prefer bit-stream metadata, but we wouldn't make it default anyway, so the user for broken files can force ignore container by `--video-crop=0x0+0+0`

> ffplay, vlc 

Both of them probably cannot even crop mkv. So it is hardly an argument.

> Basically I'm just trying to keep everything 0 if there's no actual crop set. I'm assuming that's valid (seems like it should be).

It is valid, because I made it so, but (0, 0, w, h) is also valid crop and not doing that is just hacky. Imagine that container has both incorrect PixelWidth and crop, you couldn't set to 0,0,0,0

If we really care about such files I would prefer similar option `--video-size-method=<bitstream|container>` instead of hacking it in demuxer. And handle the same way as `--video-aspect-method` in `fix_image_params`

Comment (Dudemanguy) [reply demux/demux_mkv.c:1525]: I'm not saying the code is wrong, but it assumes that the file doesn't have broken tags for the calculation. If the container in question doesn't have any actual crop (like that issue), why bother trying to match `(0, 0, w, h)`? It can lead to undesirable results. If we don't need to trust the metadata, then why have the extra step?

I guess this is my fault. I didn't realize the internal representation for "no crop" for `(0, 0, w, h)`. I thought it was all zeros. That does make this not the right solution I suppose.

Comment (kasper93) [reply demux/demux_mkv.c:1525]: > I guess this is my fault. I didn't realize the internal representation for "no crop" in image params was (0, 0, w, h). I thought it was all zeros. That does make this not the right solution I suppose.

All zeros are also fine, mostly for the compatibility with "no-crop" case like you said. Both should be equivalent.

> If we don't need to trust the metadata, then why have the extra step?

I just don't like supporting broken files, because this embraces them and let users generate more of broken files. I'm fine with setting it to (0,0,0,0) I'm just voicing my concern that it is not the best solution and will still break if any of the crop parameters are available.

Comment (Dudemanguy) [reply demux/demux_mkv.c:1525]: Well we can't stop people from making broken files as much as I'd like to.

>I'm just voicing my concern that it is not the best solution and will still break if any of the crop parameters are available.

If you have a file with totally broken crop parameters and width/heights, I think that one is just going to have to be on you. `--video-crop` still still override it. However while we're on the topic does it make sense to use `dw` and `dh` here instead of `track->v_width/track->v_height` directly? I don't remember my mkv specs but displaywidth is supposed to be preferred right?

Comment (kasper93) [reply demux/demux_mkv.c:1525]: > However while we're on the topic does it make sense to use dw and dh here instead of track->v_width/track->v_height directly? I don't remember my mkv specs but displaywidth is supposed to be preferred right?

Crop is suppose to be applied to pixel width and display width applied on top. See also https://github.com/mpv-player/mpv/pull/12683 because I just noticed that yesterday.

Like I said I'm fine with setting it to 0,0,0,0 if none crop is set in container. It just produces two different values that should be treated the same. Similarly I would need to rewrite #12683 to take that into account. But if we remember about this throughout the code it should be ok.

Comment (Dudemanguy) [reply demux/demux_mkv.c]: OK I reworked this part a bit which should do the trick I think.

File: demux/demux_mkv.c [hunk 3]
```diff
@@ -1510,16 +1505,23 @@ static int demux_mkv_open_video(demuxer_t *demuxer, mkv_track_t *track)
...
+    // file may have broken width/height tags.
+    if (track->v_crop_left || track->v_crop_top ||
+        track->v_crop_right || track->v_crop_bottom)
+    {
+        sh_v->crop = crop;
+    }
+
+    int dw = track->v_dwidth_set ? track->v_dwidth : mp_rect_w(crop);
+    int dh = track->v_dheight_set ? track->v_dheight : mp_rect_h(crop);
+    struct mp_image_params p = {.w = mp_rect_w(crop), .h = mp_rect_h(crop)};
```
Comment (kasper93) [inline demux/demux_mkv.c:1524]: Need to guard `mp_rect_*(crop)` calls. Something like this should work.

```suggestion
    bool crop_set = track->v_crop_left || track->v_crop_top || track->v_crop_right || track->v_crop_bottom;
    if (crop_set)
        sh_v->crop = crop;

    int w = crop_set ? mp_rect_w(crop) : track->v_width;
    int h = crop_set ? mp_rect_h(crop) : track->v_height;
    int dw = track->v_dwidth_set ? track->v_dwidth : w;
    int dh = track->v_dheight_set ? track->v_dheight : h;
    struct mp_image_params p = {.w = w, .h = h};
```

And while you are changing this please adjust `mp_image_to_av_frame` to support (0,0,0,0) crop, set the crop only if valid.

Comment (Dudemanguy) [reply demux/demux_mkv.c:1524]: >Need to guard mp_rect_*(crop) calls. 

Shouldn't it be the same? If there's no cropping then `mp_rect_w` is equal to `track->v_width` which is what we want. Ditto for the height case.

>And while you are changing this please adjust mp_image_to_av_frame to support (0,0,0,0) crop

I don't think this is needed? I'll admit I didn't 100% verify all of the code here, but I don't believe image param crop in `mp_image_to_av_frame` is the same as what's set in here. At least that's what the `video-params/crop-*` properties suggest. I assume that the calculation in `player/video.c` handles this already and makes the params the actual (0, 0, w, h) value which is what `mp_image_to_av_frame` and anything else that uses the `mp_image` gets.

Comment (kasper93) [reply demux/demux_mkv.c:1524]: > Shouldn't it be the same? If there's no cropping then mp_rect_w is equal to track->v_width which is what we want. 

Yes, I'm not thinking late at night. I was focused that PAR will be wrong, but it will be wrong anyway, because actually the v_width is wrong, not the crop. I guess we have option to ignore that.

> I don't believe image param crop in mp_image_to_av_frame is the same as what's set in here.

True, I see I added special case for (0,0,0,0) crop and it does the job. Although I noticed one other issue, will fix tomorrow. And take a look again at your change, but looks good actually.
