### PR TITLE
Use /dev/tty instead of stdin for terminal input

### LINKED ISSUE #4190: Terminal input is ignored when playing stdin
### mpv version and platform

mpv git-6028244160 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 27 22:36:29 MSK 2017

Platform is Linux

### Reproduction steps

`mpv --vo=null - < some-streamable-file`

(--vo=null is to keep mpv from creating a window which would be able to receive input)

### Expected behavior

Controls (e.g. space, p, q, etc) work

### Actual behavior

Any input is ignored

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/804838/output.txt)

(I ran mpv, tried pressing some keys, closed it with ^C)

### PR DESCRIPTION
**Pull request by SirCmpwn**
Fixes #4190

This allows you to use terminal input even if you've piped something
into mpv.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wm4** [comment]
Against.

**Comment by SirCmpwn** [comment]
Rationale?

**Comment by SirCmpwn** [comment]
Currently listening to `ls -tc | head -n 9 | xargs -d '\n' ~/sources/mpv/build/mpv --no-video`

**Comment by rossy** [comment]
+1. I don't think it's uncommon for interactive Linux programs to open /dev/tty and read user input. ``less`` does this too. I think a user would expect a command like ``find . | mpv --playlist=-`` to read from the tty, similar to how ``cat file | less`` reads from the tty.

**Comment by SirCmpwn** [comment]
It's not just Linux either, /dev/tty is standardized in POSIX.

**Comment by SirCmpwn** [comment]
It's not just Linux either, /dev/tty is standardized in POSIX.

**Comment by rossy** [comment]
Ah, I didn't know that. You're right. Turns out this behaviour is even standardized for the ``more`` util: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/more.html#tag_20_81_07

**Comment by SirCmpwn** [comment]
`more` wouldn't even work without using `/dev/tty` because `/dev/tty` is the only correct way to handle this.

**Comment by timofonic** [comment]
@SirCmpwn @wm4 What happened to this? :O

**Comment by haasn** [comment]
This affects me too. I often “generate_playlist.sh | mpv -playlist=-”, so being able to use terminal input in mpv would be a plus.

**Comment by haasn** [comment]
Actually I think I can get away with “mpv --playlist=<(generate_playlist.sh)”

**Comment by Q3CPMA** [comment]
Nice idea.

**Comment by SirCmpwn** [comment]
Rebased and re-tested, still good to go.

**Comment by bkazemi** [comment]
To give a real example of the necessity: I use LFTP to play songs stored on one of my LAN computers, and you must use a pipe to communicate with local programs.

**Comment by lachs0r** [comment]
In that case you should just use curlftpfs (or sshfs if that computer runs some SSH server).

**Comment by SirCmpwn** [comment]
I agree that his use case is pretty weird, but using /dev/tty for console input is still more correct than reading stdin regardless.

**Comment by bkazemi** [comment]
curlftpfs is dead, so LFTP is the probably the most convient way to do this for FTP IMHO.

**Comment by timofonic** [comment]
@wm4 @SirCmpwn @haasn @rossy What happened to this? Any updates?

**Comment by haasn** [comment]
Patch stopped applying. Also, I noticed that this patch uses global state. Isn't that thread-unsafe?

**Comment by SirCmpwn** [comment]
I'm tired of this shit. If you want to adopt this patch and puzzle out wm4's nonsense, be my guest.

**Comment by haasn** [comment]
Fair enough. I've personally given up trying to merge changes into mpv, but I've rebased the patch for my own use:

```diff
From e0479c261b6f1249ffb90bfae6db86a8972c17cd Mon Sep 17 00:00:00 2001
From: Drew DeVault <sir@cmpwn.com>
Date: Tue, 18 Jul 2017 11:53:37 -0400
Subject: [PATCH] Use /dev/tty instead of stdin for terminal input

Fixes #4190

This allows you to use terminal input even if you've piped something
into mpv.
---
 osdep/terminal-unix.c | 26 +++++++++++++++++---------
 1 file changed, 17 insertions(+), 9 deletions(-)

diff --git a/osdep/terminal-unix.c b/osdep/terminal-unix.c
index da6ccfe7f2..b3e0cbe446 100644
--- a/osdep/terminal-unix.c
+++ b/osdep/terminal-unix.c
@@ -45,6 +45,8 @@
 static volatile struct termios tio_orig;
 static volatile int tio_orig_set;
 
+int tty_in, tty_out;
+
 struct key_entry {
     const char *seq;
     int mpkey;
@@ -171,7 +173,7 @@ static struct termbuf buf;
 
 static bool getch2(struct input_ctx *input_ctx)
 {
-    int retval = read(0, &buf.b[buf.len], BUF_LEN - buf.len);
+    int retval = read(tty_in, &buf.b[buf.len], BUF_LEN - buf.len);
     /* Return false on EOF to stop running select() on the FD, as it'd
      * trigger all the time. Note that it's possible to get temporary
      * EOF on terminal if the user presses ctrl-d, but that shouldn't
@@ -259,9 +261,9 @@ static void enable_kx(bool enable)
     // tty. Note that stderr being redirected away has no influence over mpv's
     // I/O handling except for disabling the terminal OSD, and thus stderr
     // shouldn't be relied on here either.
-    if (isatty(STDOUT_FILENO)) {
+    if (isatty(tty_out)) {
         char *cmd = enable ? "\033=" : "\033>";
-        (void)write(STDOUT_FILENO, cmd, strlen(cmd));
+        (void)write(tty_out, cmd, strlen(cmd));
     }
 }
 
@@ -273,7 +275,7 @@ static void do_activate_getch2(void)
     enable_kx(true);
 
     struct termios tio_new;
-    tcgetattr(0,&tio_new);
+    tcgetattr(tty_in,&tio_new);
 
     if (!tio_orig_set) {
         tio_orig = tio_new;
@@ -298,7 +300,7 @@ static void do_deactivate_getch2(void)
     if (tio_orig_set) {
         // once set, it will never be set again
         // so we can cast away volatile here
-        tcsetattr(0, TCSANOW, (const struct termios *) &tio_orig);
+        tcsetattr(tty_in, TCSANOW, (const struct termios *) &tio_orig);
     }
 
     getch2_active = 0;
@@ -326,7 +328,7 @@ static void getch2_poll(void)
         return;
 
     // check if stdin is in the foreground process group
-    int newstatus = (tcgetpgrp(0) == getpgrp());
+    int newstatus = (tcgetpgrp(tty_in) == getpgrp());
 
     // and activate getch2 if it is, deactivate otherwise
     if (newstatus)
@@ -380,7 +382,7 @@ static void *terminal_thread(void *ptr)
         getch2_poll();
         struct pollfd fds[2] = {
             {.events = POLLIN, .fd = death_pipe[0]},
-            {.events = POLLIN, .fd = STDIN_FILENO},
+            {.events = POLLIN, .fd = tty_in},
         };
         poll(fds, stdin_ok ? 2 : 1, -1);
         if (fds[0].revents)
@@ -407,10 +409,16 @@ void terminal_setup_getch(struct input_ctx *ictx)
     if (mp_make_wakeup_pipe(death_pipe) < 0)
         return;
 
+    tty_in = tty_out = open("/dev/tty", O_RDWR);
+    if (tty_in < 0) {
+        tty_in = STDIN_FILENO;
+        tty_out = STDOUT_FILENO;
+    }
+
     // Disable reading from the terminal even if stdout is not a tty, to make
     //   mpv ... | less
     // do the right thing.
-    read_terminal = isatty(STDIN_FILENO) && isatty(STDOUT_FILENO);
+    read_terminal = isatty(tty_in) && isatty(tty_out);
 
     input_ctx = ictx;
 
@@ -460,7 +468,7 @@ bool terminal_in_background(void)
 void terminal_get_size(int *w, int *h)
 {
     struct winsize ws;
-    if (ioctl(0, TIOCGWINSZ, &ws) < 0 || !ws.ws_row || !ws.ws_col)
+    if (ioctl(tty_in, TIOCGWINSZ, &ws) < 0 || !ws.ws_row || !ws.ws_col)
         return;
 
     *w = ws.ws_col;
-- 
2.15.0
```

**Comment by SirCmpwn** [comment]
It was merged into [ffmpv](https://github.com/ffmpv/ffmpv), if you want to hop on that particular bandwagon.

**Comment by wm4** [comment]
Not my problem anymore. Do what you want.

**Comment by Q3CPMA** [comment]
Is there a reason for not merging this?

**Comment by SirCmpwn** [comment]
Rebased and re-tested, this still works correctly.

File: osdep/terminal-unix.c [hunk 1]
```diff
@@ -407,10 +409,16 @@ void terminal_setup_getch(struct input_ctx *ictx)
...
+    if (tty_in < 0) {
+        tty_in = STDIN_FILENO;
+        tty_out = STDOUT_FILENO;
+    }
+
     // Disable reading from the terminal even if stdout is not a tty, to make
     //   mpv ... | less
     // do the right thing.
-    read_terminal = isatty(STDIN_FILENO) && isatty(STDOUT_FILENO);
+    read_terminal = isatty(tty_in) && isatty(tty_out);
```
Comment (rossy) [inline osdep/terminal-unix.c]: This breaks the use-case in the above comment. It might make sense to keep the ``isatty(STDOUT_FILENO)`` test, since both ``mpv ... | less`` and ``find ... | mpv --playlist=-`` will work as expected.

Comment (jeeb) [reply osdep/terminal-unix.c]: Valid concern, I guess. Esp. since the use case is mentioned there in the comment. Otherwise if there are no additional issues found it's highly likely that it's getting to LGTM level.

File: osdep/terminal-unix.c [hunk 2]
```diff
@@ -407,10 +409,16 @@ void terminal_setup_getch(struct input_ctx *ictx)
     if (mp_make_wakeup_pipe(death_pipe) < 0)
         return;
 
+    tty_in = tty_out = open("/dev/tty", O_RDWR);
```
Comment (jeeb) [inline osdep/terminal-unix.c]: Even though in 99% of all cases the application will finish by closing itself, I would guess it's good manners to close the file descriptor at the end around `terminal_uninit`.

Additionally, the POSIX [CLOEXEC](http://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html) flag could be utilized when `open()`'ing the file.

**Comment by SirCmpwn** [comment]
Updated and rebased.

**Comment by SirCmpwn** [comment]
Well, updated.

**Comment by SirCmpwn** [comment]
I updated this to use select instead of poll, because apparently macOS does not support polling device files. This probably led to some undiscovered bugs before, too.

**Comment by garoto** [comment]
I hate to be the person to do this, but @rossy, can you consider to make this into a patch for the win32 console subsystem? Will paypal you AU 50 bucks for this to happen.
