### PR TITLE
m_option: fix float option values <= 0

### LINKED ISSUE #15728: sub-line-spacing should be allowed to be negative
### mpv Information

```bash
mpv v0.39.0-635-g20375d1133 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Jan 24 2025 09:40:54
libplacebo version: v7.350.0 (v7.349.0-30-g056b8520-dirty)
FFmpeg version: N-118350-ge20ee9f9ae
FFmpeg library versions:
   libavcodec      61.31.101
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.106
   libavutil       59.55.100
   libswresample   5.4.100
   libswscale      8.13.100
```

### Other Information

```text
- Linux version: Arch
- Kernel Version:
- GPU Model:
- Mesa/GPU Driver Version:
- Window Manager and Version:
- Source of mpv: git
- Latest known working version: Yesterday's build
- Issue started after the following happened: Some recent commit
```

### Reproduction Steps

Set `sub-line-spacing` to `-15`.

### Expected Behavior

The renderer used to draw the lines closer together.

### Actual Behavior

The option is ignored and the following error is printed:

```
The sub-line-spacing option is out of range: -15
Error parsing option sub-line-spacing (parameter is outside values allowed for option)
```

### Log File

[output.txt](https://github.com/user-attachments/files/18533940/output.txt)

### Sample Files

_No response_

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

### PR DESCRIPTION
**Pull request by guidocella**
FLT_MIN is a small positive number (1.175494e-38), so the check v < FLT_MIN introduced in 0e7f9c39dc made all 0 and negative float option values error, e.g. panscan=0 or video-align-y=-1.

Fixes #15728.

### CODE REVIEW

File: options/m_option.c [hunk 1]
```diff
@@ -1147,7 +1147,7 @@ static int clamp_float(const m_option_t *opt, double *val)
         v = FLT_MAX;
         r = M_OPT_OUT_OF_RANGE;
     }
-    if (isfinite(v) && v < FLT_MIN) {
+    if (isfinite(v) && v < -FLT_MAX) {
         v = FLT_MIN;
```
Comment (sfan5) [inline options/m_option.c:1151]:
```suggestion
        v = -FLT_MAX;
```

**Comment by sfan5** [comment]
can you also include a "fixes:" line in the commit message?

**Review by sfan5 — APPROVED** [review]
