### PR TITLE
console.lua: include more characters in selectable items

### LINKED ISSUE #15944: `input.select()` menu sometimes shows garbage character at the end
### mpv Information

```bash
mpv v0.39.0-876-gb848ffad1 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Feb 22 2025 15:04:07
libplacebo version: v7.350.0 (v7.349.0-37-g7de2415-dirty)
FFmpeg version: N-118521-gd1ed5c06e
FFmpeg library versions:
   libavcodec      61.33.102
   libavdevice     61.4.100
   libavfilter     10.9.100
   libavformat     61.9.107
   libavutil       59.57.100
   libswresample   5.4.100
   libswscale      8.13.100
```

### Other Information

```text
- Windows version: Win11 24H2
- GPU model, driver and version:
- Source of mpv: https://github.com/zhongfly/mpv-winbuild/releases/tag/2025-02-22-b848ffa
- Latest known working version:
- Issue started after the following happened:
```

### Reproduction Steps

image
The reason is  that `sub(1, 300)`  may cut off multi-bytes characters, causing garbage character at the end,
should find the previous UTF-8 character before position 300.
https://github.com/mpv-player/mpv/blob/deb27c091ac7c4c4327c5494b111bf5b7a52bac1/player/lua/console.lua#L1993-L1995

### Expected Behavior

no garbage character

### Actual Behavior

sometimes shows garbage character at the end

### Log File

N/A

### Sample Files

N/A

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

### PR DESCRIPTION
**Pull request by guidocella**
300 characters doesn't always fill the window.

Fixes #15944.

### CODE REVIEW

File: player/lua/console.lua [hunk 1]
```diff
@@ -1990,9 +1990,16 @@ mp.register_script_message('get-input', function (script_name, args)
...
         selectable_items = {}
+
+        -- Limit the number of characters to prevent libass from freezing mpv.
+        -- Not important for terminal output.
+        local limit = terminal_output() and 5000
+                      or 5 * mp.get_property_native('osd-width') / opts.font_size
+
         for i, item in ipairs(args.items) do
-            selectable_items[i] = item:gsub("[\r\n].*", "⋯"):sub(1, 300)
+            selectable_items[i] = item:gsub("[\r\n].*", "⋯"):sub(1, limit)
```
Comment (kasper93) [inline player/lua/console.lua:2000]: Should we add `⋯` when it is cut by the limit?

Comment (guidocella) [reply player/lua/console.lua:2000]: The limit should not be visibile, we want to go beyond the window width and let it be clipped.

File: player/lua/console.lua [hunk 2]
```diff
@@ -1990,9 +1990,16 @@ mp.register_script_message('get-input', function (script_name, args)
 
     if args.items then
         selectable_items = {}
+
+        -- Limit the number of characters to prevent libass from freezing mpv.
+        -- Not important for terminal output.
+        local limit = terminal_output() and 5000
+                      or (5 * mp.get_property_native('osd-width') / opts.font_size)
```
Comment (kasper93) [inline player/lua/console.lua:1997]: it could be `opts.font_size * 0.6` for width. I think 0.6 is ratio is common. But either way, does it has to be 5 times? Seems bit much?

**Review by kasper93 — APPROVED** [review]
