### PR TITLE
wayland: add cursor-shape-v1 support

### LINKED ISSUE #11671: [wayland] cursor size not respected
Inside the mpv window, cursor size is not respected and changes;  
I noticed this is a Wayland-only issue, not happening on X11;  

 - mpv 0.35.1
 - Arch Linux x86_64
 - GNOME 44
 - Wayland

Here is a screencast showing the issue:
[Screencast from 2023-05-07 22-24-36.webm](https://user-images.githubusercontent.com/545463/236701318-6c33d577-3421-4164-b13a-b52247005965.webm)
where the cursor become smaller as soon as it goes on.

### Reproduction steps
(Prerequisite: have a different cursor size)
Move the cursor in and out the mpv window in a Wayland environment;

### Expected behavior
Cursor should stay the same

### Actual behavior
Cursor's size changes to a default value

### Log file
Useless: no messages when moving the cursor

### PR DESCRIPTION
**Pull request by Dudemanguy**
This protocol no longer requires us to draw a separate cursor surface and all of that horrible stuff. We can just ask the compositor for the default cursor instead since that's literally all mpv cares about.

Should theoretically fix #11671.

Tested with https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4106 + https://github.com/swaywm/sway/pull/7571. Also requires wayland-protocols from master right now hence draft.

### CODE REVIEW

File: video/out/wayland_common.c [hunk 1]
```diff
@@ -1703,21 +1726,35 @@ static void set_content_type(struct vo_wayland_state *wl)
 #endif
 }
 
+static void set_cursor_shape(struct vo_wayland_state *wl)
+{
+    if (!wl->cursor_shape_device)
```
Comment (Nefsen402) [inline video/out/wayland_common.c:1731]: The only place where this function gets called from guarantees the existence of this object. The check should be removed.

Comment (Dudemanguy) [reply video/out/wayland_common.c]: Thanks for looking!

File: video/out/wayland_common.c [hunk 2]
```diff
@@ -1561,7 +1573,18 @@ static int get_mods(struct vo_wayland_state *wl)
...
 }
 
-static void greatest_common_divisor(struct vo_wayland_state *wl, int a, int b) {
+static void get_shape_device(struct vo_wayland_state *wl)
+{
+#if HAVE_WAYLAND_PROTOCOLS_1_32
+    if (!wl->cursor_shape_device) {
+        wl->cursor_shape_device = wp_cursor_shape_manager_v1_get_pointer(wl->cursor_shape_manager,
+                                                                         wl->pointer);
+    }
```
Comment (Nefsen402) [inline video/out/wayland_common.c:1582]:
```suggestion
    if (!wl->cursor_shape_device && wl->cursor_shape_manager) {
        wl->cursor_shape_device = wp_cursor_shape_manager_v1_get_pointer(wl->cursor_shape_manager,
                                                                         wl->pointer);
    }
```
Sorry, one more thing: Cursor shape manager can be null if the compositor does not support it but mpv was built with support. This function gets unconditionally called when setting up the cursor.

Comment (Dudemanguy) [reply video/out/wayland_common.c:1582]: Good catch.

**Comment by Nefsen402** [comment]
LGTM

**Comment by Dudemanguy** [comment]
Works fine and since wayland protocols 1.32 is out now, there's no reason to hold this back.
