### PR TITLE
vo_gpu/vo_gpu_next: scaler fixes

### LINKED ISSUE #12031: `set dscale ""` at runtime would crash
### Important Information

Provide following Information:
- mpv version
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230726
- Windows Version
22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230726
- If known which version of mpv introduced the problem
N/a
- Possible screenshot or video of visual glitches
N/a

### Reproduction steps

0. load a video
1. `set dscale jinc` or bicubic/....etc and make sure mpv was doing dscaling.
2. `set dscale ""`

### Expected behavior

No crash

### Actual behavior

mpv exited at once

### Log file

[test3.log](https://github.com/mpv-player/mpv/files/12176873/test3.log)

### Sample files

N/a

### PR DESCRIPTION
**Pull request by Dudemanguy**
The first commit fixes #12031. The second commit implements the behavior suggested [here](https://github.com/mpv-player/mpv/issues/12031#issuecomment-1657004574). That is, cscale will use the value of scale if it is unset.

### CODE REVIEW

File: video/out/gpu/video.c [hunk 1]
```diff
@@ -1727,6 +1727,12 @@ static void reinit_scaler(struct gl_video *p, struct scaler *scaler,
 
     uninit_scaler(p, scaler);
 
+    if (conf && scaler->index == SCALER_DSCALE && (!conf->kernel.name || 
+        !strcmp(conf->kernel.name, "")))
```
Comment (sfan5) [inline video/out/gpu/video.c]: shorter `!conf->kernel.name[0]`

File: video/out/gpu/video.c [hunk 2]
```diff
@@ -1727,6 +1727,12 @@ static void reinit_scaler(struct gl_video *p, struct scaler *scaler,
...
+    {
+        conf = &p->opts.scaler[SCALER_SCALE];
+    }
```
Comment (sfan5) [inline video/out/gpu/video.c]: also shouldn't this go to the very top of the function?

File: video/out/gpu/video.c [hunk 3]
```diff
@@ -2305,7 +2303,7 @@ static void pass_read_video(struct gl_video *p)
         struct scaler *scaler = &p->scaler[scaler_id];
 
         // bilinear scaling is a free no-op thanks to GPU sampling
-        if (strcmp(conf->kernel.name, "bilinear") != 0) {
+        if (!conf->kernel.name || strcmp(conf->kernel.name, "bilinear") != 0) {
```
Comment (sfan5) [inline video/out/gpu/video.c:2306]: if `!name` doesn't that mean whatever is in `conf` is invalid?

File: video/out/gpu/video.c (hunk 2 above)
Comment (Dudemanguy) [reply video/out/gpu/video.c]: `scaler_conf_eq` will return false in the case of an empty name, so I don't think it needs to be at the very top.

File: video/out/gpu/video.c (hunk 3 above)
Comment (Dudemanguy) [reply video/out/gpu/video.c:2306]: Yes, but `reinit_scaler` in the `pass_sample` call will reinitialized all the scaler and conf stuff.

Comment (sfan5) [reply video/out/gpu/video.c]: Seems a bit messy to have different code work in different ways because it either handles the fallback or doesn't, but it looks like haasn wants to rewrite this code anyway.

**Review by sfan5 — APPROVED** [review]
