### PR TITLE
demux/demux_lavf: avoid leaking AVFormatContext during demux_open_lavf

### LINKED ISSUE #11793: demux: lavf: memory leak in demux_open_lavf
### TL;DR
we perfom a fuzz on mpv and find this bug.
avfc alloc at 
https://github.com/mpv-player/mpv/blob/f1c9daa169d2b51a759997ee05af6b036324b4c5/demux/demux_lavf.c#L991
and pass as a ptr to `priv` at 
https://github.com/mpv-player/mpv/blob/f1c9daa169d2b51a759997ee05af6b036324b4c5/demux/demux_lavf.c#L1107

if prog fails between these code, `avfc` will leak.
Also, I haven't check if `avfc` can safely free after L1107.

### Important Information
```
mpv 1c9daa-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Thu Jun 15 08:49:22 2023
FFmpeg version: 4.4.2-0ubuntu0.22.04.1
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
```

### Log file
```
=================================================================
==83115==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1504 byte(s) in 1 object(s) allocated from:
    #0 0x5623958a42d7 in posix_memalign (/root/mpv/build/mpv+0x1d42d7) (BuildId: 8783f8dbcdeb230f5b3395c900aeb5a2c07e1ed9)
    #1 0x7fa4b81139e4 in av_malloc (/lib/x86_64-linux-gnu/libavutil.so.56+0x419e4) (BuildId: abc6b699a880017e212d717fb86a1c6ea0e022e8)
    #2 0x56239598e1bd in open_given_type /root/mpv/build/../demux/demux.c:3337:15
    #3 0x56239596daeb in demux_open /root/mpv/build/../demux/demux.c:3449:27
    #4 0x56239596daeb in demux_open_url /root/mpv/build/../demux/demux.c:3510:25
    #5 0x562395b62b70 in open_demux_thread /root/mpv/build/../player/loadfile.c:1054:9
    #6 0x7fa4b7d59b42  (/lib/x86_64-linux-gnu/libc.so.6+0x94b42) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

Indirect leak of 176 byte(s) in 2 object(s) allocated from:
    #0 0x5623958a42d7 in posix_memalign (/root/mpv/build/mpv+0x1d42d7) (BuildId: 8783f8dbcdeb230f5b3395c900aeb5a2c07e1ed9)
    #1 0x7fa4b81139e4 in av_malloc (/lib/x86_64-linux-gnu/libavutil.so.56+0x419e4) (BuildId: abc6b699a880017e212d717fb86a1c6ea0e022e8)

Indirect leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x5623958a42d7 in posix_memalign (/root/mpv/build/mpv+0x1d42d7) (BuildId: 8783f8dbcdeb230f5b3395c900aeb5a2c07e1ed9)
    #1 0x7fa4b81139e4 in av_malloc (/lib/x86_64-linux-gnu/libavutil.so.56+0x419e4) (BuildId: abc6b699a880017e212d717fb86a1c6ea0e022e8)
    #2 0x56239598e1bd in open_given_type /root/mpv/build/../demux/demux.c:3337:15
    #3 0x56239596daeb in demux_open /root/mpv/build/../demux/demux.c:3449:27
    #4 0x56239596daeb in demux_open_url /root/mpv/build/../demux/demux.c:3510:25
    #5 0x562395b62b70 in open_demux_thread /root/mpv/build/../player/loadfile.c:1054:9
    #6 0x7fa4b7d59b42  (/lib/x86_64-linux-gnu/libc.so.6+0x94b42) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

Indirect leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x5623958a3b86 in __interceptor_realloc (/root/mpv/build/mpv+0x1d3b86) (BuildId: 8783f8dbcdeb230f5b3395c900aeb5a2c07e1ed9)
    #1 0x7fa4b8113f38 in av_strdup (/lib/x86_64-linux-gnu/libavutil.so.56+0x41f38) (BuildId: abc6b699a880017e212d717fb86a1c6ea0e022e8)

SUMMARY: AddressSanitizer: 1835 byte(s) leaked in 5 allocation(s).
```

### PR DESCRIPTION
**Pull request by Traneptora**
If demux_open_lavf fails between calling avformat_alloc_context() and assigning the context to priv->avfc, it will never be properly freed.

Fixes #11793.

### CODE REVIEW

File: demux/demux_lavf.c [hunk 1]
```diff
@@ -969,10 +969,16 @@ static void nested_io_close(struct AVFormatContext *s, AVIOContext *pb)
...
-    AVFormatContext *avfc;
+    AVFormatContext *avfc = NULL;
     AVDictionaryEntry *t = NULL;
     float analyze_duration = 0;
-    lavf_priv_t *priv = talloc_zero(NULL, lavf_priv_t);
+    lavf_priv_t *priv = NULL;
+    AVDictionary *dopts = NULL;
+
+    priv = talloc_zero(NULL, lavf_priv_t);
+    if (!priv)
```
Comment (sfan5) [inline demux/demux_lavf.c:979]: talloc_zero never fails

File: demux/demux_lavf.c [hunk 2]
```diff
@@ -1196,6 +1199,12 @@ static int demux_open_lavf(demuxer_t *demuxer, enum demux_check check)
     }
 
     return 0;
+
+fail:
+    if (priv && avfc && !priv->avfc)
```
Comment (sfan5) [inline demux/demux_lavf.c:1204]: and this can be just `!priv->avfc`

**Review by sfan5 — APPROVED** [review]
LGTM
