### PR TITLE
command: add playlist-next-playlist and playlist-prev-playlist

### LINKED ISSUE #12495: Support next-archive or next-nonrecursive playlist controls (and/or next-directory)
After running `mpv gallery1.zip gallery2.zip`  
no key I can press will seek to the first file in `gallery2.zip`, skipping the rest of `gallery1.zip`

----

It's fairly common to have some video files and some image sets, with each image set in its own .zip or directory.  
`mpv` is almost the perfect tool to play a collection of such files, like `mpv foo*`.  (libarchive is inefficient especially when first opening an archive, but with a fast enough computer and non-huge archives, it's still faster than running `gwenview` or other full GUIs, and I often want MPV's video-playing features.)

But if you get to a big image gallery / photoset you *don't* want to see all of right now, it's painful to get past it in the playlist.

e.g. if I want to look at recently-downloaded (and still-downloading) videos and image-sets in a directory, I use this bash function `mpvcrt() { local args=($MPV); local IFS=$'\n'; mpv "${args[@]}" $(ls -Hct "$@"); }` to play files and directories in order of newest ctime, for filenames that don't contain spaces.  (Or something else if I pass `ls` options mixed with paths, like `-d` if I specify a directory.)

One current workaround is to alt-tab back to the shell so you can at least use keyboard-repeat, since MPV over the past few years has changed so right-arrow doesn't go to the next JPEG, `]` speed multiplier doesn't scale the `--image-display-duration=`, and keyboard-repeat doesn't happen for enter/return (in MPV's window; it can't do anything about the terminal emulator), or for multimedia keyboard keys like XF86AudioNext.  (This is arguably a good choice by default, although some way to get auto-repeat for playlist-next might make sense.)

### Expected behavior of the wanted feature

On pressing a key bound to `playlist-next-archive`, scan forward in the playlist until reaching an entry whose top-level `archive://` is different from the current one.  (Or isn't an archive at all.)  If `current` isn't an `archive://` entry, precisely the same as `playlist-next`, whether or not the next entry is an archive or not.

On pressing `playlist-next-directory`, search for an entry whose dirname (stuff before the final `/`) is different from the current entry.  Maybe unless this entry is already top level like `foo.mp4`?  e.g. from `foo/set42.jpg`, skip until getting to `bar/set1.jpg`.  But there are probably lots of cases where this algorithm doesn't give the behaviour we actually want.

### Alternative behavior of the wanted feature (I like this idea better)

**A `playlist-next-nonrecursive` input command could cover both archives and directories the way I'm looking for**, seeking to the next playlist entry that was given explicitly rather than via recursive expansion of a `.zip` into multiple `archive://` entries, or a directory into its contents.  (Or to an entry that came from expansion of a *different* top-level entry, if you have two back-to-back archives.)

Ideally with an exception for the case where the initial playlist had one entry, like `mpv /foo/bar` or `mpv foo.playlist`.  Otherwise you'd have to write `mpv /foo/bar/*` if you want to be able to `playlist-next-nonrecursive` across archives and subdirectories 

That would also handle the case of a `.zip` or `.rar` containing `.zip` files: if you specified just that on the command line, the next/prev `nonrecursive` commands would skip between the zip files it contained, since the top-level playlist was a single entry.  (Making next-nonrecursive equivalent to quit is less useful than allowing seeking by groups within the expansion results.)

This is hopefully simple (a playlist entry can be marked as being generated by recursive expansion vs. supplied explicitly), and only needs 2 new commands. It wouldn't be turning mpv into a general file-browser or anything.  (GUIs like gwenview exist for that, or for only still images not in archives, geeqie is nice and lightweight).  And it wouldn't need any complicated heuristics for directories vs. top-level to get the behaviour I want, I think

If people want to skip between directories or archives 2 levels deep, they could do something like `mpv /foo/*/*.zip` so the things they want to skip between are top-level playlist entries.

So for example, if the initial playlist (from the command line) contains

```
foo.mp4
foo.zip
bar.mp4
bar.zip
some_dir/
some.zip
xyz.mp4
```

(The top-level entries can of course be in different directories; we don't care about paths, just which original entries they were expanded from, so I kept it flat.)

`playlist-next-nonrecursive` from `archive://foo.zip/42.jpg` would get to `bar.mp4`.  And `playlist-prev-nonrecursive` would go to `foo.mp4`.  `playlist-next-nonrecursive` from `foo.mp4` would go to `archive://foo.zip/01.jpg`, same as a normal `playlist-next` because `foo.mp4` wasn't the result of recursive expansion.

The same for `some_dir/42.jpg` going forward or back.  Going forward into `archive://some.zip/01.jpg` or whatever it contains, we're going from one recursively-expanded entry to another, but they came from different top-level entries so we do stop there.  So I guess we'd need a unique ID number to record the entry number they were expanded from, instead of just a boolean recursive-or-not.

Perhaps auto-number the initial playlist entries, and when recursively expanding give each entry the same ID as its parent.

Or generate a new ID for each level of recursive expansion, so `foo.zip/set1/*.jpg` and `foo.zip/set2/*.jpg` end up as separate entries.  That would be different behaviour that some other users might want; it could be worth having an option for that.  It still just needs one unique ID per entry, like a `uint32_t` or u64 counter, not recording the tree structure.

(Although if that's easy, maybe a `playlist-up-and-next` command could work, with up from the first entry of an expanded group counting as the parent from whence you can go farther up?  IDK if that makes any sense in UI design / usability even if the playlist is a tree data structure.)

### PR DESCRIPTION
**Pull request by guidocella**
playlist-prev-playlist goes to the beginning of the previous playlist because this seems more useful and symmetrical to playlist-next-playlist. It does not go to the beginning when the current playlist-path starts with the previous playlist-path, e.g. with mpv --loop-playlist foo/, which expands to foo/{1..9}.zip, the current playlist path foo/1.zip beings with the playlist-path foo/ of {2..9}.zip and thus playlist-prev-playlist goes to 9.zip rather than to 2.zip.

Closes #12495.

### CODE REVIEW

File: player/command.c [hunk 1]
```diff
@@ -5321,6 +5321,45 @@ static void cmd_playlist_next_prev(void *p)
...
+        entry = direction > 0 ? playlist_get_first(mpctx->playlist)
+                              : playlist_get_last(mpctx->playlist);
+
+        if (entry && entry->playlist_path &&
+            strcmp(entry->playlist_path,
+                   mpctx->playlist->current->playlist_path) == 0)
+            entry = NULL;
+
+        if (direction > 0 && entry && mpctx->opts->loop_times > 1) {
+            mpctx->opts->loop_times--;
```
Comment (Dudemanguy) [inline player/command.c:5343]: Don't really like how the option value changes behind the user's back, but I realize that we already do this for `mp_next_file`. Maybe this can be fixed later.

File: common/playlist.h [hunk 2]
```diff
@@ -97,6 +97,10 @@ struct playlist_entry *playlist_get_last(struct playlist *pl);
 struct playlist_entry *playlist_get_next(struct playlist *pl, int direction);
 struct playlist_entry *playlist_entry_get_rel(struct playlist_entry *e,
                                               int direction);
+struct playlist_entry *playlist_get_first_in_next_playlist(struct playlist *pl,
+                                                           int direction);
+struct playlist_entry *playlist_get_first_in_same_playlist(
+    struct playlist_entry *entry, char *current_playlist_path);
```
Comment (Dudemanguy) [inline common/playlist.h:103]: Accidentally indented here.

File: common/playlist.c [hunk 3]
```diff
@@ -214,6 +214,55 @@ struct playlist_entry *playlist_entry_get_rel(struct playlist_entry *e,
...
+
+    char* playlist_path = talloc_strdup(tmp, entry->playlist_path);
+    mp_path_strip_trailing_separator(playlist_path);
+    if (bstr_startswith(bstr0(current_playlist_path),
+                        bstr0(talloc_strdup_append(playlist_path, "/")))
+#if HAVE_DOS_PATHS
+        ||
+        bstr_startswith(bstr0(current_playlist_path),
+                        bstr0(talloc_strdup_append(playlist_path, "\\")))
+#endif
```
Comment (Dudemanguy) [inline common/playlist.c:249]: Why strip the separator if you're going to compare them again with the separator? Couldn't you just do that after this check or am I missing something?

File: common/playlist.c [hunk 4]
```diff
@@ -214,6 +214,55 @@ struct playlist_entry *playlist_entry_get_rel(struct playlist_entry *e,
     return playlist_entry_from_index(e->pl, e->pl_index + direction);
 }
 
+struct playlist_entry *playlist_get_first_in_next_playlist(struct playlist *pl,
+                                                           int direction) {
```
Comment (Dudemanguy) [inline common/playlist.c:218]:
```suggestion
                                                           int direction)
{
```

File: common/playlist.c [hunk 5]
```diff
@@ -214,6 +214,55 @@ struct playlist_entry *playlist_entry_get_rel(struct playlist_entry *e,
...
+
+    if (direction < 0)
+        entry = playlist_get_first_in_same_playlist(entry,
+                                                    pl->current->playlist_path);
+
+    return entry;
+}
+
+struct playlist_entry *playlist_get_first_in_same_playlist(
+    struct playlist_entry *entry, char *current_playlist_path) {
```
Comment (Dudemanguy) [inline common/playlist.c:235]:
```suggestion
struct playlist_entry *playlist_get_first_in_same_playlist(struct playlist_entry *entry,
                                                           char *current_playlist_path)
{
```

File: player/command.c (hunk 1 above)
Comment (guidocella) [reply player/command.c:5343]: I thought about this and it would also fix --loop-file=N not being kept when going to the next file, but to fix it we would have to introduce a whopping 3 properties corresponding to `loop-file`, `loop-playlist`, and `ab-loop-count` (e.g. `remaining-file-loops`, `remaining-playlist-loops`, `remaining-ab-loops`) which is pretty bloated.

File: common/playlist.h (hunk 2 above)
Comment (guidocella) [reply common/playlist.h:103]: It's not accidental, `struct playlist_entry *playlist_get_first_in_same_playlist(struct playlist_entry *entry,` is 89 characters. Do you have a better idea to indent it?

File: common/playlist.c (hunk 3 above)
Comment (guidocella) [reply common/playlist.c:249]: We don't want to trigger to condition on e.g. `foobar/` starting with `foo/`.

File: common/playlist.c (hunk 4 above)
Comment (guidocella) [reply common/playlist.c]: Whoops, fixed.

File: common/playlist.c (hunk 5 above)
Comment (guidocella) [reply common/playlist.c]: Fixed.

File: common/playlist.c (hunk 3 above)
Comment (guidocella) [reply common/playlist.c:268]: Added a comment explaining the issue in detail.

File: common/playlist.h (hunk 2 above)
Comment (Dudemanguy) [reply common/playlist.h:103]: Oh gee, I didn't even see that. I think the normal convention for something like this is more like:
```
struct playlist_entry *playlist_get_first_in_same_playlist(struct playlist_entry *entry,
                                                                                        char *current_playlist_path);
```

File: common/playlist.c (hunk 3 above)
Comment (Dudemanguy) [reply common/playlist.c:268]: Ah okay I was wondering why you couldn't just strip all separators but that makes sense now. I might be nicer to add a `mp_path_add_trailing_separator` in path.c so we can keep the DOS_PATHS thing out of here.

Comment (Dudemanguy) [reply common/playlist.c:268]: Windows is weird and evidently you have to check both so nevermind.

File: player/command.c (hunk 1 above)
Comment (Dudemanguy) [reply player/command.c:5343]: Well they are all different kinds of loops so it might be needed to have such a separation. I think wm4 did that for everything else that had weird overlaps like `window-scale` and `current-window-scale` and also used to silently change options, but we can discuss that in some other PR I suppose.

**Comment by guidocella** [comment]
This was fixed months ago.

**Comment by guidocella** [comment]
I can't reproduce that.

**Comment by guidocella** [comment]
It still doesn't crash for me and I don't understand why you should skip that check with URLs.

**Comment by Dudemanguy** [comment]
I also cannot reproduce. Dunno, check if there's something weird in your config causing this although I don't know what that would be.
