### PR TITLE
vo_gpu_next: avoid 0x0 resizes

### LINKED ISSUE #10083: GPU-NEXT error message.
### Important Information

Provide following Information:
- mpv version: mpv-build-git
- Linux Distribution and Version: Arch
- Source of the mpv binary: AUR
- If known which version of mpv introduced the problem: git
- Window Manager and version: Mutter42.0
- GPU driver and version: Mesa Gallium driver 22.0.1 for AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.44, 5.17.1-zen1-1-zen)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

```mpv --no-config --vo=gpu-next <video>```

### Expected behavior

No error message.

### Actual behavior

```[vo/gpu-next] Tried calling `pl_swapchain_resize` with unknown size! This is forbidden for OpenGL. The first call to `pl_swapchain_resize` must include the width and height of the swapchain, because there's no way to figure this out from within the API.```

### Log file

[gpu-next.txt](https://github.com/mpv-player/mpv/files/8465874/gpu-next.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

### PR DESCRIPTION
**Pull request by Dudemanguy**
It is possible for vo_gpu_next to attempt a resize before the windowing
backend is fully initialized. In practice, this can happen on wayland
which means libplacebo attempts a 0x0 resize. Depending on the API, a
0x0 resize may be allowed (vulkan or d3d11), but libplacebo just returns
a 0 in this case which mpv doesn't do anything with anyway. In the case
of opengl, this usage is explictly forbidden and will result in a
warning which may confuse users. Solve this by just not trying a resize
if dwidth and dheight in the vo are not available. Fixes https://github.com/mpv-player/mpv/issues/10083.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
P.S. vo_gpu technically does this too, but it doesn't print out an error message or anything so I figured it wasn't worth bothering with.

File: video/out/gpu_next/context.c [hunk 1]
```diff
@@ -187,6 +187,11 @@ bool gpu_ctx_resize(struct gpu_ctx *ctx, int w, int h)
         // vulkan RA handles this by itself
         return true;
 #endif
+#if HAVE_GL
+    if (ra_is_gl(ctx->ra_ctx->ra) && (w == 0 || h == 0))
```
Comment (sfan5) [inline video/out/gpu_next/context.c:191]: why allow it for d3d11? I assume libplacebo prints this error message independent of swapchain backend/type.

Comment (Dudemanguy) [reply video/out/gpu_next/context.c:191]: It's allowed for vulkan. I have no idea about d3d11 but the error returned makes it sound like it's opengl-specific.

**Comment by cyanreg** [comment]
> In practice, this always happens on wayland

Correction - this only happens on wlroots-based compositors. It's a known bug, and no one has been interested in fixing it. It's very annoying, because it requires you to pick an arbitrary, often hardcoded size to initialize, render a frame, and only then the compositor will tell you what your size should be, making this a roundtrip that requires 2 swapchain recreations, which can be costly, and making users often see a flicker when first opening a client.

As it's a compositor-specific workaround, I'd prefer to keep the warning and make users complain so this finally gets fixed, but I don't mind.
@emersion

**Comment by Dudemanguy** [comment]
It's actually the opposite. I don't get this in wlroots, but I can trivially reproduce it in weston and gnome. I *think* the very initial `resize` call in vo_gpu_next can happen before the wayland stuff is fully initialized which just depends on the compositor.

**Comment by emersion** [comment]
On Wayland, 0x0 means "choose your surface size, the compositor has no preferred size". See the docs for `xdg_toplevel.configure`.

File: video/out/gpu_next/context.c (hunk 1 above)
Comment (sfan5) [reply video/out/gpu_next/context.c:191]: Right, appears to be allowed for d3d11 too.
But there's no point in passing through zero values to `pl_swapchain_resize` in any case, libplacebo will query the size but it's not like mpv uses the returned values.

**Comment by Dudemanguy** [comment]
Changed it so `gpu_ctx_resize` is not called if `vo->dwidth` or `vo->dheight` are zero.

**Review by sfan5 — APPROVED** [review]

**Review by philipl — APPROVED** [review]
