### PR TITLE
af_scaletempo2: prioritize louder channels for similarity measure

### LINKED ISSUE #8705: Scaletempo2, the new default for adjusting audio playback speed, sounds noticeably worse in some situations
### Important Information

Provide following Information:
- mpv version: freshly compiled latest from master (mpv 0.33.0-109-gd0c530919d)
- macOS

This is relevant because `scaletempo2` was changed to the default from `scaletempo` in #8376

### Reproduction steps
Try listening to some 5.1 audio at 0.95x speed using the now default scaletempo2 filter.  
`$ mpv --speed=0.95 --af=scaletempo2 some_audio`
Listen for the poor quality in some situations.

Now add the old default, `scaletempo`, to the af filter chain and listen for the better quality.
`$ mpv --speed=0.95 --af=scaletempo some_audio`

Also listen to the recorded sample files below.  You can use the [original_source.mkv ](https://0x0.st/-cDF.mkv) file included to reproduce the samples I recorded.

### Expected behavior
The default should not make things worse.

### Actual behavior
scaletempo2 is worse for minor speed changes in the 0.85x - 1.2x range.  It's MUCH better for the big speed changes though, and I really appreciate it for that.

While I do appreciate scaletempo2 for big adjustments, I usually only make minor speed changes so for me so it's not a good default.  I suspect that playback speed adjustments in the 0.9-1.2x range are much more common amongst users.  [This comment](https://github.com/mpv-player/mpv/issues/4418#issuecomment-812581417) is where another users seems to have been caught up in this default change.

### Sample files
- [scaletempo2_0.95x_speed.wav](https://0x0.st/-cDD.wav)    (Bad)
- [scaletempo_0.95x_speed.wav](https://0x0.st/-cDG.wav)     (Better)
- [1x_speed.wav](https://0x0.st/-cDn.wav)  (1x speed, recorded in the same way)
- [original_source_audio.mkv](https://0x0.st/-cDF.mkv)

### PR DESCRIPTION
**Pull request by ferreum**
This is an attempt to fix #8705 and is the result to my ideas [commented](https://github.com/mpv-player/mpv/pull/13737#issuecommnt-2013445939) on #13737.

The idea here is to increase the weight of louder channels. Some details are in the commit message. Should have very little effect on stereo audio and none on mono.

I tested it with the [sample](https://github.com/mpv-player/mpv/issues/8705#issuecomment-2000666720) from the issue, with the [test file](https://github.com/mpv-player/mpv/pull/13737#issuecomment-2014064370) in the discussion, and in random other videos I've watched and my impression is pretty good so far.

### CODE REVIEW

File: audio/filter/af_scaletempo2_internals.c [hunk 1]
```diff
@@ -99,11 +99,13 @@ static float multi_channel_similarity_measure(
 {
     const float epsilon = 1e-12f;
     float similarity_measure = 0.0f;
+    float total_energy = epsilon;
```
Comment (christoph-heinrich) [inline audio/filter/af_scaletempo2_internals.c:102]: Removing that shouldn't make any difference to the result.

The target block doesn't change with the offset, therefore this sum will always be the same for each iteration of the optimal index search, so all calculated similarities are changed by the same factor, thus not changing the location of the maximum.

**Review by christoph-heinrich — CHANGES_REQUESTED** [review]
I gave it a quick test and it sounds good so far :+1:

I'll be using it in my mpv build.

File: audio/filter/af_scaletempo2_internals.c (hunk 1 above)
Comment (ferreum) [reply audio/filter/af_scaletempo2_internals.c:102]: Hmm, that's true. I was thinking of the sliding window here. On the other hand, this relies on the fact that target block is always passed first, and this method currently doesn't say which one the target block is (though I did phrase my commit message that way). I'll remove it.

Comment (ferreum) [reply audio/filter/af_scaletempo2_internals.c]: how about changing the parameters to make the intention apparent? I'm thinking of this
```
 static float multi_channel_similarity_measure(
-    const float* dot_prod_a_b,
-    const float* energy_a, const float* energy_b,
+    const float* dot_prod,
+    const float* energy_target, const float* energy_candidate,
     int channels)
 {
     const float epsilon = 1e-12f;
     float similarity_measure = 0.0f;
     for (int n = 0; n < channels; ++n) {
-        similarity_measure += dot_prod_a_b[n] * energy_a[n]
-            / sqrtf(energy_a[n] * energy_b[n] + epsilon);
+        similarity_measure += dot_prod[n] * energy_target[n]
+            / sqrtf(energy_target[n] * energy_candidate[n] + epsilon);
     }
     return similarity_measure;
 }
```

Comment (christoph-heinrich) [reply audio/filter/af_scaletempo2_internals.c]: Now that the target and candidate aren't treated the same anymore in that function, it does make sense to give them more descriptive names. I'd be fine with those.

**Review by christoph-heinrich — APPROVED** [review]
I don't understand why `dot_prod(target, candidate) * sqrt(energy_target) / sqrt(energy_candidate)` works, but it does and that's all that really matters.

**Comment by christoph-heinrich** [comment]
> But this PR still doesn't eliminate some problems which scaletempo doesn't have. Here is a sample I have played at 1.1x speed, where scaletempo2 has some kind of pitch shifting artifact which scaletempo doesn't have:

scaletempo uses very different default parameters to scaletempo2. If you use `af=scaletempo2=search-interval=14:window-size=60` (which is kind of what scaletempo uses, except scaletempo2 has no way of replicating overlap=0.2) then there is no noticeable pitch shift anymore.

Whichever parameters you choose, it will always be a compromise in some regard.
Maybe dynamic parameters could work well for "all" situations, where `search-interval` and `window-size` change automatically based on playback speed.

**Comment by christoph-heinrich** [comment]
> My understanding is that the original similarity measure being ununited means that the input signals are essentially normalized, so quiet channels get essentially boosted even though they shouldn't.

I should have been more specific. I do understand why this change in isolation is an improvement over the status quo, but I don't understand why multiplying the dot product with `sqrt(energy_target) / sqrt(energy_candidate)` makes it better.
How come that if the target is louder then the candidate the similarity gets raised over when they are the same loudness,
and then if the candidate is louder then the target it gets decreased.
How does that make the result better? Evidently it does, but it makes no sense to me.

**Review by Dudemanguy — APPROVED** [review]
I don't use this extensively, but if everyone agrees this has better results, I don't see why not.
