### PR TITLE
external_files: detect locales with a region like en-US

### LINKED ISSUE #12372: Poor support for locale specific subtitles
### Important Information

Provide following Information:
- mpv version: nighly mpv v0.36.0-240-g67368ac5, built on Sep  3 2023 00:14:58
- Platform and Version: Win 10

### Reproduction steps

- Start off with subtitles that match a filename, e.g. `123.mp4` and `123.en.srt`. mpv loads these subtitles by default and recognises the language of the subtitles correctly (`en`). 
- Rename the subtitles to `123.en-US.srt`. Open `123.mp4` in mpv 

### Expected behavior
Treat locale specific subtitles the same way regular subtitles are treated (e.g. as if they are simply `.en.vtt` and the `-US` part didn't exist).
- Recognise said `.en-XX.vtt` subtitles without the `sub-auto=fuzzy` flag set
- Recognise language of the subtitles as `en` despite the locale

### Actual behavior
mpv doesn't open locale specific subtitles by default (`sub-auto=fuzzy` is required to do so). 
- Additionally, the language of said subs is no longer recognised as `en` but `unknown` instead. This in turn causes problems with other subtitle params (e.g. `slang=`).

### Notes
  - These steps can be reproduced with `.vtt` (and probably other) file extensions
  - This can be reproduced with any subtitles that are of format `.xx-yy.srt` (or any other file extension beside `.srt`), where `xx` is the 2 character language code and `yy` is the 2 character locale code. As of now, it seems that mpv only cleanly supports `xx.srt` files.
  - I don't think it's worth the effort to extract the locale (e.g. `US`) from the filename or anything like that. It would be simply sufficient to recognise that, e.g. `en-US` subtitles exist and are of English language
  - The reason I'm creating this issue is that sometimes subtitles are provided with locale similar to the above (rather that plain `.en.srt` ), so recognising them by default saves messing around and renaming them.

### LINKED ISSUE #13251: mpv wont load/pickup subtitles?
Provide following Information:
- mpv version
-mpv v0.37.0-112-g702b3eb956 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 18 2023 11:49:17
libplacebo version: v6.338.0-62-g52314e0e
FFmpeg version: n6.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100

- Linux Distribution and Version
devuan 5.0 64bit

mpv 
built from source

with options
echo --enable-libx264 >> ffmpeg_options
echo --enable-vaapi >> ffmpeg_options
echo -Dvapoursynth=enabled >> mpv_options
echo -Dlibmpv=true >> mpv_options
echo --enable-nvdec >> ffmpeg_options

### Reproduction steps

i have downloaded several videos via yt-dlp with corresponding subtitles /subtitles as separate .vtt files,

issues is mpv does not recognize the subtitles altough they are in the same folder and have the same filename like in

A Hindu Temple Hidden Under Islamic University of Indonesia？  Candi Kimpulan Temple – Part 1 [50jN3QMI5u0].mp4
A Hindu Temple Hidden Under Islamic University of Indonesia？  Candi Kimpulan Temple – Part 1 [50jN3QMI5u0].en-US.vtt

mpv does not play subtitles automatically and does not pick up subtitles when pressing ¨j"on keyboard.

### Expected behavior

mpv should recognize subtitles , as vlc does on the same computer with same files

### Actual behavior

mpv does not play subtitles, maybe the compile was made without subtitle support?

### Log file

https://pastebin.ubuntu.com/p/c7wcTWj6CK/

### Sample files

mpv-shot0001
Screenshot_2024-01-08_21-54-43

### PR DESCRIPTION
**Pull request by guidocella**
commit 1: external_files: rename variables in guess_lang_from_filename()

commit 2: external_files: detect locales with a region like en-US

This loads subtitle files like foo.en-US.srt with --sub-auto=exact.

To preserve the case of these locales and not convert them to e.g. en-us, stop lower casing filenames, and instead use case insensitive functions to check if the media filename is contained in the external filenames. Extensions, whitelisted cover art filenames and idx files were already being compared case insensitively.

Fixes #12372, fixes #13251.

### CODE REVIEW

**Comment by dyphire** [comment]
So what about `sgn-FSL` and `en-simple` as mentioned in https://github.com/mpv-player/mpv/issues/8144 ? There are also Chinese labels, such as `zh-Hans` and `zh-Hant`.

**Comment by guidocella** [comment]
I guess we should just allow any length?

**Comment by dyphire** [comment]
> I guess we should just allow any length?

According to the BCP 47 language tags standard, there will only be 2 or 3 characters before the first `-` character, which can be used to determine validity. The problem is that it is uncertain how many characters will follow the first `-` character. Perhaps we can choose to only support commonly seen language tags, which are within the range of 3 to 6 characters.

File: player/external_files.c [hunk 1]
```diff
@@ -110,36 +110,52 @@ static int compare_sub_priority(const void *a, const void *b)
     return strcoll(s1->fname, s2->fname);
 }
 
-static struct bstr guess_lang_from_filename(struct bstr name, int *fn_start)
+static struct bstr guess_lang_from_filename(struct bstr name, int *lang_start)
```
Comment (kasper93) [inline player/external_files.c:113]: I would prefer if we moved this function to language.c and added a test for it. To document it's behavior and avoid breakage in future.

File: player/external_files.c [hunk 2]
```diff
@@ -110,36 +110,52 @@ static int compare_sub_priority(const void *a, const void *b)
...
     while (i >= 0 && mp_isalpha(name.start[i])) {
-        n++;
-        if (n > 3)
-            return (struct bstr){NULL, 0};
+        lang_length++;
         i--;
     }
 
-    if (n < 2 || i == 0 || name.start[i] != thing)
+    if (lang_length < 2 || lang_length > 6 || (name.start[i] != '-' && lang_length > 3))
```
Comment (kasper93) [inline player/external_files.c:136]: `gsw-u-sd-chzh` is longer than 6 chars

File: player/external_files.c [hunk 3]
```diff
@@ -110,36 +110,52 @@ static int compare_sub_priority(const void *a, const void *b)
...
+        return (struct bstr){NULL, 0};
```
Comment (kasper93) [inline player/external_files.c:137]:
```suggestion
        return (struct bstr){0};
```

File: player/external_files.c [hunk 4]
```diff
@@ -110,36 +110,52 @@ static int compare_sub_priority(const void *a, const void *b)
...
+
+    // Detect locales with a region, like en-US.
+    if (name.start[i] == '-') {
```
Comment (kasper93) [inline player/external_files.c:140]: BCP 47 allows multiple subtags. Like `gsw-u-sd-chzh` this should be supported. As I see currently only one would be added.

**Review by kasper93 — CHANGES_REQUESTED** [review]

File: player/external_files.c (hunk 2 above)
Comment (dyphire) [reply player/external_files.c:136]: Here's a more extreme example: `he-IL-u-ca-hebrew-tz-jeruslm`, The only way to add full support for the BCP 47 language tags standard to external files seems to be to remove the limit on the detection length.

Comment (dyphire) [reply player/external_files.c:136]: One possible detection method: invalid when there are other symbols other than `-`. According to the BCP 47 language tags standard, there will be a maximum of eight characters after each `-` symbol.

File: player/external_files.c (hunk 1 above)
Comment (guidocella) [reply player/external_files.c:113]: That's best done after https://github.com/mpv-player/mpv/pull/13917 to avoid conflicts though I don't think it's bad to have it here since it's specific to external files rather than comparing languages, and there are already other 2 public functions.

File: player/external_files.c (hunk 2 above)
Comment (guidocella) [reply player/external_files.c]: I just removed the limit.

File: player/external_files.c (hunk 3 above)
Comment (guidocella) [reply player/external_files.c]: Done.

**Comment by dyphire** [comment]
The current detection is too lenient, it defaults to loading subtitles that do not comply with the specifications, such as test-en and en-simpletest-simpletest.

As I mentioned earlier: according to the BCP 47 language tags standard, there will only be 2 or 3 characters before the first `-` character.  And this should match the valid language tags in language.c.

And according to the BCP 47 language tags standard, there will be a maximum of eight characters after each hyphens (-). Therefore, we still need to check the eight character limit after each hyphens (-).

Refer to relevant  relevant  BCP 47 language tags normative content:
https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags

File: player/external_files.c (hunk 1 above)
Comment (kasper93) [reply player/external_files.c:113]: merged now

Comment (guidocella) [reply player/external_files.c]: Done.

File: test/language.c [hunk 5]
```diff
@@ -54,4 +54,25 @@ int main(void)
...
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.en-US.srt"), NULL)), "en-US");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.en-simple.srt"), NULL)), "en-simple");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.sgn-FSL.srt"), NULL)), "sgn-FSL");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.gsw-u-sd-chzh.srt"), NULL)), "gsw-u-sd-chzh");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.a.srt"), NULL)), "");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.aaaa.srt"), NULL)), "");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.00.srt"), NULL)), "");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.en-.srt"), NULL)), "");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.en-aaaaaaaaa.srt"), NULL)), "");
+    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.en-0.srt"), NULL)), "");
```
Comment (kasper93) [inline test/language.c:75]: I would add also
```
    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.e.srt"), NULL)), "");
    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.en.srt"), NULL)), "en");
    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.eng.srt"), NULL)), "eng");
    assert_string_equal(bstrto0(ta_ctx, mp_guess_lang_from_filename(bstr0("foo.engg.srt"), NULL)), "");
```

File: misc/language.c [hunk 6]
```diff
@@ -21,7 +21,7 @@
 #include <stdint.h>
 
 #include "common/common.h"
-#include "misc/bstr.h"
+#include "misc/ctype.h"
```
Comment (kasper93) [inline misc/language.c:24]: why remove bstr.h?

File: misc/language.c [hunk 7]
```diff
@@ -296,3 +296,56 @@ int mp_match_lang(char **langs, const char *lang)
     talloc_free(ta_ctx);
     return best_score;
 }
+
+bstr mp_guess_lang_from_filename(bstr name, int *lang_start)
+{
+    name = bstr_strip(bstr_strip_ext(name));
+
+    if (name.len < 2)
+        return (struct bstr){0};
```
Comment (kasper93) [inline misc/language.c:305]:
```suggestion
        return (bstr){0};
```

File: misc/language.c [hunk 8]
```diff
@@ -296,3 +296,56 @@ int mp_match_lang(char **langs, const char *lang)
...
+        while (i >= 0 && mp_isalpha(name.start[i])) {
+            lang_length++;
+            i--;
+        }
+
+        // According to
+        // https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags
+        // subtags after the first are composed of 1 to 8 letters.
+        if (lang_length < suffixes_length + 1 || lang_length > suffixes_length + 8)
+            return (struct bstr){0};
```
Comment (kasper93) [inline misc/language.c:331]:
```suggestion
            return (bstr){0};
```

File: misc/language.c [hunk 9]
```diff
@@ -296,3 +296,56 @@ int mp_match_lang(char **langs, const char *lang)
...
+
+    // The primary subtag can have 2 or 3 letters.
+    if (lang_length < suffixes_length + 2 || lang_length > suffixes_length + 3 ||
+        i == 0 || name.start[i] != delimiter)
+        return (struct bstr){0};
+
+    if (lang_start)
+        *lang_start = i;
+
+    return (struct bstr){name.start + i + 1, lang_length};
```
Comment (kasper93) [inline misc/language.c:350]:
```suggestion
    return (bstr){name.start + i + 1, lang_length};
```

File: test/language.c (hunk 5 above)
Comment (guidocella) [reply test/language.c:77]: I reorganized the tests and fixed a buffer overflow with `foo.srt`.

File: misc/language.c (hunk 6 above)
Comment (guidocella) [reply misc/language.c:24]: It's moved to misc/language.h so the prototype can have `bstr` instead of `struct bstr`.

File: misc/language.c (hunk 7 above)
Comment (guidocella) [reply misc/language.c]: Done.

File: misc/language.c (hunk 8 above)
Comment (guidocella) [reply misc/language.c]: Done.

File: misc/language.c (hunk 9 above)
Comment (guidocella) [reply misc/language.c]: Done.

**Review by kasper93 — APPROVED** [review]
