### PR TITLE
various: expand paths for several file/directory related options

### LINKED ISSUE #15598: mpv cannot handle $HOME variable in mpv.conf file
### Reproduction Steps

Define a path in your mpv.conf file like this:

`external-file=~/.config/mpv/mpv.webp`

### Expected Behavior

Excepted behaviour would be that mpv will use the image...

### Actual Behavior

mpv says that the file does not exist:

`Can not open external file ~/.config/mpv/mpv.webp.`

But if you give the path in the form `external-file=/home/USERNAME/.config/mpv/mpv.webp`, mpv will find the image file.

### PR DESCRIPTION
**Pull request by Dudemanguy**
There's several path-related options that do not handle common shortcuts (like ~). Fix this by using mp_get_user_path where appropriate which expands the path so users get more intuitive behavior. Fixes #15598.

### CODE REVIEW

**Comment by kasper93** [comment]
Maybe interface changes entry to document that now path can be expanded for some options.

**Comment by Dudemanguy** [comment]
Sure it's technically an interface change. Added a brief entry.

File: common/encode_lavc.c [hunk 1]
```diff
@@ -135,7 +136,9 @@ struct encode_lavc_context *encode_lavc_init(struct mpv_global *global)
 
     p->muxer->oformat = ctx->oformat;
 
-    p->muxer->url = av_strdup(filename);
+    char *path = mp_get_user_path(ctx, global, filename);
```
Comment (kasper93) [inline common/encode_lavc.c:139]:
```suggestion
    char *path = mp_get_user_path(NULL, global, filename);
```

File: options/path.c [hunk 2]
```diff
@@ -115,7 +115,7 @@ void mp_init_paths(struct mpv_global *global, struct MPOpts *opts)
     if (!opts->load_config)
         force_configdir = "";
 
-    global->configdir = talloc_strdup(global, force_configdir);
+    global->configdir = mp_get_user_path(opts, global, force_configdir);
```
Comment (kasper93) [inline options/path.c:118]: Why change parent to opts?

File: player/loadfile.c [hunk 3]
```diff
@@ -852,8 +852,9 @@ int mp_add_external_file(struct MPContext *mpctx, char *filename,
 
     mp_core_unlock(mpctx);
 
+    char *path = mp_get_user_path(NULL, mpctx->global, filename);
     struct demuxer *demuxer =
-        demux_open_url(filename, &params, cancel, mpctx->global);
+        demux_open_url(path, &params, cancel, mpctx->global);
```
Comment (kasper93) [inline player/loadfile.c:857]: Why not `talloc_free(path);` immediately after this line?

Comment (Dudemanguy) [reply player/loadfile.c:857]: I wasn't sure if freeing `path` would cause some issue with any of the demuxer stuff trying to use the url, but it looks like stream does a copy so I guess it's probably OK?

Comment (kasper93) [reply player/loadfile.c:857]: Should be fine and if not it is on stream.c to fix.

File: common/playlist.c [hunk 4]
```diff
@@ -403,17 +403,16 @@ struct playlist *playlist_parse_file(const char *file, struct mp_cancel *cancel,
...
-    }
-
+    struct demuxer *d = demux_open_url(path, &p, cancel, global);
     struct playlist *ret = NULL;
+    if (!d)
+        goto done;
+
     if (d && d->playlist) {
         ret = talloc_zero(NULL, struct playlist);
         playlist_populate_playlist_path(d->playlist, file);
```
Comment (kasper93) [inline common/playlist.c:418]: shouldn't this use path now?

File: player/loadfile.c [hunk 5]
```diff
@@ -912,6 +915,7 @@ int mp_add_external_file(struct MPContext *mpctx, char *filename,
 
 err_out:
     demux_cancel_and_free(demuxer);
+    talloc_free(path);
```
Comment (kasper93) [inline player/loadfile.c:918]: not needed anymore

File: common/playlist.c (hunk 4 above)
Comment (Dudemanguy) [reply common/playlist.c:418]: I interpreted playlist path to mean the unexpanded url so not path in this case.

**Comment by Dudemanguy** [comment]
The intent is supposed to be any `M_OPT_FILE` option. The status quo right now is a mix of some of those options expanding and some don't which is bizarre and not intuitive.

I might I have missed one somewhere. Haven't double checked yet.

**Comment by Dudemanguy** [comment]
>I might I have missed one somewhere. Haven't double checked yet.

I believe I got all the options that weren't handling this.
