### PR TITLE
x11: avoid XPresent API calls when it's not needed

### LINKED ISSUE #10326: mpv performance is bad with --gpu-context=x11vk or --gpu-api=vulkan
### Important Information

mpv version:

```zsh
mpv 0.34.0-353-g230d490eca Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Jun 22 12:49:46 2022
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```

linux destribution and version:

```zsh
Operating System: Manjaro Linux
Kernel: Linux 5.18.5-1-MANJARO
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

window manager: x11, KDE Plasma 5.25.0

GPU driver: proprietary nvidia driver 515.48.07

introduced in: https://github.com/mpv-player/mpv/commit/3d459832a88a9bd2835b339cf6ca98f84aad0115

### Reproduction steps

`mpv --no-config --gpu-context=x11vk 1.mp4`

or

`mpv --no-config --gpu-api=vulkan 1.mp4`

gives the same result

### Expected behavior

Video plays without issues

### Actual behavior

Very poor performance with a lot of dropped frames

### Log file

`--gpu-context=x11vk` log: https://0x0.st/ouFh.txt

`--gpu-api=vulkan` log: https://0x0.st/ouFF.txt

Additional info: continuation of discussion in #10320

After rebuilding several times I found out the commit, where this behavior was introduced (see above).

### LINKED ISSUE #10327: mpv with xpresent causes entire DE to crash, without xpresent no video
### Important Information

- **mpv version:** 0.34.0-355-g24f4582b6f (24f4582b6f7f57f566418551f9252b8578d2b602)
- **Linux Distribution and Version:** Gentoo
- **Source of the mpv binary:** Self-Compiled, GCC 11.3.0
- **If known which version of mpv introduced the problem:** 3d459832a88a9bd2835b339cf6ca98f84aad0115
- **Window Manager and version:** X11/xorg-server 21.1.3-r2, Plasma 5.24.5
- **GPU driver and version:** nvidia 510.73.05
- **Possible screenshot or video of visual glitches:** Not feasible

### Reproduction steps

1. Build mpv off of 24f4582b6f7f57f566418551f9252b8578d2b602 with meson
2. Load any video file

### Expected behavior

A window opens up and a video plays.

### Actual behavior

Without libXpresent installed mpv doesn't open a window and playback ceases with these error messages:
```
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Cannot retrieve DRM resources: Operation not supported
[vo/gpu/opengl] Failed to create KMS.
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```

With libXpresent installed my entire screen goes black, my monitor cycles through inputs indicating it lost signal, and I am spit back out to my display manager (SDDM). I assume my entire DE has crashed.

I compiled mpv once without Xpresent installed and once with Xpresent installed.

### Log file (No Xpresent)

https://0x0.st/oSr0.txt

### Log file (Xpresent)

https://0x0.st/oSrD.txt

### PR DESCRIPTION
**Pull request by Dudemanguy**
This commit kind of mixes several related things together. The main
thing is to avoid calling any XPresent functions or internal functions
related to presentation when the feature is not auto-whitelisted or
enabled by the user. Internally rework this so it all works off of a
use_present bool (have_present is eliminated because having a non-zero
present_code covers exactly the same thing) and make sure it updates on
runtime. Finally, put some actual logging in here whenever XPresent is
enabled/disabled. Fixes #10326.

Also fixes #10327.

### CODE REVIEW

File: video/out/x11_common.c [hunk 1]
```diff
@@ -377,6 +377,19 @@ static int vo_wm_detect(struct vo *vo)
...
 }
 
+static void xpresent_set(struct vo_x11_state *x11)
+{
+    int present = x11->opts->x11_present;
+    x11->use_present = x11->present_code &&
+                       ((x11->has_mesa && !x11->has_nvidia && present) ||
+                        present == 2);
+    if (x11->use_present) {
+        MP_VERBOSE(x11, "XPresent statistics enabled.\n");
```
Comment (sfan5) [inline video/out/x11_common.c:387]: are they actually called statistics?

Comment (Dudemanguy) [reply video/out/x11_common.c:387]: Not really. How about `XPresent events` instead?

**Comment by ripose-jp** [comment]
I've tested this and it fixes #10327.
