### PR TITLE
input: make command argument list a dynamic array

### LINKED ISSUE #5375: [input] Command cycle-values has trailing unused arguments: ' 1'.
### mpv version and platform
mpv 2:0.26.0+git1~trusty1 on Ubuntu 14.04.5 LTS

### Reproduction steps
A value before the last value in `window-scale` in `~/.config/mpv/input.conf` : 
BEFORE : 
$ grep "^[^#].*window-scale" .config/mpv/input.conf
Ctrl+d	cycle_values window-scale 0.75 1 1.5 2 2.5 3 3.5 4 1
AFTER : 
$ grep "^[^#].*window-scale" .config/mpv/input.conf
Ctrl+d	cycle_values window-scale 0.75 1 1.5 2 2.5 3 3.5 4 4.5 1

### Expected behavior
The new value is taken into account
### Actual behavior
[input] Command cycle-values has trailing unused arguments: ' 1'.
[input] Command was defined at /home/sebastien/.config/mpv/input.conf:12.
### Log file

LOG : [output.txt](http://paste.ubuntu.com/26355283/)

### Sample files

It is a keyboard shortcut definition issue, therefore it occurs every time when playing any file or URL you want.

### PR DESCRIPTION
**Pull request by wm4**
Replace the static array with dynamic memory allocation. This also
requires some code to honor mp_cmd.nargs more strictly. Generally
allocates more stuff.

Fixes #5375 (although we could also just raise the static limit).

---

Well, not sure if this is better, or if the static limit should simply be raised.

### CODE REVIEW

File: input/input.h [hunk 1]
```diff
@@ -56,6 +56,9 @@ enum mp_input_section_flags {
 struct input_ctx;
 struct mp_log;
 
+// Arbitrary upper bound for sanity.
+#define MP_CMD_MAX_ARGS 100
```
Comment (kevmitch) [inline input/input.h]: So this is enforced in `parse_cmd_str`? Should there be some warning when it is hit? Am I correct in understanding this limit can be circumvented with `mp_input_parse_cmd_strv`?

Comment (wm4) [reply input/input.h]: The parser will show the same error as before when the maximum number of args was reached. The strv variant is not limited by this, but yeah maybe that does not make much sense.

I think I kept MP_CMD_MAX_ARGS only because javascript.c uses it for some reason, and I was too lazy to update that.

Comment (avih) [reply input/input.h]: > I think I kept MP_CMD_MAX_ARGS only because javascript.c uses it for some reason, and I was too lazy to update that.

Isn't it the correct usage, at least before this patch? If not, what would have been the correct usage? `lua.c` hardcodes it to 50, but it won't work with more than MP_CMD_MAX_ARGS iirc.

Comment (kevmitch) [reply input/input.h]: For some reason, @wm4 hates this question. I'll just merge this for now. We can address eliminating or making more consistent use of `MP_CMD_MAX_ARGS` in a future commit.
