### PR TITLE
options: rename --video-aspect to --video-aspect-override

### LINKED ISSUE #6068: Can not toggle to 1.778 and 1.333 aspect ratio via shift-a
### mpv version and platform
v0.29.0 on 4.17.12-200.fc28.x86_64
I originally noticed with rpm-fusion rpm build for this version.  Below is results from local build.
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build/
./use-mpv-release
./update
./rebuild -j6
### Reproduction steps
cd mpv/build
./mpv FILE
press shift-A
### Expected behavior
Should show video in 1.778 ratio (16:9)
(pressing again would show 1.333)
(pressing again would show 2.350)
### Actual behavior
Shows 2.350, pressing again returns to 2.348
### Log file
https://0x0.st/sJTy.log
### Sample files
Did not attach.  Seems to behave this way with all locally derived and fetched from web

### PR DESCRIPTION
**Pull request by haasn**
The justification for this is the fact that the `video-aspect` property
doesn't work well with `cycle_values` commands that include the value
"-1".

The "video-aspect" property has effectively no change in behavior, but
we may want to make it read-only in the future. I think it's probably
fine to leave as-is, though.

Fixes #6068.

Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

File: options/options.c [hunk 1]
```diff
@@ -519,7 +519,7 @@ const m_option_t mp_opts[] = {
 
     // -1 means auto aspect (prefer container size until aspect change)
     //  0 means square pixels
-    OPT_ASPECT("video-aspect", movie_aspect, UPDATE_IMGPAR, -1.0, 10.0),
```
Comment (wm4) [inline options/options.c]: Doesn't this and the OPT_REPLACE below means the behavior of ``video-aspect`` as visible to the user changes, which would break compatibility? I didn't try it myself, and what actually happens probably depends much on the property/option bridge in presence of renamed options, which isn't really a rabbit hole I want to get down.

File: DOCS/man/input.rst [hunk 2]
```diff
@@ -1937,10 +1937,10 @@ Property list
     Estimated deviation factor of the vsync duration.
 
 ``video-aspect`` (RW)
-    Video aspect, see ``--video-aspect``.
+    Video aspect, sse ``--video-aspect-override``.
 
     If video is active, this reports the effective aspect value, instead of
-    the value of the ``--video-aspect`` option.
+    the value of the ``--video-aspect-override`` option.
```
Comment (wm4) [inline DOCS/man/input.rst]: Does this sentence really still make sense?

It should also mention that it's deprecated, and how a user should change to non-deprecated mechanisms. This is the nasty part because you need to think about how human users and API users might have (mis)used it.

There's also another mention of ``video-aspect`` in input.rst in the "Inconsistencies between options and properties" which this commit touches upon.

File: options/options.c (hunk 1 above)
Comment (haasn) [reply options/options.c]: Oh, yes, that doesn't interact at all. Good catch. This actually segfaults.

Comment (haasn) [reply options/options.c]: Decided to just have the property directly feed through to video-aspect-override without going via the deprecated option bridge, and print a deprecation warning via some dumb hack.

The plan is to rewrite this function completely once the deprecation period is over, and script authors have had time to adjust. In the meantime, the bug will be fixed for users.

File: DOCS/man/input.rst (hunk 2 above)
Comment (haasn) [reply DOCS/man/input.rst]: Clarified the interaction in the documentation of `video-aspect`. I also just removed that reference since there's no more `--video-aspect` option, technically.
