### PR TITLE
command: notify media-title on force-media-title change

### LINKED ISSUE #12887: Observing media-title property doesn't update when media-title changes
### Important Information

Provide following Information:
- mpv ad02db8ceefc8cd8a52ea0cbeff0a18e80882c6f
- Arch Linux
- compiled from source

Observing `media-title` should result in updates any time `media-title` changes, but instead it only updates with `MP_EVENT_METADATA_UPDATE` events, which is insufficient.

### Reproduction steps

1. Observe `media-title` in a script with `mp.observe_property('media-title', 'string', function(_, val) print(val) end)`
2. Open some file
3. Run in console: set force-media-title asdf

### Expected behavior

The script gets notified about the `media-title` change.

### Actual behavior

No updates.

### Log file

not needed

### Sample files

not needed

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Fixes #12887

### CODE REVIEW

File: player/command.c [hunk 1]
```diff
@@ -6966,8 +6966,11 @@ void mp_option_change_callback(void *ctx, struct m_config_option *co, int flags,
     bool init = !co;
     void *opt_ptr = init ? NULL : co->data; // NULL on start
 
-    if (co)
+    if (co) {
         mp_notify_property(mpctx, co->name);
+        if (opt_ptr == &opts->media_title)
+            mp_notify_property(mpctx, "media-title");
```
Comment (sfan5) [inline player/command.c:6972]: I don't think there's a need for this to be in the `if (co)`, is there?
all the other checks are a bunch of lines below

also not sure if it would be cleaner to do `mp_notify(mpctx, MP_EVENT_METADATA_UPDATE, NULL)`

Comment (christoph-heinrich) [reply player/command.c:6972]: At first I had it at the end of the function, but then I though it should probably be next to the other notify call.

The actual metadata of the file doesn't change when `force-media-title` is set, so I don't think `mp_notify(mpctx, MP_EVENT_METADATA_UPDATE, NULL)` makes sense here. It would work but seems overkill.

Comment (christoph-heinrich) [reply player/command.c:6972]: Actually `MP_EVENT_METADATA_UPDATE` is better because of the playlist title thing, but I could factor that out into it's own function and call that.

Whichever you prefer.

Comment (sfan5) [reply player/command.c:6972]: not sure what you mean.
just put the right `mp_notify` in this function and call it a day?

Comment (christoph-heinrich) [reply player/command.c]: This is what I mean.

Comment (christoph-heinrich) [reply player/command.c]: I've changed it to the `mp_notify` for simplicity, it's not like that will cause any performance problems.

Comment (christoph-heinrich) [reply player/command.c]: > I've changed it to `mp_notify` for simplicity, it's not like that will cause any performance problems.

**Review by sfan5 — APPROVED** [review]
