### PR TITLE
demux_lavf: set duration to -1 if unknown

### LINKED ISSUE #12454: regression in seeking streams with no PTS with --no-correct-pts
### Important Information

Provide following Information:
- mpv version: starting with v0.36.0-240-g67368ac5 until latest
- Windows Version: build 22621
- Source of the mpv binary: scoop or sourceforge.net/projects/mpv-player-windows
- If known which version of mpv introduced the problem: v0.36.0-240-g67368ac5 or a few commits earlier. Binary released immediately before v0.36.0-174-g83c0e980, works correctly

### Reproduction steps

Load a live h264 stream with no PTS, such as that generated by an IP camera. Use `--no-correct-pts ` to enable frame-based seeking through the demuxer cache.

### Expected behavior
Seeking works through the demuxer cache.

### Actual behavior
Seeking either doesn't work at all or stops working after seeking backward and forward a few times through the cache.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12686742/output.txt)

### PR DESCRIPTION
**Pull request by llyyr**
`demux->duration` is set to -1 on initialization, and some checks rely on it being -1 when unknown. Before this commit, we set `demux->duration` to 0 when unknown. This is incorrect and breaks rtsp logic for disabling seeking outside of cached regions.

To fix these issues, initialize `total_duration` and `av_duration` at -1. They're only changed if a real duration is detected, so in cases where the duration is unknown, demux->duration is set to -1 correctly.

Fixes: e6afc53e7c ("demux_lavf: get total duration from track durations")
Fixes #12454

### CODE REVIEW

**Review by Dudemanguy — APPROVED** [review]
Looks reasonable

**Comment by llyyr** [comment]
@myspaghetti can you try testing with the mpv build from this PR to see if this fixes your issue? https://github.com/mpv-player/mpv/actions/runs/6265175874

File: demux/demux_lavf.c [hunk 1]
```diff
@@ -1166,7 +1166,7 @@ static int demux_open_lavf(demuxer_t *demuxer, enum demux_check check)
             av_duration = MPMAX(av_duration, f_duration);
     }
     double duration = av_duration > 0 ? av_duration : total_duration;
-    if (duration == 0 && priv->avfc->duration > 0)
+    if (duration < 0 && priv->avfc->duration > 0)
```
Comment (sfan5) [inline demux/demux_lavf.c:1169]: I think `<=` would still be correct here

**Comment by myspaghetti** [comment]
This build seeks correctly, thank you!

(Playback is more jerky, frames are unnecessarily skipped when skipping or fast-forwarding, fps appears to be limited to stream fps instead of display fps, but this appears to be a different issue.)

Thank you so much! You addressed this issue remarkably fast!

**Comment by llyyr** [comment]
More time was spent trying to get a working rtsp stream than figuring out the bug...

Thanks for testing.
