### PR TITLE
af_scaletempo2: use gcc vectors to speed up inner loop

### LINKED ISSUE #8848: scaletempo2 takes too much CPU
### Important Information
Provide following Information:
- mpv version
git master
- Linux Distribution and Version
ubuntu 20.04 
- Source of the mpv binary
git master
- If known which version of mpv introduced the problem
- Window Manager and version
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Recently, when I use 2x speed playback, the CPU is more than twice as high as when I use 1x speed playback.
When 1x , cpu= 18.2 %
./mpv  --no-config /home/test/Videos/1080-test.mp4
then if 2x,cpu = 48.2 %
./mpv  --no-config --speed=2.0 /home/test/Videos/1080-test.mp4

### Expected behavior
There shouldn't be such a high CPU usage.
Compared with scaletempo, my impression is close to 10% less than scaletempo 2 (but I'm not sure, it's just an inaccurate recollection of the previous impression -( )
### Log file

The issue will be closed for ignoring the issue template.

### Sample files
Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

### PR DESCRIPTION
**Pull request by haasn**
This brings my scaletempo2 benchmark down from ~22s to ~8s on my machine
(-march=native), and down to ~11s with a generic compile.

Closes #8848

TODO:
- [x] figure out why I get the following warning:

```
./audio/filter/af_scaletempo2_internals.c: In function ‘hsum8’:
../audio/filter/af_scaletempo2_internals.c:111:21: note: the ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
  111 | static inline float hsum8(v8sf v8)
      |                     ^~~~~
```

### CODE REVIEW

**Comment by CounterPillow** [comment]
10x speedup on my zen+ (so x86_64-v2) with `-mtune=native -march=native`, still >= 2x with just generic x86_64 on the same chip. Definitely an improvement worth the amount of code.

File: audio/filter/af_scaletempo2_internals.c [hunk 1]
```diff
@@ -104,6 +104,10 @@ static float multi_channel_similarity_measure(
     return similarity_measure;
 }
 
+#if HAVE_VECTOR
```
Comment (sfan5) [inline audio/filter/af_scaletempo2_internals.c:107]: <pre>
../audio/filter/af_scaletempo2_internals.c:107:5: Warnung: »HAVE_VECTOR« ist nicht definiert, wird zu 0 ausgewertet [-Wundef]
  107 | #if HAVE_VECTOR
      |     ^~~~~~~~~~~

</pre>

**Review by sfan5 — CHANGES_REQUESTED** [review]
Works other than that.

File: audio/filter/af_scaletempo2_internals.c (hunk 1 above)
Comment (CounterPillow) [reply audio/filter/af_scaletempo2_internals.c:107]: Did you run a `./waf configure` beforehand?

Comment (avih) [reply audio/filter/af_scaletempo2_internals.c:107]: All the `HAVE_*` values are defined at `config.h`, but `config.h` is not included in this file, and it's not obvious that it's included from other headers here.

Comment (haasn) [reply audio/filter/af_scaletempo2_internals.c:107]: Fixed.

**Review by sfan5 — APPROVED** [review]

**Comment by avih** [comment]
LGTM.
