### PR TITLE
vo: clear request_redraw in render_frame only if video is playing

### LINKED ISSUE #17288: OSC UI does not always update during frame foward stepping
### mpv Information

```bash
mpv v0.40.0-dev-g02f47c882 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Dec 19 2025 17:47:42
libplacebo version: v7.358.0
FFmpeg version: f853d12
FFmpeg library versions:
   libavcodec      62.11.100
   libavdevice     62.1.100
   libavfilter     11.4.100
   libavformat     62.3.100
   libavutil       60.8.100
   libswresample   6.1.100
   libswscale      9.1.100
```

### Other Information

```text
- Windows version: Windows 11 Pro 24H2
- GPU model, driver and version: NVIDIA GTX 1070, 566.36
- Source of mpv: GitHub
```

### Reproduction Steps

1. Show the OSC by moving the mouse pointer over the player.

2. Pause playback.

3. Press the frame-forward shortcut key once.

4. The pause icon remains visible and the timecode does not update.

5. Hide and show the OSC by moving the mouse pointer away from and back over the player.

6. The play icon is shown and the timecode is updated.

If the issue does not occur, repeat steps 3–5.

### Expected Behavior

The OSC properly reflects the current play state and timecode during frame by frame step forward operations.

### Actual Behavior

Stepping forward frame by frame can in some cases cause the OSC to become stuck, which is indicated by the pause icon remaining visible and the timecode not updating. The issue persists until another frame action is performed or the OSC is hidden and shown again.

### Log File

[mpv_log.txt](https://github.com/user-attachments/files/24698932/mpv_log.txt)

### Sample Files

_No response_

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

### PR DESCRIPTION
**Pull request by Dudemanguy**
27a78276eb4b68f230e441e1baedf26f3cd66fbd almost got it but it should be an and condition not an or. When we unlock VO to draw the core, the OSD can update after we flip the page and the player can also pause itself in that time. That means that we will clear the redraw request but due to the OSD update it actually needs to draw again. Because the player paused itself in that time frame, this redraw gets lost and you have the mismatch. The simplest way to avoid that case is to only clear the redraw_request while mpv is playing. The paused case will always get handled later in do_redraw so it does not get missed. The slight downside is that it's technically possible to do a redundant redraw (e.g. what if you pause before draw_frame), but this theoretical inefficiency is deemed not really relevant or important enough to add more confusing code to avoid. Fixes #17288.

@somerandoname does this fix it for you?

### CODE REVIEW

**Comment by somerandoname** [comment]
It does indeed, thank you 😄

File: video/out/vo.c [hunk 1]
```diff
@@ -1054,13 +1054,13 @@ static bool render_frame(struct vo *vo)
...
-        // next loop will draw what we need. However if there initially is
+        // If the initial redraw request was true and mpv is still playing,
+        // then we can clear it here since the next loop will guarantee that
+        // we draw whatever is needed. However if there initially is
         // no redraw request, then something can change this (i.e. the OSD)
         // while the vo was unlocked. If we are paused, don't touch
-        // in->request_redraw in that case.
-        if (request_redraw || !in->paused)
+        // in->request_redraw in that case and let do_redraw do the work later.
+        if (request_redraw && !in->paused)
```
Comment (kasper93) [inline video/out/vo.c:1063]: This will make it constantly redraw in paused state?

Comment (Dudemanguy) [reply video/out/vo.c:1063]: The paused state does not constantly go through `render_frame`. mpv can pause itself in the middle of this function but on the next playloop it would hit the goto code at the top and skip all of this.
