### PR TITLE
player: set playlist title to media title if not set already

### LINKED ISSUE #4780: youtube titles in playlist (osd)
### mpv version and platform
```
mpv 0.26.0-179-g01058b16f9 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Aug 18 15:49:57 CEST 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.102.100
   libavformat     57.76.100
   libswscale      4.7.102
   libavfilter     6.99.100
   libswresample   2.8.100
ffmpeg version: N-87004-gcadab5a2a7

os = Debian 9
```
### Reproduction steps
Shift+drag youtube videos (not youtube playlists) to mpv window and see playlist in osd. 
In input.conf I have 'F3 script-message osc-playlist 5' to see the playlist.

### Expected behavior
The actual titles would show, same as if loading 'youtube.com/watch?list=somelist' type of links.

### Actual behavior
watch?v=xy shows.

### Log file
<http://paste.debian.net/plain/981977>

### p.s.
Possibly related: If this is 'youtube-dl is not telling me type of thing': Even with single video playing from youtube and it is already in full playback it will still show 'watch?v=xy' instead of title.

### PR DESCRIPTION
**Pull request by christoph-heinrich**
The title in the playlist should get set when we get a title and the playlist title isn't set already.

#8548 has essentially the same goal, but this has the advantage that
1. It actually works (maybe the handling of media-title has changed since that was implemented)
2. The title gets stored in the playlist item instead of only showing the media-title as the playlist-item title when the playlist property gets accessed, so printing the playlist will show the title too.
3. The media-title does not shadow the playlist-item title if it actually has one set.
4. Any playlist item that has been opened will have a title if it didn't already have one from the playlist file, not only the current one

Somewhat closes #4780, but still only shows titles for files/urls that have been opened before. I don't think we should make a bunch of requests just to get the titles.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Seems pretty good. The only nit I can find is that the `ytdl_hook` will sometimes override the media title anyways (which it does on master as well). I think that's just the logic in the script though and not anything to do with this. Dunno if you want to tackle that or not (in a separate commit). But otherwise LGTM.

**Comment by christoph-heinrich** [comment]
I don't see a problem with `ytdl_hook` setting `force-media-title`. This works fine with it in my testing.

**Comment by Dudemanguy** [comment]
If I set `--force-media-title` via cli or something, I would expect the ytdl_hook to not override it and respect what I set. It at least happens to me in some cases (for example, `mpv --force-media-title="test-title" someurl`). That has absolutely nothing to do with this PR though; it's just logic in the script.

**Review by Dudemanguy — APPROVED** [review]

File: player/command.c [hunk 1]
```diff
@@ -515,24 +515,27 @@ static int mp_property_media_title(void *ctx, struct m_property *prop,
...
+            if (!name || !name[0])
+                name = mp_tags_get_str(mpctx->demuxer->metadata, "icy-title");
+        }
+    }
+    struct playlist_entry *const pe = mpctx->playing;
+    if (pe) {
+        if (!name || !name[0]){
+            name = pe->title;
+        } else if (!pe->title) {
+            pe->title = talloc_strdup(pe, name);
```
Comment (sfan5) [inline player/command.c:534]: This is the property handler for `media-title`.
1) why does this _modify_ a playlist entry?
2) how does this work if nobody touches `media-title`?

Comment (Dudemanguy) [reply player/command.c:534]: If we want to set the playlist title to the media title it needs to be done in the `media-title` property handler not the playlist one since it would need to update itself anytime the `media-title` changes.

Comment (christoph-heinrich) [reply player/command.c:534]: You're right, I thought it was fine because the handler usually gets a ton of calls, but handler never gets called when running `mpv --no-config --no-terminal --no-osc --title=foo <some file>`.

Any suggestions on a better way of implementing that?

Comment (sfan5) [reply player/command.c:534]: Not sure, maybe in `update_demuxer_properties` or some other place that deals with playlist changes.
