### PR TITLE
wayland: fix segfault in surface_handle_enter due to memory read

### LINKED ISSUE #13887: Segmentation fault on wayland with force-window=immediate and a YouTube url
### Important Information

Provide following Information:
- current git master (919a042833202817492d1744e087836b6b02f63f)
- Arch linux
- compiled from source
- introduced by 895f40e150d4bf2261a96fc2586d75f998d2ac5d
- Plasma 6.0.3 with KWin 6.0.3.1
- AMD Radeon R9 380

### Reproduction steps

Run `mpv --no-config --gpu-context=wayland --force-window=immediate "https://www.youtube.com/watch?v=xCBrtopAG80"`

### Expected behavior

Video starts playing

### Actual behavior

Segmentation fault

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/14978615/log.txt)

### PR DESCRIPTION
**Pull request by llyyr**
Fixes: 895f40e150d4 ("wayland: only perform a rescale if window is on one output")

Fixes #13887

### CODE REVIEW

File: video/out/wayland_common.c [hunk 1]
```diff
@@ -957,7 +957,8 @@ static void surface_handle_enter(void *data, struct wl_surface *wl_surface,
         update_output_geometry(wl, old_geometry, old_output_geometry);
 
     MP_VERBOSE(wl, "Surface entered output %s %s (0x%x), scale = %f, refresh rate = %f Hz\n",
```
Comment (kasper93) [inline video/out/wayland_common.c:959]: How about we move it inside the loop instead?

Comment (sfan5) [reply video/out/wayland_common.c:959]: I had that thought too but `update_output_geometry` probably sets `wl->scaling`

**Comment by christoph-heinrich** [comment]
Thanks for fixing this so quickly. I had to leave before and now after coming back I wanted to have a look, but you were faster :smile:

**Review by christoph-heinrich — APPROVED** [review]

File: video/out/wayland_common.c (hunk 1 above)
Comment (Dudemanguy) [reply video/out/wayland_common.c:959]: Yep.

**Comment by Dudemanguy** [comment]
Thanks, logically this should have always been `wl->current_output` anyways.
