### PR TITLE
console.lua: allow subsequent mp.input calls

### LINKED ISSUE #15795: opening selector multiple times will cause the selection to fail, is it a `input.select` API bug?
### mpv Information

```bash
mpv v0.39.0-723-g38ad1ed0 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Feb  1 2025 17:04:54
libplacebo version: v7.350.0 (v7.349.0-30-g056b852-dirty)
FFmpeg version: N-118392-g0113e3080
FFmpeg library versions:
   libavcodec      61.31.101
   libavdevice     61.4.100
   libavfilter     10.9.100
   libavformat     61.9.106
   libavutil       59.56.100
   libswresample   5.4.100
   libswscale      8.13.100
```

### Other Information

```text
- Windows version: Win10 22H2
- GPU model, driver and version:
- Source of mpv: https://github.com/zhongfly/mpv-winbuild/releases/tag/2025-02-02-38ad1ed
- Latest known working version:
- Issue started after the following happened:
```

### Reproduction Steps

- bind alt+s to close console and open subtitle selector
```ini
alt+s    script-message-to console disable; script-binding select/select-sid
```
- play any video with subtitles
- press alt+s two times
- press enter to select any subtitle

### Expected Behavior

subtitle selected

### Actual Behavior

nothing happened

### Log File

[log.txt](https://github.com/user-attachments/files/18640666/log.txt)

### Sample Files

N/A

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

### PR DESCRIPTION
**Pull request by guidocella**
Currently using mp.input while the console is open doesn't do anything. We can allow using mp.input multiple times in a row by keeping the console open, and sending a closed event only when the previous calling script is different from the current one. If it is the same, sending a closed event would unregister the new input-event listener, so it is just never sent in this case as there is no sane way to do it.

Fixes #15795.

### CODE REVIEW

File: player/lua/console.lua [hunk 1]
```diff
@@ -1837,8 +1837,9 @@ mp.register_script_message('type', function(text, cursor_pos)
 end)
 
 mp.register_script_message('get-input', function (script_name, args)
-    if repl_active then
-        return
+    if repl_active and input_caller and script_name ~= input_caller then
+        mp.commandv('script-message-to', input_caller, 'input-event',
+                    'closed', utils.format_json({line, cursor}))
```
Comment (kasper93) [inline player/lua/console.lua:1842]: This looks hacky.

Comment (guidocella) [reply player/lua/console.lua:1842]: Better suggestions welcome.

Comment (kasper93) [reply player/lua/console.lua:1842]: Have a stack with the state, and restore whatever was/is open after select ended.

Comment (kasper93) [reply player/lua/console.lua:1842]: I meant the other way, to immediate go to user requested input, but go back to previous state, if requested (closed without select). i.e. allow nested menus in menu type situation.

Comment (guidocella) [reply player/lua/console.lua:1842]: Isn't it strange to go back to the previous state when it was invoked by a completely different script doing something completely different? I think it should still send `closed` to different scripts like in this PR. Restoring the previous state from the same script is a separate functionality that can be added later.

Comment (kasper93) [reply player/lua/console.lua:1842]: I think close without select or indeed another dedicated function could achieve that.

As for the rest, I don't think other scripts should be able to interrupt the selection that is being made, with implicit way. If it is invoked as "nested" select we can support that to provide "menu" like interface, but I don't see others nuking already open select. That's why I feel that it is hacky, because we allow it to open and send some implicit closed events, but only if script is different, it's weird.

Comment (guidocella) [reply player/lua/console.lua:1842]: That's fair though I think one reasonable use case for it is to try out `script-binding select/...` bindings in the console, this was actually requested in https://github.com/mpv-player/mpv/pull/14087#issuecomment-2109128569 (and I misunderstood it as referring to the input queue at that time too).

**Comment by guidocella** [comment]
This doesn't actually fix calling `input.select` again within `submit` because console already closes automatically on select so `closed` is received after `submit` and it unregisters the new event listener instead of the old one. A fix would be just not to call `mp.unregister_script_message("input-event")` whose only purpose was to allow garbage collection of variables defined in the scope calling `mp.input`. This PR does fix the `get -> get` and `get -> select` cases as with `get` console stays open until it is asked to close.

**Comment by guidocella** [comment]
I just removed the `unregister_script_message` call.

**Review by kasper93 — APPROVED** [review]
works.
