### PR TITLE
win32: improve window snapping behavior

### LINKED ISSUE #6588: When mpv window is snapped, drag-border resize should be fullfilled by moving 2 non-snapped sides of window to fully stay in the screen, not going out of it.
MPV resize suggestion
### mpv version and platform
0.29.1, Windows 7

### Reproduction steps
1. Launch mpv with snap ON in mpv.conf.
2. Snap window to let's say lower right corner so that right and bottom sides were magnet to screen edges.
3. Drag to resize either left or top border of mpv.
### Expected behavior
Window should resize to Left+Up as this way it doesn't go out of the screen and Right and Down borders are snapped so should remain there.
### Actual behavior
Snapped borders are no longer snapped and mpv window is getting resized out of the screen.

### PR DESCRIPTION
**Pull request by sunpenghao**
Several window resizing operations (i.e., `--auto-window-resize`,
border dragging with `--keep-aspect-window`, Alt+0/1/2) cause the
window to detach from the snapped borders. This patch resolves
this by recording to which borders the window is snapped, and
using this info to determine how the window should be placed after
resizing. Closes https://github.com/mpv-player/mpv/issues/6588.

### CODE REVIEW

**Comment by kasper93** [comment]
When snapped and on resize window exceeds available area it will unsnap, but flag is still set. This causes the window move around and eventually go outside client area.

Also I would suggest extending `--snap-window` to enum, I personally prefer window resized around the center of the window as it is now. Although I totally understand anchoring on sides.

File: video/out/w32_common.c [hunk 1]
```diff
@@ -1514,8 +1532,19 @@ static void gui_thread_reconfig(void *ptr)
...
+    else if (w32->snapped_right)
+        x = rc->right - vo->dwidth;
+    else
+        x = rc->left + rect_w(*rc) / 2 - vo->dwidth / 2;
+    if (w32->snapped_top)
+        y = rc->top;
+    else if (w32->snapped_bottom)
+        y = rc->bottom - vo->dheight;
+    else
+        y = rc->top + rect_h(*rc) / 2 - vo->dheight / 2;
```
Comment (kasper93) [inline video/out/w32_common.c:1547]: Please add some parentheses or empty lines for readability.

File: video/out/w32_common.c [hunk 2]
```diff
@@ -1808,8 +1838,20 @@ static int gui_thread_control(struct vo_w32_state *w32, int request, void *arg)
...
+        else if (w32->snapped_right)
+            x = rc->right - s[0];
+        else
+            x = rc->left + rect_w(*rc) / 2 - s[0] / 2;
+        if (w32->snapped_top)
+            y = rc->top;
+        else if (w32->snapped_bottom)
+            y = rc->bottom - s[1];
+        else
+            y = rc->top + rect_h(*rc) / 2 - s[1] / 2;
```
Comment (kasper93) [inline video/out/w32_common.c:1854]: This looks like exactly the same logic, might want to enclose it in function to not duplicate it, to avoid desync in future.

File: video/out/w32_common.c (hunk 1 above)
Comment (sunpenghao) [reply video/out/w32_common.c]: Done. Wrapped it in a function.

**Comment by sunpenghao** [comment]
> When snapped and on resize window exceeds available area it will unsnap, but flag is still set. This causes the window move around and eventually go outside client area.

Fixed. This was because `fit_window_on_screen` may move the window when the title bar goes above the screen, and this move was not adjusted by the `snapped_*` flags. One thing I'm not sure in this case though is whether we should let the title bar snap to the top after this move. At the moment it doesn't, so the window will still move around in the example below. But now the window will converge to 3 and stay there instead of moving around forever.

图片1

> Also I would suggest extending `--snap-window` to enum, I personally prefer window resized around the center of the window as it is now. Although I totally understand anchoring on sides.

I'm not sure I fully understand your idea. Are you suggesting something like `--snap-window=<no|drag_only|always>`?

**Comment by kasper93** [comment]
> One thing I'm not sure in this case though is whether we should let the title bar snap to the top after this move. At the moment it doesn't, so the window will still move around in the example below. But now the window will converge to 3 and stay there instead of moving around forever.

For me it would be intuitive that it snaps. I mean no matter how we arrive to state `2`, it should consistently be snapped at this point.

> I'm not sure I fully understand your idea. Are you suggesting something like --snap-window=<no|drag_only|always>?

This was the idea, indeed. But after thinking about it, probably not worth making it more complex like that. Let's go with your logic, it makes more sense than current one.

**Comment by sunpenghao** [comment]
> For me it would be intuitive that it snaps. I mean no matter how we arrive to state 2, it should consistently be snapped at this point.

Makes sense. In fact I'm thinking about letting `fit_window_on_screen` keep the window entirely within the screen. For now it only ensures that the title bar does not go outside. I'm not sure if it's a Windows convention sort of thing though.

> This was the idea, indeed. But after thinking about it, probably not worth making it more complex like that. Let's go with your logic, it makes more sense than current one.

Yeah that's my plan as well. Also if we change this flag option to an enum one people using `--snap-window=yes` and `--no-snap-window` will have to change their config. It's just a window behavior thing so I guess keeping it stable would be better.

**Comment by kasper93** [comment]
Works fine now.

One observation not related to snapping itself. Maybe we should `fit_window_on_screen` also other borders, to not go outside the screen.

**Comment by kasper93** [comment]
Ah, one more thing. When both top and bottom (or left and right) borders are snapped, next resize should behave as if it were not snapped. Now it prefers top border snap, and stays top if we make window smaller. I would prefer it stay centered in this case.

Hope I'm clear? I can make drawing to explain better.

**Comment by sunpenghao** [comment]
> Works fine now.
> 
> One observation not related to snapping itself. Maybe we should `fit_window_on_screen` also other borders, to not go outside the screen.

I was actually thinking about doing that. I wrote this in my earlier comment (deleted now):

> In fact I'm thinking about letting fit_window_on_screen keep the window entirely within the screen. I mean it already shrinks the window to the screen size, but only ensures that the title bar does not go outside. I don't see why it doesn't go further and make sure the window stays inside the screen. I'm not sure if it's a Windows convention sort of thing though.

But then I realized if we enforce this for all borders, users won't be able to leave the window at a position that spans multiple monitors. Perhaps it's better to leave it the way it is now.

**Comment by sunpenghao** [comment]
> Ah, one more thing. When both top and bottom (or left and right) borders are snapped, next resize should behave as if it were not snapped. Now it prefers top border snap, and stays top if we make window smaller. I would prefer it stay centered in this case.
> 
> Hope I'm clear? I can make drawing to explain better.

Yes I get your point. Should be easy to implement.

**Comment by kasper93** [comment]
> But then I realized if we enforce this for all borders, users won't be able to leave the window at a position that spans multiple monitors. Perhaps it's better to leave it the way it is now.

Sure, leave it for now. It should probably be clever about whole virtual display area. I recall there were complaints about `fit_window_on_screen` not working correctly when taskbar is hidden and so on.

**Comment by sunpenghao** [comment]
Pushed another version and opted for the following logic:

- If one of the two opposite borders touch the screen edges, let it snap.
- If both of the opposite borders touch the screen edges:
    - For mouse drags, prefer `left` over `right`, `top` over `bottom`. (It needs to at least snap somewhere with `--snap-window`, I think.)
    - For resizes, pick the border that was previously snapped and snap that border. If none was snapped, don't snap any. Coding-wise we can leave the `snapped-*` flags as is in this case.

Does this sound reasonable?

**Comment by kasper93** [comment]
I tested quickly, I'm fine with current behavior. We can always improve on it if there are better ideas.

**Comment by sunpenghao** [comment]
Rebased on latest `master`. No conflicts.

**Comment by kasper93** [comment]
Could you rebase on current master?

**Comment by sunpenghao** [comment]
> Could you rebase on current master?

Done.

**Comment by Dudemanguy** [comment]
Kasper OK'd this in IRC the other day so fine by me.
