### PR TITLE
ao_coreaudio: set ao->device_buffer base on hardware latency

### LINKED ISSUE #7172: ao/coreaudio Audio underflow
### mpv version and platform

macOS 10.14.6
mpv 0.30 from brew

### Reproduction steps

Playing various format music files.

### Expected behavior

No underrun.

### Actual behavior

The music randomly stalls sometimes.  At these times this is logged on the console.  It is quite jarring, so i am fairly sure i would have noticed if 0.29 did it as well, but i have no such recollection.

```
AO: [coreaudio] 44100Hz stereo 2ch floatp
A: 00:00:26 / 00:05:43 (7%)
[ao/coreaudio] Audio underflow by 1420 samples.
A: 00:02:26 / 00:05:43 (42%)
[ao/coreaudio] Audio underflow by 1420 samples.
A: 00:05:43 / 00:05:43 (99%)
```

Listened to the same file again couple of times, no uderrun. Not really sure about reproduction steps, but probably load specific?  when switching between apps?  cpu spikes?  just speculating.

for now i put in `mpv.conf`:

```
audio-buffer=1
```

but it's too early to say if it stops underflows.  however the documentation was very explicit about contacting the devs if changed long term, so that's another reason why i am posting this issue.

### PR DESCRIPTION
**Pull request by ruihe774**
Fixes #7172, #13189

Can someone test this? @rgaufman would you plz have a check?

### CODE REVIEW

File: audio/out/ao_coreaudio.c [hunk 1]
```diff
@@ -178,6 +178,7 @@ static int init(struct ao *ao)
         goto coreaudio_error;
 
     reinit_latency(ao);
+    ao->device_buffer = p->hw_latency_ns * ao->samplerate / 1000000000 * 2;
```
Comment (kasper93) [inline audio/out/ao_coreaudio.c:181]: Use `MP_TIME_NS_TO_S`

**Review by Akemi — APPROVED** [review]

**Comment by Akemi** [comment]
thanks @ruihe774
