### PR TITLE
ao_coreaudio: stop audio unit after idle timeout

### LINKED ISSUE #11617: While paused mpv prevents sleep on Mac, consumes CPU
### Important Information

Provide following Information:
- mpv version:  master
- macOS Version:  13.3.1
- Source of the mpv binary or bundle:  My own build using [mpv-build](https://github.com/mpv-player/mpv-build) and Xcode 14.3
- If known which version of mpv introduced the problem:  0.35.1?
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

- Start playing a video that has an audio track with mpv
- Pause playback
- Start [Activity Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac)
- Check the `Columns` menu item under the `View` menu and ensure `Preventing Sleep` is enabled
- Find the entry for `mpv` in `Activity Monitor`
- The `Preventing Sleep` column contains `Yes`
- `coreaudiod` consumes CPU until `mpv` terminates

The video _must_ have an audio track or the problem will not occur.

### Expected behavior
The Mac is allowed to sleep if `mpv` is not actively playing a video.

### Actual behavior
- `Activity Monitor` reports `mpv` is preventing sleep
-  `coreaudiod` consumes CPU

This does not occur when the same video is played with [QuickTime](https://support.apple.com/guide/quicktime-player/welcome/mac).

In addition to my own build of `mpv`, I also reproduced this behavior using the 0.35.1 release from [stolendata](https://laboratory.stolendata.net/~djinn/mpv_osx/).

Testing with the 0.35.0 release from [stolendata](https://laboratory.stolendata.net/~djinn/mpv_osx/) as well as the 0.34.1 release I am unable to reproduce either of these bad behaviors. After pausing `Activity Monitor` no longer reports `mpv` is preventing sleep and `coreaudiod` CPU use goes to zero.

However this results conflicts with a report from an IINA 1.3.1 user in issue https://github.com/iina/iina/issues/4354. That report is what caused me to notice this behavior. IINA 1.3.1 uses mpv 0.34.1. The user reporting the issue has an Intel Mac running macOS Ventura. Unfortunately they did not report the specific macOS version. My testing was done on a MacBookPro18,2 with the M1 Mac chip under the latest release of Ventura and I was unable to reproduce the problem with IINA 1.3.1. A development version of IINA using mpv 0.35.1 reproduces the problem.

I'm very troubled that I can not explain why the user is experiencing this with IINA 1.3.1. Maybe there is another problem lurking in this area? Or they are running an earlier version of Ventura? This is why I put a question mark at the end of my answer to `If known which version of mpv introduced the problem`.

Using [Terminal](https://support.apple.com/guide/terminal/welcome/mac) to inspect active power management system assertions with this command:
```bash
pmset -g assertions
```

Shows:
- Only the expected assertions before starting the test
- `mpv` creates an assertion to prevent sleep while playing the video
- `coreaudiod` creates an assertion on behalf of `mpv`
- `mpv` releases its assertion when playback is paused
- `coreaudiod` does not release its assertion, preventing sleep
- When `mpv` terminates  `coreaudiod` releases the assertion

This confirms that when playback is paused `mpv` is calling [IOPMAssertionRelease](https://developer.apple.com/documentation/iokit/1557090-iopmassertionrelease) to allow the Mac to sleep. Sleep is being prevented because `coreaudiod` created an assertion on behalf of `mpv` and that assertion is still active. As `coreaudiod` created the assertion on behalf o `mpv`, `Activity Monitor` reports `mpv` is preventing sleep.

Using 0.35.0 and 0.34.1 the same behavior of `coreaudiod` posting an assertion on behalf of `mpv` is seen, but when `mpv` is paused both assertions are released.

<details>
<summary><b>pmset assertions:</b></summary>

```bash
low-batt@gag ~$  pmset -g assertions
2023-04-23 11:55:35 -0400 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  0
   InternalPreventDisplaySleep    1
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 172(WindowServer): [0x00006c37000995f6] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:1000009e0 service:AppleHIDKeyboardEventDriverV2 product:Apple Internal Keyboard / Trackpad eventType:3"  
	Timeout will fire in 1800 secs Action=TimeoutActionRelease
   pid 119(powerd): [0x0001b7690001838b] 01:09:14 PreventUserIdleSystemSleep named: "Powerd - Prevent sleep while display is on"  
   pid 119(powerd): [0x0001c6a2001082fa] 00:04:17 InternalPreventDisplaySleep named: "com.apple.powermanagement.delayDisplayOff"  
	Timeout will fire in 42 secs Action=TimeoutActionTurnOff
No kernel assertions.
low-batt@gag ~$  pmset -g assertions
2023-04-23 11:56:16 -0400 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             0
   ExternalMedia                  0
   InternalPreventDisplaySleep    1
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 119(powerd): [0x0001b7690001838b] 01:09:55 PreventUserIdleSystemSleep named: "Powerd - Prevent sleep while display is on"  
   pid 119(powerd): [0x0001c6a2001082fa] 00:04:58 InternalPreventDisplaySleep named: "com.apple.powermanagement.delayDisplayOff"  
	Timeout will fire in 1 secs Action=TimeoutActionTurnOff
   pid 54365(mpv): [0x0001c7c6000584c2] 00:00:06 PreventUserIdleDisplaySleep named: "io.mpv.video_playing_back"  
   pid 190(coreaudiod): [0x0001c7c6000184bc] 00:00:06 PreventUserIdleSystemSleep named: "com.apple.audio.BuiltInSpeakerDevice.context.preventuseridlesleep"  
	Created for PID: 54365. 
   pid 172(WindowServer): [0x00006c37000995f6] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:1000009e0 service:AppleHIDKeyboardEventDriverV2 product:Apple Internal Keyboard / Trackpad eventType:3"  
	Timeout will fire in 1800 secs Action=TimeoutActionRelease
No kernel assertions.
low-batt@gag ~$  pmset -g assertions
2023-04-23 11:56:33 -0400 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  0
   InternalPreventDisplaySleep    1
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 119(powerd): [0x0001b7690001838b] 01:10:13 PreventUserIdleSystemSleep named: "Powerd - Prevent sleep while display is on"  
   pid 119(powerd): [0x0001c7d9001082fa] 00:00:04 InternalPreventDisplaySleep named: "com.apple.powermanagement.delayDisplayOff"  
	Timeout will fire in 295 secs Action=TimeoutActionTurnOff
   pid 172(WindowServer): [0x00006c37000995f6] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:1000009e0 service:AppleHIDKeyboardEventDriverV2 product:Apple Internal Keyboard / Trackpad eventType:3"  
	Timeout will fire in 1800 secs Action=TimeoutActionRelease
   pid 190(coreaudiod): [0x0001c7c6000184bc] 00:00:23 PreventUserIdleSystemSleep named: "com.apple.audio.BuiltInSpeakerDevice.context.preventuseridlesleep"  
	Created for PID: 54365. 
No kernel assertions.
low-batt@gag ~$  pmset -g assertions
2023-04-23 11:56:53 -0400 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  0
   InternalPreventDisplaySleep    1
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 172(WindowServer): [0x00006c37000995f6] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:1000009e0 service:AppleHIDKeyboardEventDriverV2 product:Apple Internal Keyboard / Trackpad eventType:3"  
	Timeout will fire in 1800 secs Action=TimeoutActionRelease
   pid 119(powerd): [0x0001b7690001838b] 01:10:32 PreventUserIdleSystemSleep named: "Powerd - Prevent sleep while display is on"  
   pid 119(powerd): [0x0001c7d9001082fa] 00:00:24 InternalPreventDisplaySleep named: "com.apple.powermanagement.delayDisplayOff"  
	Timeout will fire in 276 secs Action=TimeoutActionTurnOff
No kernel assertions.
low-batt@gag ~$ 
```
</details>

Using [Terminal](https://support.apple.com/guide/terminal/welcome/mac) to monitor CPU usage with this command:
```bash
while true; do ps -e -o 'args,%cpu,cputime' | grep 'coreaudiod\|mpv' | grep -v grep; sleep 5; done
```

Shows:
- `coreaudiod` is idle before `mpv` is started
- Both consume CPU while playing
- `mpv` CPU drops to near 0 while paused
-  `coreaudiod` continues to use a significant amount of CPU
-  `coreaudiod` drops to 0 after quitting `mpv`

With 0.35.0 and 0.34.1 `coreaudiod` CPU use drops to zero when playback is paused.

<details>
<summary><b>CPU usage:</b></summary>

```bash
low-batt@gag ~$ while true; do ps -e -o 'args,%cpu,cputime' | grep 'coreaudiod\|mpv' | grep -v grep; sleep 5; done
/usr/sbin/coreaudiod                                               0.0  25:03.81
/usr/sbin/coreaudiod                                               0.0  25:03.81
/usr/sbin/coreaudiod                                              11.2  25:04.21
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M  28.5   0:00.87
/usr/sbin/coreaudiod                                              11.2  25:04.80
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M  18.7   0:01.85
/usr/sbin/coreaudiod                                              10.5  25:05.41
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M  18.7   0:02.87
/usr/sbin/coreaudiod                                              10.2  25:05.97
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M  33.6   0:03.96
/usr/sbin/coreaudiod                                              13.2  25:06.60
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M   0.4   0:04.29
/usr/sbin/coreaudiod                                              13.0  25:07.26
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M   0.3   0:04.33
/usr/sbin/coreaudiod                                              13.8  25:07.94
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M   0.6   0:04.36
/usr/sbin/coreaudiod                                              13.5  25:08.60
./mpv/build/mpv --log-file=mpv.log --no-config /Users/low-batt/M   0.7   0:04.40
/usr/sbin/coreaudiod                                               0.0  25:08.82
/usr/sbin/coreaudiod                                               0.0  25:08.82
/usr/sbin/coreaudiod                                               0.0  25:08.82
^C
low-batt@gag ~$ 
```
</details>

This is how I ran `mpv` for the test:
```bash
low-batt@gag mpv-build (master %=)$ ./mpv/build/mpv --log-file=mpv.log --no-config ~/Movies/Airplaneski.mp4 
 (+) Video --vid=1 (*) (h264 682x438 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 682x438 => 683x438 yuv420p
(Paused) AV: 00:00:19 / 01:11:53 (0%) A-V:  0.000

Exiting... (Quit)
low-batt@gag mpv-build (master %=)$ 
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/11304478/mpv.log)

### Sample files

The issue is not sensitive to the video being played other than it _must_ have an audio track.

### PR DESCRIPTION
**Pull request by low-batt**
Commit 39f7f83 changed ao_driver.reset to use AudioUnitReset instead of AudioOutputUnitStop. The problem with calling AudioOutputUnitStop was that AudioOutputUnitStart takes a significant amount of time after a stop when a wireless audio device is being used. This resulted in lagging that was noticeable to users during seeking and short pause/resume cycles. Switching to AudioUnitReset eliminated this lagging.

However with the switch to AudioUnitReset the macOS daemon coreaudiod continued to consume CPU time and did not release a powerd assertion that it created on behalf of mpv, preventing macOS from sleeping.

This commit will change ao_coreaudio.reset to call AudioOutputUnitStop after a delay if playback has not resumed. This preserves the faster restart of playback for seeking and short pause/resume cycles and avoids preventing sleep and needless CPU consumption.

Fixes #11617

The code changes were authored by @orion1vi and @lhc70000.

### CODE REVIEW

**Comment by low-batt** [comment]
This is the replacement pull request for PR #11667.

@Akemi If there is anything you don't like and want changed do not hesitate to ask. I am happy to update as needed.

I did not change the code at all other than to add a couple of comments. I am worried about the switch from synchronous to asynchronous in the `reset` and `stop` methods as I mentioned in the other PR. If these operations need to be synchronous, let me know and I will correct them.

File: audio/out/ao_coreaudio.c [hunk 1]
```diff
@@ -320,24 +332,89 @@ static bool init_audiounit(struct ao *ao, AudioStreamBasicDescription asbd)
...
+    // after a delay if it remains idle.
+    stop_after_idle_time(ao);
 }
 
-static void start(struct ao *ao)
+static void reset(struct ao *ao)
+{
+    struct priv *p = ao->priv;
+    // Must dispatch to serialize reset, start and stop operations.
+    dispatch_async_f(p->queue, ao, &_reset);
```
Comment (low-batt) [inline audio/out/ao_coreaudio.c:387]: Does the calling code expect the operation to be completed when this method returns? If so, then this needs to be changed to `dispatch_sync_f`.

File: audio/out/ao_coreaudio.c [hunk 2]
```diff
@@ -320,24 +332,89 @@ static bool init_audiounit(struct ao *ao, AudioStreamBasicDescription asbd)
...
+
     OSStatus err = AudioOutputUnitStart(p->audio_unit);
     CHECK_CA_WARN("can't start audio unit");
 }
 
+static void start(struct ao *ao)
+{
+    struct priv *p = ao->priv;
+    // Must dispatch to serialize reset, start and stop operations.
+    dispatch_async_f(p->queue, ao, &_start);
```
Comment (low-batt) [inline audio/out/ao_coreaudio.c:406]: Does the calling code expect the operation to be completed when this method returns? If so, then this needs to be changed to `dispatch_sync_f`.

File: audio/out/ao_coreaudio.c (hunk 1 above)
Comment (Akemi) [reply audio/out/ao_coreaudio.c:387]: i am not sure about the expectations, though i would keep it sync since that's how it 'worked' before and in other AOs.

**Comment by Akemi** [comment]
besides my comment about keeping it in sync, i think this is good to go.

File: audio/out/ao_coreaudio.c (hunk 1 above)
Comment (low-batt) [reply audio/out/ao_coreaudio.c]: Both `reset` and `start` have been changed to use `dispatch_sync_f`.

File: audio/out/ao_coreaudio.c (hunk 2 above)
Comment (low-batt) [reply audio/out/ao_coreaudio.c]: Both `reset` and `start` have been changed to use `dispatch_sync_f`.

**Comment by low-batt** [comment]
I have updated the commit to use `dispatch_sync_f` in `reset` and `start`.

I was very tempted to make that change when preparing the PR, but as I do not know the macOS audio APIs I was concerned this might be some sort of event driven interface and I would be undoing some sort of improvement.

**Comment by Akemi** [comment]
thank you all @low-batt, @lhc70000 and @orion1vi, for the work on those changes and all the analysing you did on the related issues/PRs.

and sorry again i am taking so long with reviewing those changes and going through the accumulated issues and PRs.
