### PR TITLE
osc: scale rendered aspect ratio with window aspect ratio

### LINKED ISSUE #10710: Logo is disproportional
### Important Information
- mpv version:  This issue first appeared in `20220925-git-56e24d5`, and has existed ever since. Current latest is `20221002-git-2207236`
- Platform and Version: Windows 11 x64
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps
Start mpv without any config. 

### Expected behavior
The center logo should be proportional, regardless of the windows size. See the screenshot taken from `20220918-git-ba81e4e`.

### Actual behavior
The center logo is disproportional - see below. And it will change according to the windows size. For example, if I press `f` and go into the full-screen mode (16:9), the logo is proportional again.

### Log file
N/A

### Sample files
N/A

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Should behave pretty much the same as it used to, but the logo stays centered better and it doesn't distort anymore, which was caused by a recent change in libass https://github.com/libass/libass/pull/645.

Has been tested with the latest libass release 0.16.0 and with their latest master commit https://github.com/libass/libass/commit/44f6532daf5eb13cb1aa95f5449a77b5df1dd85b

Closes #10710

### CODE REVIEW

File: player/lua/osc.lua [hunk 1]
```diff
@@ -2585,7 +2585,11 @@ function tick()
 
         -- render idle message
         msg.trace("idle message")
-        local icon_x, icon_y = 320 - 26, 140
+        local _, _, display_aspect = mp.get_osd_size()
+        local display_h = 360
+        local display_w = display_h * display_aspect
+        -- logo is rendered at 2^(6-1) = 32 times resolution with size 1800x1800
+        local icon_x, icon_y = (display_w - 1800 / 32) / 2, 140
```
Comment (thebombzen) [inline player/lua/osc.lua:2592]: This changes the location, because 1800/64 is ~28, not 26. Was the previous location incorrect?

Comment (christoph-heinrich) [reply player/lua/osc.lua:2592]: It was not perfectly centered (I checked in a screenshot)

**Comment by thebombzen** [comment]
In that case, LGTM

**Comment by christoph-heinrich** [comment]
And that has been happening since this PR got merged?

**Comment by Obegg** [comment]
> And that has been happening with this PR but not without it?
>
Yes.

> If so, it would be very helpful If you could try out this patch and then report what it writes out.
>
I have no idea how to use it.
I use this https://github.com/shinchiro/mpv-winbuild-cmake

**Comment by christoph-heinrich** [comment]
A recent issue in uosc revealed that height and width may sometimes report an initial value of 0 and I'm pretty sure that's what causes your issue.
We could certainly check for that, but I don't know how it should behave in such a case.
