### PR TITLE
vd_lavc: try other hwdecs when falling back after an hwdec failure 

### LINKED ISSUE #11865: hwdec fallback failure
### Important Information

Provide following Information:
- [mpv version](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230630/mpv-x86_64-v3-20230630-git-40a1b00.7z)
- Windows Version 
  23H2
- If known which version of mpv introduced the problem
  N/A
- Possible screenshot or video of visual glitches
  N/A

### Reproduction steps
Requires a Vulkan device that does not support `VK_MESA_video_decode_av1` (NVIDIA RTX3070 LP Windows DCH Driver)

`mpv --no-config --vo=gpu-next --hwdec=vulkan,nvdec --msg-level=vd=trace --gpu-context=winvk AV1_Video.mkv`

### Expected behavior
```
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     libvpx-vp9 (vp9) - libvpx VP9
[vd]     vp9_cuvid (vp9) - Nvidia CUVID VP9 decoder
[vd]     vp9_qsv (vp9) - VP9 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder vp9
[vd] Looking at hwdec vp9-nvdec...
[vd] Trying hardware decoding via vp9-nvdec.
[vd] Selected codec: vp9 (Google VP9)
[vd] Pixel formats supported by decoder: dxva2_vld d3d11va_vld d3d11 cuda yuv420p10le
[vd] Codec profile: Profile 2 (0x2)
[vd] Requesting pixfmt 'cuda' from decoder.
Using hardware decoding (nvdec).
```
The av1 video should fall back to nvdec just like the vp9 video
### Actual behavior
```
[vd] Codec list:
[vd]     libdav1d (av1) - dav1d AV1 decoder by VideoLAN
[vd]     av1 - Alliance for Open Media AV1
[vd]     av1_cuvid (av1) - Nvidia CUVID AV1 decoder
[vd]     av1_qsv (av1) - AV1 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder libdav1d
[vd] Looking at hwdec av1-vulkan...
[vd] Trying hardware decoding via av1-vulkan.
[vd] Using underlying hw-decoder 'av1'
[vd] Selected codec: libdav1d (dav1d AV1 decoder by VideoLAN)
[vd] Pixel formats supported by decoder: dxva2_vld d3d11va_vld d3d11 cuda vulkan yuv420p10le
[vd] Codec profile: Main (0x0)
[ffmpeg/video] av1: Device does not support decoding av1!
[vd] Hardware decoding of this stream is unsupported?
[vd] Requesting pixfmt 'yuv420p10le' from decoder.
[ffmpeg/video] av1: Your platform doesn't support hardware accelerated AV1 decoding.
[ffmpeg/video] av1: Failed to get pixel format.
Error while decoding frame (hardware decoding)!
[vd] Falling back to software decoding.
```
This bug should be reproduced on any Vulkan GPU that does not support `VK_MESA_video_decode_av1`
### Log file

N/A

### Sample files

N/A

### PR DESCRIPTION
**Pull request by philipl**
Today, if hwdec initialisation succeeds, we move on to attempting
decoding, and if decoding fails, we enter a fallback path that will
only do software decoding.

This is suboptimal because some hwdecs and codec combinations can
pass hwdec init, but then fail at hwaccel init, or even frame decoding.
In these situations, we will never attempt other hwdecs in the `auto`
or manually specified lists which might work.

One good example is someone tries to use `vulkan,auto` and tries to
play av1 content. The vulkan decoding will fail at hwaccel init time,
and then fallback to software instead of going through the auto list
which would allow vaapi, nvdec, etc to play the file.

Instead, let's not give up immediately, and try the next hwdec after
a failure, just like we do if hwdec init fails.

The key part of this change is to keep track of the hwdecs we have
tried, so that each time we run through hwdec selection, we don't try
the same one over and over again. If we really get through the whole
list with no success, we will then fall back to software decoding.

Fixes #11865

### CODE REVIEW

**Comment by sfan5** [comment]
will also fix https://github.com/mpv-android/mpv-android/issues/670

File: video/decode/vd_lavc.c [hunk 1]
```diff
@@ -247,6 +248,9 @@ const struct autoprobe_info hwdec_autoprobe_info[] = {
     {"mediacodec-copy", HWDEC_FLAG_AUTO | HWDEC_FLAG_WHITELIST},
     {"videotoolbox",    HWDEC_FLAG_AUTO | HWDEC_FLAG_WHITELIST},
     {"videotoolbox-copy", HWDEC_FLAG_AUTO | HWDEC_FLAG_WHITELIST},
+    {"cuda",            HWDEC_FLAG_DENYLIST },
+    {"cuda-copy",       HWDEC_FLAG_DENYLIST },
+    {"v4l2m2m-copy",    HWDEC_FLAG_DENYLIST },
```
Comment (sfan5) [inline video/decode/vd_lavc.c:255]: should we really do this when the docs are pretty clear that people should use `auto-safe`?

also v4l2m2m-copy doesn't "prevent playback fromhappening at all" on my system

Comment (philipl) [reply video/decode/vd_lavc.c:255]: On my machine (normal desktop), trying to use v4l2m2m-copy resulted in the stream abruptly hitting EOF.

But yes, I discussed this in the commit description (I guess I should have copied it to the PR description). We'd need to change Ctrl+h to use `auto-safe` by default.

**Comment by philipl** [comment]
I've added a commit to switch ctrl+h to `auto-safe`

File: video/decode/vd_lavc.c [hunk 2]
```diff
@@ -485,6 +489,15 @@ static void select_and_set_hwdec(struct mp_filter *vd)
 
         if (!hwdec_requested) {
             MP_VERBOSE(vd, "No hardware decoding requested.\n");
+            /*
+             * Reset attempted hwdecs so that if the hwdec list is reconfigured
+             * we attempts all of them from the beginning. The most practical
+             * reason for this is that Ctrl+h toggles between `no` and `auto`,
+             * and we want `auto` to reevaluate from a clean slate each time.
```
Comment (N-R-K) [inline video/decode/vd_lavc.c:496]: These probably should be updated to `auto-safe` as well.

**Review by N-R-K — CHANGES_REQUESTED** [review]

File: video/decode/vd_lavc.c (hunk 2 above)
Comment (philipl) [reply video/decode/vd_lavc.c]: Fixed.

File: DOCS/man/options.rst [hunk 3]
```diff
@@ -1200,7 +1200,7 @@ Video
     .. note::
 
         Use the ``Ctrl+h`` shortcut to toggle hardware decoding at runtime. It
-        toggles this option between ``auto`` and ``no``.
+        toggles this option between ``auto-safe`` and ``no``.
```
Comment (kasper93) [inline DOCS/man/options.rst:1203]: Wouldn't it be better to actually toggle on user settings between `hwdec` and `no`? 

It is always strange to start with some hwdec and after toggling ctrl+h end up with a different one.

File: DOCS/man/options.rst [hunk 4]
```diff
@@ -1248,9 +1248,9 @@ Video
     special values:
 
     :no:        always use software decoding (default)
+    :auto-safe: enable any whitelisted hw decoder (see below)
     :auto:      forcibly enable any hw decoder found (see below)
     :yes:       exactly the same as ``auto``
```
Comment (sfan5) [inline DOCS/man/options.rst:1253]: should "yes" be changed to mean auto-safe too?

**Comment by philipl** [comment]
> `--hwdec=vulkan,qsv-copy` hevc scc profile video does not seem to fall back to qsv-copy correctly Currently only Intel Gen12 + QSV/VA-API can decode such videos (even SW decoder does not exist)

It doesn't fall back because it doesn't return any errors. It appears to be like the current linux ANV behaviour where it will accept any profile or bit depth and then spit out garbage. So that's a driver bug.

File: DOCS/man/options.rst (hunk 3 above)
Comment (philipl) [reply DOCS/man/options.rst:1203]: As I discussed elsewhere, this would require a change to how configuration works - You can't toggle between `hwdec` and `no` because ctrl+h rewrites `hwdec`, so we'd need to add a new config option for "the hwdec list to use with ctrl+h". 

Which is doable, but I'm not bundling it in here.

File: DOCS/man/options.rst (hunk 4 above)
Comment (philipl) [reply DOCS/man/options.rst:1253]: It's something of a configuration compatibility break, although I think it's a reasonable thing to do, so that's why I didn't change it, but happy to do so.

File: DOCS/man/options.rst (hunk 3 above)
Comment (kasper93) [reply DOCS/man/options.rst:1203]: I don't think you need 2nd config option for that. ctrl+h could simply remember current hwdec when toggling and restore it on next toggle. I haven't look into details, but with one more state variable it should be doable. But fair, it can be done in different PR in the future.

File: DOCS/man/options.rst (hunk 4 above)
Comment (philipl) [reply DOCS/man/options.rst]: Added another commit for this.

File: video/decode/vd_lavc.c [hunk 5]
```diff
@@ -475,16 +479,25 @@ static void select_and_set_hwdec(struct mp_filter *vd)
...
+                            bstr_equals0(opt, "yes");
         bool hwdec_auto_copy = bstr_equals0(opt, "auto-copy") ||
                             bstr_equals0(opt, "auto-copy-safe");
         bool hwdec_auto = hwdec_auto_all || hwdec_auto_copy || hwdec_auto_safe;
 
         if (!hwdec_requested) {
             MP_VERBOSE(vd, "No hardware decoding requested.\n");
+            /*
+             * Reset attempted hwdecs so that if the hwdec list is reconfigured
+             * we attempts all of them from the beginning. The most practical
```
Comment (sfan5) [inline video/decode/vd_lavc.c:494]: attempt*

File: video/decode/vd_lavc.c [hunk 6]
```diff
@@ -475,16 +479,25 @@ static void select_and_set_hwdec(struct mp_filter *vd)
...
+             * reason for this is that ctrl+h toggles between `no` and
+             * `auto-safe`, and we want to reevaluate from a clean slate each time.
+             */
+            TA_FREEP(&ctx->attempted_hwdecs);
+            ctx->num_attempted_hwdecs = 0;
+            ctx->hwdec_notified = false;
```
Comment (sfan5) [inline video/decode/vd_lavc.c:500]: this probably needs to be changed in a way that vd_lavc is notified if the `hwdec` option changes

Comment (philipl) [reply video/decode/vd_lavc.c:500]: Yes. I've moved this logic into `reinit`, which is called whenever the config option changes value. Should address @arm64-v9a 's report.

**Review by sfan5 — APPROVED** [review]
