### PR TITLE
video/image_writer: use image->params.repr to determine depth

### LINKED ISSUE #16398: Screenshot With JPEG XL Format Results in 16 Bit Depth Even the Original Video is 10 Bit Depth
### mpv Information

```bash
mpv v0.40.0-119-g1d1535ff9 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on May 23 2025 00:13:48
libplacebo version: v7.351.0 (v7.351.0-dirty)
FFmpeg version: N-119684-g670089304
FFmpeg library versions:
   libavcodec      62.3.101
   libavdevice     62.0.100
   libavfilter     11.0.100
   libavformat     62.0.102
   libavutil       60.3.100
   libswresample   6.0.100
   libswscale      9.0.100
```

### Other Information

```text
- Windows version:Windows 11 24H2 (10.0.26100.1150)
- Source of mpv:[https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/)
```

### Reproduction Steps

Set screenshot format to JPEG XL (screenshot-format=jxl in mpv.conf) and then screenshot a 10 bit video  with the ‘s’ key

### Expected Behavior

Screenshot image is 10 bit depth.

### Actual Behavior

Screenshot image is 16 bit depth.

### Log File

[output.txt](https://github.com/user-attachments/files/20515381/output.txt)

### Sample Files

[\[Nekomoe kissaten&LoliHouse\] Zatsu Tabi - 08 \[WebRip 1080p HEVC-10bit AAC ASSx2\].mkv @00_00_04.jxl.zip](https://github.com/user-attachments/files/20515392/Nekomoe.kissaten.LoliHouse.Zatsu.Tabi.-.08.WebRip.1080p.HEVC-10bit.AAC.ASSx2.mkv.%4000_00_04.jxl.zip)

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

### PR DESCRIPTION
**Pull request by Traneptora**
The previous method used in 2b38b382cf doesn't properly determine the original depth. We use image->params.repr.bits.color_depth to determine that now.

Fixes #16398.

### CODE REVIEW

File: video/image_writer.c [hunk 1]
```diff
@@ -188,13 +188,14 @@ static bool write_lavc(struct image_writer_ctx *ctx, mp_image_t *image, FILE *fp
...
      */
-    if (memcmp(image->fmt.bpp, ctx->original_format.bpp, sizeof(image->fmt.bpp))) {
-        int depth = 0;
-        for (int i = 0; i < MP_ARRAY_SIZE(ctx->original_format.comps); i++)
-            depth = MPMAX(depth, ctx->original_format.comps[i].size);
-        MP_DBG(ctx, "tagging bits_per_raw_sample=%d\n", depth);
-        avctx->bits_per_raw_sample = depth;
+    if (image->params.repr.bits.color_depth != image->params.repr.bits.sample_depth) {
+        MP_DBG(ctx, "tagging bits_per_raw_sample=%d\n", image->params.repr.bits.color_depth);
+        avctx->bits_per_raw_sample = image->params.repr.bits.color_depth;
```
Comment (kasper93) [inline video/image_writer.c:198]: What happens for format that have non-zero `bit_shift`?

Generally patch make sense.

Comment (Traneptora) [reply video/image_writer.c:198]: I haven't been able to test that. Can you provide an example pixel format that I could test that with (ideally something I can generate with lavfi)?
