### PR TITLE
wayland: obey initial size hints set by the compositor

### LINKED ISSUE #11134: Resizing through KDE window rules does not work
### Important Information

Provide following Information:
- mpv version: 0.35.0
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: community/mpv package from standard arch repository
- ~~If known which version of mpv introduced the problem~~
- Window Manager and version: kwin 5.26.5 (wayland)
- GPU driver and version: Mesa 22.3.2 (vegam, LLVM 14.0.6, DRM 3.49, 6.1.4-zen2-1-zen)
- ~~Possible screenshot or video of visual glitches~~

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I am trying to place window at specific place and resize it.

Here's screenshot of window rules I use:
image

### Expected behavior

Window placed at specified position and has requested size.

### Actual behavior

Window placed in the right place but window size isn't updated.

If I use kwin debug console (`qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole`), I see `clientSize 960x540` and `bufferGeometry 2560,1523 960x540` which isn't right.

I filed issue [in KDE bugtracket](https://bugs.kde.org/show_bug.cgi?id=453374#c7) first (don't mind unrelated topic, there's still discussion about MPV) and KDE developer said that this is MPV issue:
> position window rule works, but the size window rule does not. kwin asks mpv to show itself with the given size, but mpv ignores that and attaches a buffer with different size anyway. Can't fix it in kwin, please report this issue to mpv developers.

### Log file

[mpv3.txt](https://github.com/mpv-player/mpv/files/10403536/mpv3.txt) - log with WAYLAND_DEBUG=1
[mpv2.txt](https://github.com/mpv-player/mpv/files/10403548/mpv2.txt) - regular log

### Sample files

~~Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.~~

### PR DESCRIPTION
**Pull request by Dudemanguy**
In the past, this worked by accident because the initial startup was racy and sometimes the initial firing of handle_toplevel_config would happen after reconfig. Since we now properly wait on all compositor events we can save the initial size hint that is given to us and try to use that as the window-size/geometry provided the --autofit/geometry options aren't explictly set. Fixes #11134.

Extracted from #12260.

### CODE REVIEW

File: video/out/wayland_common.c [hunk 1]
```diff
@@ -894,9 +894,17 @@ static void handle_toplevel_config(void *data, struct xdg_toplevel *toplevel,
     wl->toplevel_width = width;
     wl->toplevel_height = height;
 
-    /* Don't do anything here if we haven't finished setting geometry. */
-    if (mp_rect_w(wl->geometry) == 0 || mp_rect_h(wl->geometry) == 0)
+    if ((mp_rect_w(wl->geometry) == 0 || mp_rect_h(wl->geometry) == 0)) {
```
Comment (kasper93) [inline video/out/wayland_common.c:897]: nit, but those additional parens are not needed, no?

Comment (Dudemanguy) [reply video/out/wayland_common.c:897]: Not sure where those crept in from.
