### PR TITLE
egl_helpers: fix create_context fallback behavior

### LINKED ISSUE #5915: --opengl-es=auto does not attempt to use OpenGL ES
Somewhat related to #5903 

### mpv version and platform

mpv 0.28.2
Arch Linux x86_64

```
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May 14 09:49:30 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0
```

### Reproduction steps

Have an old computer which supports only really old OpenGL versions (in my case, OpenGL 1.4 and OpenGL ES 2.0)
**OR**
(if you use mesa) Use the `MESA_GL_VERSION_OVERRIDE` and `MESA_GLES_VERSION_OVERRIDE` environment variables to change reported OpenGL(ES) versions
**THEN**
Play videos with `--vo=gpu --gpu-api=opengl --opengl-es=(yes/no/auto)`

### Expected behavior

When video is played with `--opengl-es=auto`, mpv detects the system's OpenGL and OpenGL ES versions, and makes a decision whether to use one or the other based on the versions. (e.g. if OpenGL <2.1 but OpenGL ES =2.0, OpenGL ES is selected)

When video is played with `--opengl-es=(yes/no)`, then OpenGL ES is forced or disabled appropriately.

### Actual behavior

When `--opengl-es=auto` is used and OpenGL is _available_ (not necessarily usable), then mpv only tries to use it, and errors when the OpenGL version is insufficient. No attempt is made to use OpenGL ES.

When `--opengl-es=yes` is used and OpenGL (not ES) is _usable_, then OpenGL is used, not OpenGL ES.

### Log file

`mpv --vo=gpu --gpu-api=opengl --opengl-es=auto` https://0x0.st/s_U0.txt

In this one I use environment variables to force mesa to accept OpenGL 2.1 contexts, even if they aren't supported by the hardware, and to reject OpenGL ES contexts newer than 1.0.
`MESA_GL_VERSION_OVERRIDE=2.1 MESA_GLES_VERSION_OVERRIDE=1.0 mpv --vo=gpu --gpu-api=opengl --opengl-es=yes` https://0x0.st/s_Uk.txt

### Sample files

Happens with every file I tried so far, so I'm fairly sure I don't need to upload samples.

### PR DESCRIPTION
**Pull request by Dudemanguy**
The EGL stuff is really complicated because of historical reasons
(tl;dr: blame EGL). There was one edge case with EGL context creation
that lead to incorrect behavior. EGL_KHR_create_context was created with
EGL 1.4 (which mpv does support) but it is still possible for an EGL 1.4
device to not implement this extension. That means that none of the EGL
attrs that pass a specific opengl version work. So for this obscure
case, there is a fallback context creation at the very end which simply
creates an EGLContext without passing any special attrs.

This has another problem however. mpv has a hard requirement on at least
desktop opengl 2.1 or opengl ES 2.0 to function (we're not asking for
much here). Since the fallback EGL context creation has no version
checking, it is entirely possible to create an EGL context with a
desktop opengl version under 2.1. As you get further along in the code,
the user will encounter the hard opengl version check and then error
out. However, we're supposed to also actually check if GLES works
(that's what the opengl-es=auto option is for) so this is a bug.

The fix is to do a bit of code duplication and make a mpgl_check_version
specifically for if we hit the edge case of needing to create an EGL
context without the EGL_KHR_create_context extension. Grab the version
with the function pointer, check if it's under 210, if so destroy the
EGL context and set it to NULL. After that, if the user has set
opengl-es to auto, mpv will try GLES next. If it is set to no, then mpv
will simply fail as desired. Fixes #5915.

Sidenote: the ra_gl_ctx_test_version originally testing 140 doesn't make
any sense. Passing the version number in that function only does
something if the user has set opengl-restrict. What we need to do is to
pass the version of the created context to that function. If the version
is higher than the opengl-restrict option, then make this a failure.

### CODE REVIEW

File: video/out/opengl/egl_helpers.c [hunk 1]
```diff
@@ -78,6 +78,20 @@ static void dump_egl_config(struct mp_log *log, int msgl, EGLDisplay display,
...
+{
+    void *p = eglGetProcAddress(name);
+#if defined(__GLIBC__) && HAVE_LIBDL
+    // Some crappy ARM/Linux things do not provide EGL 1.5, so above call does
+    // not necessarily return function pointers for core functions. Try to get
+    // them from a loaded GLES lib. As POSIX leaves RTLD_DEFAULT "reserved",
+    // use it only with glibc.
+    if (!p)
+        p = dlsym(RTLD_DEFAULT, name);
+#endif
```
Comment (evelikov) [inline video/out/opengl/egl_helpers.c:91]: Since you're moving this, might as well make it more useful.
 - the rant doesn't help much document what's happening - see an example from another project below
 - kill off the unused ctx argument
```
   - Mali drivers on EGL 1.4 expose GL API statically from
     libGLESv2 but not dynamically from eglGetProcAddress. The EGL 1.4 spec
     permits this behavior.
    - EGL 1.5 requires that eglGetStringi be exposed dynamically through
      eglGetProcAddress. Exposing statically with dlsym is optional.
   - Mesa drivers expose GL API statically from libGL and libGLESv2
     and dynamically from eglGetProcAddress and glxGetProcAddress.
```

**Comment by evelikov** [comment]
Note that despite the suggestion, the commit itself is correct and should fix the mentioned bug.

Albeit the GLES handling should be simplified by constructing appropriate `es[]` array in `mpegl_create_context_cb()` and removing the GLES checking from `ra_gl_ctx_test_version()`... Bth this is just an idea.

File: video/out/opengl/egl_helpers.c (hunk 1 above)
Comment (Dudemanguy) [reply video/out/opengl/egl_helpers.c:91]: I didn't originally write this. ;) I think the void *ctx is used with the function pointer stuff in `opengl/common.c`, so it can't be removed.

Comment (evelikov) [reply video/out/opengl/egl_helpers.c:91]: Yup, perfectly aware you didn't write the original. Looking at the `opengl/common.c` code - seems like the most convoluted GL handling out there. As said originally it's a suggestion - feel free to take it or leave it. 
 https://github.com/mpv-player/mpv/blob/8a5e3d194b25471b540bfaca7c4c2b1707ba37ae/video/out/opengl/common.c#L680
