### PR TITLE
vo_gpu: hwdec: load hwdec interops on-demand by default

### LINKED ISSUE #8765: Option to disable cuda-nvdec when no CUDA device present
### Important Information

Provide following Information:
- mpv version: 0.33.1
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: Archlinux repository
- Window Manager and version: sway 0.16 
- GPU driver and version: Intel Tiger Lake, Mesa 21.0

### Reproduction steps

1. Have a device with CUDA installed, but no Nvidia GPU present and a device that supports hwdec=vaapi
2. Launch mpv on any video with hwdec=vaapi.

### Expected behavior
Video plays instantly using the device that supports vaapi. 

### Actual behavior
Video starts playing using the vaapi device after a delay of 10 seconds. Log shows that it gets stuck trying to initialize cuda-nvdec.

### Log file

https://0x0.st/-mPB.txt

### LINKED ISSUE #9691: mpv shouldn't complain about missing libcuda.so.1
* mpv version: 0.34.1
* Linux Distribution: Debian testing.
*  Source of the mpv binary: Debian testing repo.
* Window Manager and version: KDE Plasma 5.23.5
* GPU driver and version: AMD, Mesa 21.3.3

Every time I run mpv it complains about missing libcuda.so.1:

```
Cannot load libcuda.so.1
```

This looks like noise, especially since CUDA is Nvidia only. Can you please remove this error message when it's not relevant?

### PR DESCRIPTION
**Pull request by philipl**
Historically, we have treated hwdec interop loading as a completely
separate step from loading the hwdecs themselves. Some hwdecs need an
interop, and some don't, and users generally configure the exact
hwdec they want, so interops that aren't relevant for that hwdec
shouldn't be loaded to save time and avoid warning/error spam.

The basic approach here is to recognise that interops are tied to
hwdecs by imgfmt. The hwdec outputs some format, and an interop is
needed to get that format to the vo without read back.

So, when we try to load an hwdec, instead of just blindly loading all
interops as we do today, let's pass the imgfmt in and only load
interops that work for that format. If more than one interop is
available for the format, the existing logic (whatever it is) will
continue to be used to pick one.

We also have one callsite in filters where we seem to pre-emptively
load all the interops. It's probably possible to trace down a specific
format but for now I'm just letting it keep loading all of them; it's
no worse than before.

You may notice there is no documentation update - and that's because
the current docs say that when the interop mode is `auto`, the interop
is loaded on demand. So reality now reflects the docs. How nice.

Fixes #8765
Fixes #9691

### CODE REVIEW

File: video/hwdec.h [hunk 1]
```diff
@@ -55,11 +55,11 @@ void hwdec_devices_remove(struct mp_hwdec_devices *devs, struct mp_hwdec_ctx *ct
 // If used at all, this must be set/unset during initialization/uninitialization,
 // as concurrent use with hwdec_devices_request() is a race condition.
 void hwdec_devices_set_loader(struct mp_hwdec_devices *devs,
-    void (*load_api)(void *ctx), void *load_api_ctx);
+    void (*load_api)(void *ctx, int imgfmt), void *load_api_ctx);
 
 // Cause VO to lazily load all devices, and will block until this is done (even
```
Comment (jeeb) [inline video/hwdec.h:60]: "to lazily load all devices for a specific hardware IMGFMT" or so?

Comment (jeeb) [reply video/hwdec.h:60]: Also mentioning IMGFMT_NONE as "all" instead of "no limitations" might be a good idea.

File: video/out/gpu/video.c [hunk 2]
```diff
@@ -4360,11 +4369,49 @@ void gl_video_load_hwdecs(struct gl_video *p, struct mp_hwdec_devices *devs,
...
-void gl_video_load_hwdecs_all(struct gl_video *p, struct mp_hwdec_devices *devs)
+void gl_video_load_hwdecs_for_img_fmt(struct gl_video *p,
+                                      struct mp_hwdec_devices *devs,
+                                      int imgfmt)
 {
-    if (!p->hwdec_interop_loading_done) {
-        for (int n = 0; ra_hwdec_drivers[n]; n++)
-            load_add_hwdec(p, devs, ra_hwdec_drivers[n], true);
-        p->hwdec_interop_loading_done = true;
+    if (p->hwdec_interop_loading_done) {
```
Comment (jeeb) [inline video/out/gpu/video.c:4376]: I am not sure if this is a real case we have to think about, but what if the function gets called, but with a different imgfmt (from specific to none or from one specific to another would be the two cases that pop to my mind) ?

If switching of the imgfmt may only happen in case the whole gl_video gets reset, then just having a single boolean is fine. If we could have more and more things getting loaded with various calls, then just boolean would not be sufficient and we'd either have to have a bitmask or an array of bools...

Comment (philipl) [reply video/out/gpu/video.c:4376]: I respected this boolean because if it's set, we know we loaded all interops. But if it's not set, we have a separate check for each individual interop to only load it if it's not already been loaded. So we can move between interops safely and also work correctly after a load_all happens.

File: filters/filter.c [hunk 3]
```diff
@@ -688,7 +689,7 @@ struct AVBufferRef *mp_filter_load_hwdec_device(struct mp_filter *f, int avtype)
     if (!info || !info->hwdec_devs)
         return NULL;
 
-    hwdec_devices_request_all(info->hwdec_devs);
+    hwdec_devices_request_for_img_fmt(info->hwdec_devs, IMGFMT_NONE);
```
[the remark this answers is not in the document]
Comment (philipl) [reply filters/filter.c]: Good call. I've added it, as it's simple enough.

**Comment by philipl** [comment]
Updated to ensure we check for already loaded hwdecs in all scenarios.

**Review by jeeb — APPROVED** [review]
Generally looks good now.

`gl_video_load_hwdecs` still has the original interpretation of what `hwdec_interop_loading_done` means, but that just leads to a difference if a specific interop is selected. or if all interops are disabled with `"no"`.

**Comment by philipl** [comment]
Thanks, I'll tweak that to make it more consistent.

**Comment by jeeb** [comment]
Finished my testing with:

1. `vo_libmpv` (macOS), which is the only one calling `gl_video_load_hwdecs` with `load_all_by_default` set to true.
   `mpv --no-config --hwdec=videotoolbox FILE`
2. `d3d11va` with `d3d11vp` (just to test one of the VPP filter usages).
    `mpv -v --no-config --hwdec=d3d11va --vf=d3d11vpp --hwdec-codecs=mpeg2video random_broadcast.ts`

Both seem to work :)

**Comment by jeeb** [comment]
> Thanks, I'll tweak that to make it more consistent.

For the record, I'm not sure if the inconsistency is a problem, since it just makes sure that what gets loaded by VO preinit (at least with the GPU and libmpv VOs) is then all that gets loaded.

Just thought it was worth bringing up as a difference, though.

**Comment by philipl** [comment]
> > Thanks, I'll tweak that to make it more consistent.
> 
> For the record, I'm not sure if the inconsistency is a problem, since it just makes sure that what gets loaded by VO preinit (at least with the GPU and libmpv VOs) is then all that gets loaded in case an interop is specified or set to no.
> 
> Just thought it was worth bringing up as a difference, though.

True. I can document the behaviour more clearly if nothing else.
