### PR TITLE
sd_ass: fix converted subtitles having too-wide borders

### LINKED ISSUE #11825: Subtitle border stretched horizontally (regression?)
### Important Information

Provide following Information:
- mpv version
mpv 0.35.0-445-g650c53df

- Platform and Version
Windows 10 x64

- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps

1. Download the [0.34.0-230-g7ac4b7dfe7](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220313-git-7ac4b7d.7z/download) build, download the latest build.
2. Play the video in the latest version until the subtitle line appears, pause.
3. Play the video in the older version until the subtitle line appears, pause.
4. Compare the output.

Reproducible with no-config. I did not check when exactly the regression happened, it's just the build I happened to check.

### Expected behavior

Border is rendered evenly in both directions.

### Actual behavior

mpv currently stretches the border horizontally, regardless of the settings (at least border/shadow related).

### Log file

Old version: https://0x0.st/HQ8T.txt
New version: https://0x0.st/HQ8c.txt

### Sample files

https://0x0.st/HQ8b.mkv

### PR DESCRIPTION
**Pull request by llyyr**
We internally convert SRT to ASS and render them with libass, however as of libass 0.17.0, the text shadows and borders scale in the x-axis, while they previously did not. This means naively setting PlayRes{X,Y} to be 4:3 will result in stretched shadows and borders in the x-axis. Fix this by setting PlayResX = (PlayResY * DAR).

Fixes #11825

### CODE REVIEW

**Comment by avih** [comment]
After some discussion with the libass guys, here's the same commit but with modified commit message, and code comment:
```diff
From b4fcf0d092f103a18b23103ebf9d6e30f2652e4b Mon Sep 17 00:00:00 2001
From: llyyr <llyyr.public@gmail.com>
Date: Sun, 25 Jun 2023 06:10:25 +0530
Subject: [PATCH] sd_ass: srt subs: fix too-wide border with libass 0.17

Libass commit f08f8ea5 (between 0.16 and 0.17) changed how PlayerResX
affects some aspects of rendering.

The libass change fixes a VSFilter compatibility issue which existed
for about two decades, and there are no libass plans to support the
previous behavior, so ultimately we have to adjust the mpv code, and
we can't guarantee to restore the old behavior in all cases.

Starting at this commit, vector drawing coords, font spacing, border
and shadow widths are all affected by PlayerResX (specifically, by
the aspect), while previously they were unaffected by PlayerResX.

This changed srt sub border and shadow widths in mpv, because ffmpeg
generates the ass with fixed PlayerResX of 384 (aspect of 4:3), and
with libass 0.17, if this doesn't match the video aspect, then borders
and shadow were too wide - because most clips aspect is more than 4:3.

The fact that ffmpeg uses fixed PlayerResX of 384 could be considered
an issue, but for now we have no control over it, and ffmpeg doesn't
have the video resolution when it converts an srt source to ass.

So here we adjust PlayerResX accordingly so that border/shadows are
now rendered with correct width.

However, regardless of that commit, changing PlayerResX also affects
the margin value, so to compensate, we adjust sub-margins-x too.

According to libass devs, this should cover basic srt-to-ass
conversion by ffmpeg to work correctly with libass 0.17.

However, there could be srt extensions which use more complex ass,
and/or ffmpeg conversion of other sub formats, where more things
need adjustments. As of now we don't know what these are, and so
we don't really know what else might remain broken or get broken.
---
 sub/sd_ass.c | 26 ++++++++++++++++++++++++++
 1 file changed, 26 insertions(+)

diff --git a/sub/sd_ass.c b/sub/sd_ass.c
index bec989fee7..7f0510bf5e 100644
--- a/sub/sd_ass.c
+++ b/sub/sd_ass.c
@@ -448,6 +448,32 @@ static void configure_ass(struct sd *sd, struct mp_osd_res *dim,
     if (converted)
         ass_track_set_feature(track, ASS_FEATURE_WRAP_UNICODE, 1);
 #endif
+    if (converted) {
+        bool override_playres = true;
+        char **ass_force_style_list = opts->ass_force_style_list;
+        for (int i = 0; ass_force_style_list && ass_force_style_list[i]; i++) {
+            if (bstr_find0(bstr0(ass_force_style_list[i]), "PlayResX") >= 0)
+                override_playres = false;
+        }
+
+        // srt ass from ffmpeg has fixed PlayerResX of 384 (and aspect of 4:3).
+        // starting with libass f08f8ea5 (pre 0.17) PlayerResX affects shadow
+        // and border widths, among others, so to render borders and shadows
+        // correctly, we adjust PlayerResX according to the video aspect.
+        // But PlayerResX also affects margins, so we adjust those too.
+        // This should ensure basic srt-to-ass ffmpeg conversion has correct
+        // borders, but there could be other issues with some srt extensions
+        // and/or different source formats which would be exposed over time.
+        // we make these adjustments only if the user didn't set PlaterResX.
+        if (override_playres) {
+            int vidw = dim->w - (dim->ml + dim->mr);
+            int vidh = dim->h - (dim->mt + dim->mb);
+            track->PlayResX = track->PlayResY * (double)vidw / MPMAX(vidh, 1);
+            double fix_margins = track->PlayResX / 384.0;
+            track->styles->MarginL = round(track->styles->MarginL * fix_margins);
+            track->styles->MarginR = track->styles->MarginL;
+        }
+    }
 }
 
 static bool has_overrides(char *s)
-- 
2.34.1
```

@llyyr does the text reflect your current understanding?

@astiob @TheOneric could you please confirm the texts are reasonably accurate?

**Comment by llyyr** [comment]
I've pushed the commit with that description and comments with some minor changes, I think this is fine for now.

File: sub/sd_ass.c [hunk 1]
```diff
@@ -448,6 +448,32 @@ static void configure_ass(struct sd *sd, struct mp_osd_res *dim,
...
+        // borders, but there could be other issues with some srt extensions
+        // and/or different source formats which would be exposed over time.
+        // we make these adjustments only if the user didn't set PlaterResX.
+        if (override_playres) {
+            int vidw = dim->w - (dim->ml + dim->mr);
+            int vidh = dim->h - (dim->mt + dim->mb);
+            track->PlayResX = track->PlayResY * (double)vidw / MPMAX(vidh, 1);
+            double fix_margins = track->PlayResX / 384.0;
+            track->styles->MarginL = round(track->styles->MarginL * fix_margins);
+            track->styles->MarginR = track->styles->MarginL;
```
Comment (TheOneric) [inline sub/sd_ass.c:474]: The general idea of overriding `PlayResX` and Margins seems good, but the specific implementation can be improved. As for the calculation of `vidw` and `vidh` itself I’ll just assume it is correct, but can't actually verify.
 - if `vidw` or `vidh` can be zero, it would be better to cap *both* to `>= 1` and move the `MPMAX` to their respective definitions.
 - hardcoding `384` seems brittle and may exacerbate problems with formats whose ffmpeg converter uses custom `PlayRes*`. Instead save the old `PlayResX` value to a temporary variable before overriding it.
 - i don't see why the fixup should enforce `MarginL == MarginR`. Scaling both independently seems better.
 
 ```diff
diff --git a/sub/sd_ass.c b/sub/sd_ass.c
index d3612f5514..32ea41991f 100644
--- a/sub/sd_ass.c
+++ b/sub/sd_ass.c
@@ -464,12 +464,13 @@ static void configure_ass(struct sd *sd, struct mp_osd_res *dim,
         // Do NOT change anything if an user override already set PlayResX.
         // TODO: also exclude converters with custom PlayRes?
         if (override_playres) {
-            int vidw = dim->w - (dim->ml + dim->mr);
-            int vidh = dim->h - (dim->mt + dim->mb);
-            track->PlayResX = track->PlayResY * (double)vidw / MPMAX(vidh, 1);
-            double fix_margins = track->PlayResX / 384.0;
+            int vidw = MPMAX(dim->w - (dim->ml + dim->mr), 1);
+            int vidh = MPMAX(dim->h - (dim->mt + dim->mb), 1);
+            double old_prx = track->PlayResX;
+            track->PlayResX = track->PlayResY * vidw / (double) vidh;
+            double fix_margins = track->PlayResX / old_prx;
             track->styles->MarginL = round(track->styles->MarginL * fix_margins);
-            track->styles->MarginR = track->styles->MarginL;
+            track->styles->MarginR = round(track->styles->MarginR * fix_margins);
         }
     }
 }
 ```

**Review by TheOneric — COMMENTED** [review]
To confirm again: yes the general idea of overriding `PlayResX` and margins  looks good to me. I don’t expect this to create any problems with SRT subs which "worked" before. The specific implementation here though can be improved; see code comment.

Btw, I now also looked up again which ffmpeg converters currently use custom `PlayRes`, see further below.

> could you please confirm the texts are reasonably accurate?

Not really important, but there a a couple typos:
 - last line of the code comment: `PlaterResX` 
 - commit message `PlayerResX`

> The fact that ffmpeg uses fixed PlayerResX of 384 could be considered an issue, but for now we have no control over it

It’s not a "could" but a definite "is". As a reminder, there are also other problems arising from ffmpeg not considering video resolution during conversion which were always broken and will always remain broken regardless of theoretical libass hacks. *(And ofc, even the border stuff never worked in VSFilters etc; the combination of ffmpeg and libass bugs merely happened to hide some of the more common problems.)*
There cannot ever be a correct conversion of all complexities without the video’s DAR.

Otherwise, if taking everything at face value only there are some rounding inaccuracies etc, but it can be considered technically correct. If you want to merge it like this, then go ahead.

However at least to me the phrasing seems prone to create misleading implications for readers without prior background knowledge. Personally, I’d write the comment and commit message something like this (note the `TODO`s):

**Commit Message**:
```
Subject: [PATCH] sd_ass: srt subs: fix too-wide border with libass 0.17

Prior to libass commit f08f8ea5 (between 0.16 and 0.17), it mistreated
scaling of several features with PlayResX and anamorphic stretching.
This both diverged from the authoritative reference implementation
VSFilter and was unintuitive in how PlayResX only affected some things.

However, this also made a bug in ffmpeg’s SRT-to-ASS converter more
obvious. Currently ffmpeg does not take the video’s DAR into
consideration during conversion but as a "best guess" assumes NTSC DVD
coordinates for positioning and outputs ASS with PlayRes of 384×288
(i.e. an aspect of 4:3). This breaks various things, but now that
borders get scaled correctly it can become apparent even on basic
text-only subs if the actual video DAR diverges enough from 4:3.

Ideally this should be fixed in ffmpeg, but in the meantime to at
least avoid anisotropic features for basic subs (as before), we’ll
fix up PlayResX of the ASS ffmpeg produces to match the video’s
actual DAR, keeping PlayResY fixed to preserve general scaling.

More complex SRT, using e.g. unofficial "extensions" for positioning
or inserting complex ASS override commands into SRT remain broken,
but there’s not much we can do about that here and it shouldn't be
worse than before.

For non SRT subs, most also just use ffmpeg’s internal default
PlayRes of 384×288, but some use ff_ass_subtitle_header_full
or copy-pasta'd the whole header generation code from libavcodec/ass.c
to set a custom value derived from the original sub format. Namely
this includes aribb24, aribcaption and movtext.
Overriding PlayResX may affect these formats negatively, but we
also aren't really sure what those formats and converters expect in the
first place.
TODO: exclude them or just override anyway and wait if someone
complains, who can then hopefully tell us more about what's expected?
```

Code comment
```C
        // Current ffmpeg has a bug where conversion from most sub formats
        // results in ASS with an hardcoded PlayRes with a 4:3 AR.
        // This unintentionally introduces anistotropy to e.g. borders.
        // To avoid this, keep PlayResY unchanged to preserve font size scaling
        // but fix up PlayResX to match the actual DAR.
        // Do NOT change anything if an user override already set PlayResX.
        // TODO: also exclude converters with custom PlayRes?

```

----

More generally and unrelated to the ffmpeg bug, for future tweaks it may be useful to categorise converted formats into "ASS-adjacent" and "independent". The latter will probably profit from enabling more VSF-incompatible `ASS_FEATURE_*`s, while the former shouldn't use much of them (`WRAP_UNICODE` should be fine, but everything else may be iffy).
E.g. I’d consider WebVTT to be firmly in the latter and it would imo profit from e.g. `ASS_FEATURE_WHOLE_TEXT_LAYOUT`. On the other SSF is firmly in the ASS-adjacent camp *(don't know if ffmpeg supports it)* and many SRT subs are as well. SRT is a bit tricky though, as it is underspecified and "complex" SRT subs depend on specifics of the author’s SRT renderer. While "complex SRT" subs exploiting VSF-quirk definitely exist, so do other SRT renderers and undoubtedly also SRT subs which don’t expect any VSF-like behaviour.
Perhaps for SRT the categorisation should be user-toggleable, or treat SRT special with a user-configurable mix of both `ASS_FEATURE__*`s.

I cannot help any further though with what behaviour various non-SSA/ASS sub formats expect.

File: sub/sd_ass.c (hunk 1 above)
Comment (llyyr) [reply sub/sd_ass.c:474]: I don't think vidw or vidh can be zero, a lot of other things would blow up before this piece of code would even be reached if that were the case. @avih suggested that I wrap it in MPMAX.

288x384 is hardcoded everywhere in sub/*, I eventually intend to clean this up but for now I'll save old PlayResX.

MarginL == MarginR is something that we already do, so I simply copied the behavior. https://github.com/mpv-player/mpv/blob/master/sub/ass_mp.c#L76-L77

Comment (avih) [reply sub/sd_ass.c:474]: > @avih suggested that I wrap it in MPMAX.

Yeah, we divide by `vidh`, so it can't be 0. It's guarded just like earlier in this function. If `vidw` is 0 then whatever, but it won't blow due to division by zero.

**Comment by avih** [comment]
> To confirm again: yes the general idea of overriding `PlayResX` and margins looks good to me. I don’t expect this to create any problems with SRT subs which "worked" before

Thanks.

> there a a couple typos:

Thanks.

> Otherwise, if taking everything at face value only there are some rounding inaccuracies etc, but it can be considered technically correct. If you want to merge it like this, then go ahead.

Thanks.

> It’s not a "could" but a definite "is"

This worked correctly for a very long time, so it was de-facto correct. It only became an issue when libass discovered a vsfilter compatibility problem and changed its behavior.

I guess this makes libass more correct than before (according to its own standards), and ffmpeg more wrong than before (according to libass standards), but at the time it was written it was working just fine.

So I prefer to stick to the facts: libass changed, and ffmpeg uses a fixed PlayerResX value, which results in issues with new libass - which this commit handles to some degree.

> the phrasing seems prone to create misleading implications for readers without prior background knowledge

Can you please be specific? which phrasing/paragraph/suggestion exactly can mislead, and what would be a better description?

It's a bit hard to pick with a completely new suggested commit message...

File: sub/sd_ass.c (hunk 1 above)
Comment (TheOneric) [reply sub/sd_ass.c]: > If vidw is 0 then whatever, but it won't blow due to division by zero.

`PlayRes* <= 0` is not a valid value, so it will be treated as unset(or invalidly set) and ASS’ mechanism for deriving a default kicks in. While in most cases I’d expect this to still lead to `PlayResX = 1` in the end, this may not hold true for all edge cases and it is not a particular clean approach.
Just clamping `vidw`/`widh` as I previously suggested doesn't fully solve it either though. The following would probably be best:
```C
track->PlayResX = MPMAX(track->PlayResY * vidw / (double) MPMAX(vidh, 1), 1);
```

> MarginL == MarginR is something that we already do

I’m not that familiar with this part of mpv, but I’m guessing this just sets the initial default (same with hardcoded `288×384`). Otherwise e.g. user overrides like `MarginL=5,MarginR=50` wouldn't work. But we want them to work and then scale them afterwards.

In either case I personally think it is best to not hardcode any values or assumptions about how the Style was preinitialised at this part. This will only cause additional hassle should those other areas ever change. In the end this up to mpv devs to decide though.

Comment (avih) [reply sub/sd_ass.c]: > `PlayRes* <= 0` is not a valid value, so it will be treated as unset(or invalidly set) and ASS’ mechanism for deriving a default kicks in.

That's absolutely fine as far as I'm concerned. If the width is 0 then nothing sensible can result either way. The goal here is only to avoid division by zero.

> Otherwise e.g. user overrides like `MarginL=5,MarginR=50` wouldn't work

This is already fixed at the updated PR code from yesterday. Thanks for noticing it in the first palce.

> In either case I personally think it is best to not hardcode any values

If you refer to the 384, then we already added a comment why it's fixed like that. This should be enough until we maybe (or never) unify all the 384 values into a single constant.

Also, I'd appreciate if you could reply to my question about the "misleading phrasing". Thanks.

Comment (TheOneric) [reply sub/sd_ass.c]: >  refer to the 384, then we already added a comment why it's fixed like that. This should be enough until we maybe (or never) unify all the 384 values into a single constant.

this new comment
```
ffmpeg and mpv use a default PlayResX of 384 when it is not known, this comes from VSFilter
```
 does not explain why you are expecting hardcoding this here to be a good idea for e.g. the aforementioned ffmpeg-converted sub with custom PlayRes or why you think ffmpeg won't ever change their default `PlayRes` sizes.
“Comes from VSFilter” is no justification at this place. Converters do not need to care what defaults ASS uses for unset `PlayRes` since they can just set whatever valid values they want. This entails being free to chose their own defaults whenever and to whatever valid value they like. And ASS defaults behaves differently depending on if both or only one `PlayRes*` value is unknown and what the known value is, so it isn't even always `384`.

I continue to believe this is a bad idea, but if you’re determined to stick with this then do so.

**Comment by TheOneric** [comment]
> [avih:] Also, I'd appreciate if you could reply to my question about the "misleading phrasing". Thanks.

Rest assured that I intended and still intent to do so. In this case this didn't already happen since after writing the reply to the code comment thread, I looked at the clock, noticed *“oh, this late already”* and then left for `$things`.
You seem especially impatient here, by previously writing on IRC with questions just to then a couple minutes later repost them on GH once you didn't get a fast reply and now requesting a reply to your other comment on GH, mere 20min after my last post — eventhough you yourself had a gap of about 45min between your two posts about code and the description yesterday. You seem to have unreasonable expectations about available time and priority. Temper them.

The specification of what needs to be adjusted was already known and verified from the start. I’m only here because you explicitly asked for my additional feedback and re-verification on this. If now, in addition to my lack of time due to being busy, you keep being pushy this doesn't exactly raise my motivation to spend what little time I have available atm on this.

File: sub/sd_ass.c (hunk 1 above)
Comment (avih) [reply sub/sd_ass.c]: > `PlayRes* <= 0` is not a valid value, so it will be treated as unset(or invalidly set) and ASS’ mechanism for deriving a default kicks in.

That's absolutely fine as far as I'm concerned. If the width is 0 then nothing sensible can result either way. The goal here is only to avoid division by zero.

> Otherwise e.g. user overrides like `MarginL=5,MarginR=50` wouldn't work

This is already fixed at the updated PR code from yesterday. Thanks for noticing it in the first palce.

> In either case I personally think it is best to not hardcode any values

If you refer to the 384, then we already added a comment why it's fixed like that. This should be enough until we maybe (or never) unify all the 384 values into a single constant.

Also, I'd appreciate if you could reply to my question about the "misleading phrasing". Thanks.

> I continue to believe this is a bad idea, but if you’re determined to stick with this then do so.

What exactly is a bad idea here? using 384 with a comment instead of using it as a constant or some `#define` ?

Comment (avih) [reply sub/sd_ass.c]: > I continue to believe this is a bad idea, but if you’re determined to stick with this then do so.

What exactly is a bad idea here? using 384 with a comment instead of using it as a constant or some `#define` ?

I don't think I understand what you think would be a better idea...

**Comment by llyyr** [comment]
I'm not really certain what your prescription here is if you think this is a bad idea. Is there *any* way mpv can fix the borders, short of me or someone else learning ffmpeg internals and making the required changes to support the new libass behavior there?

**Comment by TheOneric** [comment]
> I'm not really certain what your prescription here is if you think this is a bad idea. Is there _any_ way mpv can fix the borders, [...]?

Did you mean to reply to the closing *“I continue to believe this is a bad idea, but if you’re determined to stick with this then do so.”* from my [code comment reply](https://github.com/mpv-player/mpv/pull/11831#discussion_r1264515149)? This comment references the hardcoding of (known to be sometimes wrong) magic values and exclusively is about exactly that. This hardcoding is the “bad idea”.

Overriding `PlayResX` is no solution *(fixing the buggy converter would be)*, but an acceptable workaround for the meantime. I’m the one who suggested this afterall and have already umpteen times on request reverified that this general approach looks good.

File: sub/sd_ass.c (hunk 1 above)
Comment (TheOneric) [reply sub/sd_ass.c]: > What exactly is a bad idea here? using 384 with a comment instead of using it as a constant or some `#define` ?

Using a constant variable or `#define` would be no better. Assuming `PlayResX` always were `384` before is the problem and I already pointed out cases for which this assumption doesn't hold.
The better idea is exactly what I wrote in my initial code comment and the accompaniying suggested diff:
> - hardcoding 384 seems brittle wrt to future ffmpeg changes and may exacerbate problems with formats whose ffmpeg converter uses custom PlayRes*. Instead save the old PlayResX value to a temporary variable before overriding it.
>
> [...]
> `double fix_margins = track->PlayResX / old_prx;`

**Comment by TheOneric** [comment]
**Part 1: Why *is* this an ffmpeg bug (yet again)**

> > It’s not a "could" but a definite "is"
>
> This worked correctly for a very long time, so it was de-facto correct.

No. ffmpeg produces "ASS", and the ASS never worked in VSFilter — the authorative source on how to render ASS and a still popular ASS renderer choice on Windows.

> It only became an issue when libass discovered a vsfilter compatibility problem and changed its behavior.

As before, it already was not working before.

> I guess this makes libass more correct than before (according to its own standards),

those standards being ASS and rendering ASS(+SSA) is libass primary goal. That’s why its called lib*ass* and not lib*srt*, lib*sub* or so.

> and ffmpeg more wrong than before (according to libass standards)

It remains just as wrong as before. It claims to convert to ASS, yet doesn't render as intended in ASS’ reference implementation.

> but at the time it was written it was working just fine.

(again:) No it never did.

> So I prefer to stick to the facts: libass changed, and ffmpeg uses a fixed PlayerResX value,

The fact is, ASS didn't change at all in this regard *(and since "true", VSF-compatible ASS has long-term stability guarantees never will)* and ffmpeg’s output was broken from the beginning.
libass fixed a rendering bug, which used to break real, native ASS files. Now those files render as intended.

**Comment by llyyr** [comment]
> No. ffmpeg produces "ASS", and the ASS never worked in VSFilter — the authorative source on how to render ASS and a still popular ASS renderer choice on Windows.

Are you sure this was never working on VSFilter? From what I know, VSFilter defaulted to ScaledBorderAndShadow = no ([and still does](https://github.com/pinterf/xy-VSFilter/blob/15390e5fb97465cb939888dd267a9eb67d06b229/src/subtitles/STS.cpp#L2446)) so it was never tried to scale them anyway because ffmpeg also never set ScaledBAS on the converted subtitles until you made the commit to change it https://github.com/FFmpeg/FFmpeg/commit/e6dcb6a0db7d05f789f8a672d61704d170836555

As far as I can tell just by looking at git history of ffmpeg and various VSFilter forks, even if VSFilter scaled borders and shadows in the x-axis, in practice this never broke anything for ffmpeg-converted subtitles until 2020 when it suddenly started asking for scaling on borders and shadows, even on Windows.

> As above, it already was not working before.

This should've been working until ffmpeg 4.3.

**Comment by TheOneric** [comment]
> so it never tried to scale them anyway

Exactly and as a result, borders were ridiculously small — barely noticeable even — in VSFilter on any modern "high res" video, which was clearly also not the intended rendering. So yes, the output was broken (in a different, even more obvious way).

> working until ffmpeg 4.3.

nope, see above.

**Comment by TheOneric** [comment]
**Part 1.1: An analogy** (will merge per edit into Part 1 once emails are out)

If ffmpeg’s output never rendering correctly in the very implementation defining ASS isn't obvious enough for you, perhaps stepping away from the specific situation here and instead considering the following analogy helps. If it doesn't help, just ignore it:

Mutter (Gnome Wayland) does currently not implement idle-inhibit. Yet many applications use this protocol when available.
Imagine someone who uses Gnome Wayland likes to fall asleep to Music, but also doesn't want their device to keep running the whole night. To this end they depend on their device automatically going to sleep after a set amount of time.Their music player implements the idle-inhibit protocol, but since Mutter doesn't it goes to sleep as they intended.
One day Mutter gains support and the device no longer goes to sleep automatically. The music player even has an option to disable idle-inhibit, bu since it wasn't implemented by their compositor before they didn't set it.

Now claiming, the border rendering is not an ffmpeg but a libass issue seems akin to me to as if this hypothetical person would now complain to Mutter to have broken their sleep routine and says since it worked before and now doesn't anymore after a Mutter change, it was previously correct to assume idle would not be inhibited even if using the idle-inhibit protocol in the client.
And demanding Mutter should purge support again or at least implement an auto disable if they notice the name of the sending program starts with `music` and the username starts with `analog`.

Obviously the lack of support for idle-inhibt has always been a Mutter issue which prevented many valid usecases from working. And it was never valid to expect idle not being inhibited when the client uses idle-inhibit to request just that. Instead of this support being purged again described person should just flip the option and implement such an option in any other program they wish to not prevent idle.

**Comment by llyyr** [comment]
>Mutter (Gnome Wayland) does currently not implement idle-inhibit. Yet many applications use this protocol when available.
>Imagine someone who uses Gnome Wayland likes to fall asleep to Music, but also doesn't want their device to keep running the whole night. To this end they depend on their device automatically going to sleep after a set amount of time.Their music player implements the idle-inhibit protocol, but since Mutter doesn't it goes to sleep as they intended.
One day Mutter gains support and the device no longer goes to sleep automatically. The music player even has an option to disable idle-inhibit, bu since it wasn't implemented by their compositor before they didn't set it.

Except in this analogy, libass is not Mutter. libass is *everyone else*. It's as if Kwin/wlroots decided that Mutter must be not implementing idle-inhibit for a good reason and they're one of the most used compositors so we ought to follow their standards and remove support for idle-inhibit after initially having supported it.

Anyway, I'm not sure what the point of continuing this dialogue is if this is about the commit message not explicitly calling this a ffmpeg bug. Let's save everyone some time instead. 

I think the commit message and the code comment are perfectly neutral. I do not think this is a ffmpeg bug, and I also do not think this is a libass bug, which is why I haven't called it a bug anywhere.

Noting that libass changed its behavior after over a decade and a half to have perfect 1:1 bug compatibility with VSFilter and "this could be considered a ffmpeg bug" are fair descriptions of this issue and won't change.

**Comment by TheOneric** [comment]
**Part 2: Details about the original commit message and code comment**

> > the phrasing seems prone to create misleading implications for readers without prior background knowledge
>
> Can you please be specific? which phrasing/paragraph/suggestion exactly can mislead, and what would be a better description?
> 
> It's a bit hard to pick with a completely new suggested commit message...

The general gist is, that if missing background knowledge on who created and defines ASS, the text you proposed can be interpreted to implying such a way as if libass had unilateral control over the ASS format and any ability to implement breaking changes to it. It also implies ffmpeg’s output were "working" before and a higher degree of stability in libass rendering output than it actually has. These are not the case.  
The text I proposed removes such implications and adds an explainer to how ASS is defined.

But sure, I can go over some points in more detail:

> Libass commit f08f8ea5 (between 0.16 and 0.17) changed how PlayerResX affects some aspects of rendering.

This is *technically* correct in that it changed how `PlayResX` affects *libass’* rendering result. But it doesn't specify this limitation to *libass’* rendering. With the necessary background knowledge this context is obvious, but without it it may be seen as a general statement. In general however, `PlayResX` *always* affected ASS rendering in this way, libass just got it wrong. libass also has no authority to redefine how ASS works. Such a redefinition would also break countless existing subtitle releases.

> The libass change fixes a VSFilter compatibility issue which existed for about two decades

VSFilter existed for two decades, libass is several years younger *(this is the aforementioned rounding error)*. Technically it is correct that the compatibility issue existed for as long as libass did and with rounding one may stretch this to two decades.
However, this text then still implies libass’ rendering result had been reliable for *nearly two decades*. Especially in the beginning though libass output greatly differed from its current one and VSFilter and many features were completely unsupported. libass regularly changes to better match VSFilter and those changes were especially frequent and noticeable in the beginning years.

> Starting at this commit, vector drawing coords, font spacing, border and shadow widths are all affected by PlayerResX (specifically, by the aspect), while previously they were unaffected by PlayerResX.

Again, they were/are only un/affected in *libass’* rendering. They always were affected in ASS.

> srt [...] ffmpeg generates the ass with fixed PlayerResX of 384

It currently uses this fixed value for SRT. It might change the value in the future and other formats already use custom values in their ffmpeg converter.

> The fact that ffmpeg uses fixed PlayerResX of 384 could

already discussed in detail.

> As of now we don't know what these are

As mentioned, I did at least look up for which formats ffmpeg converters use custom PlayRes. This and its implications are mentioned in the text I proposed.

> // starting with libass f08f8ea5 (pre 0.17) PlayerResX affects shadow
> // and border widths, among others

Same as 4 above.

**Comment by TheOneric** [comment]
> Except in this analogy, libass is not Mutter. libass is everyone else. It's as if Kwin/wlroots decided that Mutter must be not implementing idle-inhibit for a good reason and they're one of the most used compositors so we ought to follow their standards and remove support for idle-inhibit after initially having supported it.

Not really. Wayland protocols are clearly defined *outside* of Mutter. While for ASS, VSFilter *created* ASS and its rendering *is* the definition of what ASS should do. This is ofc not a particularly good way to create a format, but since it was also the *only* implementation for years and continued to be very dominant even after (less featureful) alternatives emerged, this is how it went and existing ASS releases depend on all kinds of VSFilter quirks.
In this case, the VSFilter behaviour isn't even quirky though, but actually sensible and old libass behaviour was the weird one.

Just considering current Mutter instead of the standards is more akin to what ffmpeg’s converter does — just that ffmpeg’s converter is even worse and also does things which don't even and never did render as intended in libass or *any* ASS renderer.

**Comment by TheOneric** [comment]
Anyway, as far as I was concerned my involvement would have ended at the suggestion how to realise a workaround, but since avih explicitly (and repeatedly) asked I gave more detailed feedback.
I already wrote before that you can keep the imho misunderstanding-invinting message if you want, but again more details were asked for; now you have them.
I don't intend to keep this going any further though. If it isn't a concrete question on the implementation or custom-PlayRes converters, don't expect a reply, I spent enough time on this.

**Comment by TheOneric** [comment]
Better and shorter analogy (again will be merged, but email notifs for those subscribed to this bug):


Imagine a media streaming server uses some library to live-transcode media to AV1. This library has a bug, where it writes garbage into the grain synthesis fields. Since the lib authors and users of the media server primarily use one media player who doesn't currently support grain synthesis at all, they didn't notice this bug. The majority of other AV1 decoders including notably the reference AV1 decoder do already support grain and reveal the issue.
One day the media player gains support for AV1 grain synthesis and users of the media server now notice weird grains and "artefacts" in the video they receive from the server.
Would you claim, this is not necessarily a bug in the AV1 transcoder, since "it worked before" (for one particular decoding setup)?

**Comment by avih** [comment]
> No. ffmpeg produces "ASS", and the ASS never worked in VSFilter

I believe you, but mpv was using libass the whole time, and we did not test with vsfilter and don't support compiling with vsfilter. Maybe the ffmpeg guys should have tested with vsfilter instead. I can't speak for them, but mpv ass backend is libass exclusively, for better or worse, and ultimately this is what we care about in mpv, and in this configurations the borders were correct.

It doesn't make things more right or more wrong, just facts.

Anyway, thanks for the time, review, comments, and clarifications.

I understand your "misleading phrasing" comment was referring to our description of "could be considered an ffmpeg issue" rather than your preference for "is an ffmpeg issue".

I think it's not very critical as long as ffmpeg is pointed at, and the commit message sheds reasonable light, so I'm leaving it as is.

> This hardcoding (of 384 - avih) is the “bad idea”.

Thanks for the clarification. I think the comment makes it less magical. I'm also not excluding unifying all the 384 values into a single definition in the future, but for now, I think this comment is reasonably descriptive.

I'll merge it a bit later.

Thanks again.
