### PR TITLE
Revert "ao_coreaudio: switch to ao_read_data_nonblocking()"

### LINKED ISSUE #13880: Audio stuttering on macOS since v0.37.0
Possibly related issues/PRs:
https://github.com/mpv-player/mpv/issues/13676
https://github.com/mpv-player/mpv/pull/12643#issuecomment-1774264729
https://github.com/mpv-player/mpv/issues/13348

### Important Information

Provide following Information:
- mpv version: v0.37.0-775-g9030e6a7ad
- macOS Version: 14.4.1 (23E224)
- Source of the mpv binary or bundle: binary, compiled from source
- If known which version of mpv introduced the problem: v0.37.0
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

`mpv <any file> --no-config`

### Expected behavior

No audio stuttering.

### Actual behavior

Audio stutters every 20 to 60 seconds when playing any file.

I also get these kinds of errors in the macOS console:

- Healer Girl 05 (CR)
Capture d’écran 2024-04-13 à 17 17 37

- <a href="https://kara.yuru.moe/Aqours%20-%20LIVE%20-%20Mattete%20Ai%20no%20Uta%20(VIDEO%20Love%20Live!%20Sunshine!!%20Aqours%204th%20LoveLive!%20～Sailing%20to%20the%20Sunshine～%20Day%202)/Aqours%20-%20LIVE%20-%20Mattete%20Ai%20no%20Uta%20(VIDEO%20Love%20Live!%20Sunshine!!%20Aqours%204th%20LoveLive!%20～Sailing%20to%20the%20Sunshine～%20Day%202).mp4">Aqours - LIVE - Mattete Ai no Uta (VIDEO Love Live! Sunshine!! Aqours 4th LoveLive! ～Sailing to the Sunshine～ Day 2).mp4</a>
Capture d’écran 2024-04-13 à 17 21 35

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14968649/mpv.log)

(There were stutters at 0:30 and 0:40 but nothing relevant was logged)

### Sample files

N/A

### PR DESCRIPTION
**Pull request by m154k1**
Fixes #13880

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Maybe 0341a6f1d39801160322d3fe16245f8387735f4b needs to be reverted too?

**Comment by sfan5** [comment]
> Maybe [0341a6f](https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b) needs to be reverted too?

No, the blocking function does not guarantee that `ret_samples == samples` either.

**Comment by kasper93** [comment]
Is it possible to do the same for ao_avfoundation?

``` diff
diff --git a/audio/out/ao_avfoundation.m b/audio/out/ao_avfoundation.m
index 7654916519..61bf39620e 100644
--- a/audio/out/ao_avfoundation.m
+++ b/audio/out/ao_avfoundation.m
@@ -76,12 +76,7 @@ static void feed(struct ao *ao)
     int64_t cur_time_mp = mp_time_ns();
     int64_t end_time_av = MPMAX(p->end_time_av, cur_time_av);
     int64_t time_delta = CMTimeGetNanoseconds(CMTimeMake(request_sample_count, samplerate));
-    int real_sample_count = ao_read_data_nonblocking(ao, data, request_sample_count, end_time_av - cur_time_av + cur_time_mp + time_delta);
-    if (real_sample_count == 0) {
-        // avoid spinning by blocking the thread
-        mp_sleep_ns(10000000);
-        goto finish;
-    }
+    int real_sample_count = ao_read_data(ao, data, request_sample_count, end_time_av - cur_time_av + cur_time_mp + time_delta);

     if ((err = CMBlockBufferCreateWithMemoryBlock(
         NULL,
```

**Comment by Akemi** [comment]
@ruihe774 see @kasper93 comment above.

**Comment by ruihe774** [comment]
> Is it possible to do the same for ao_avfoundation?
> 
> ```diff
> diff --git a/audio/out/ao_avfoundation.m b/audio/out/ao_avfoundation.m
> index 7654916519..61bf39620e 100644
> --- a/audio/out/ao_avfoundation.m
> +++ b/audio/out/ao_avfoundation.m
> @@ -76,12 +76,7 @@ static void feed(struct ao *ao)
>      int64_t cur_time_mp = mp_time_ns();
>      int64_t end_time_av = MPMAX(p->end_time_av, cur_time_av);
>      int64_t time_delta = CMTimeGetNanoseconds(CMTimeMake(request_sample_count, samplerate));
> -    int real_sample_count = ao_read_data_nonblocking(ao, data, request_sample_count, end_time_av - cur_time_av + cur_time_mp + time_delta);
> -    if (real_sample_count == 0) {
> -        // avoid spinning by blocking the thread
> -        mp_sleep_ns(10000000);
> -        goto finish;
> -    }
> +    int real_sample_count = ao_read_data(ao, data, request_sample_count, end_time_av - cur_time_av + cur_time_mp + time_delta);
> 
>      if ((err = CMBlockBufferCreateWithMemoryBlock(
>          NULL,
> ```

@kasper93 avfoundation can well handle audio buffer of variable length.

File: audio/out/ao_coreaudio.c [hunk 1]
```diff
@@ -89,7 +89,7 @@ static OSStatus render_cb_lpcm(void *ctx, AudioUnitRenderActionFlags *aflags,
 
     int64_t end = mp_time_ns();
     end += p->hw_latency_ns + ca_get_latency(ts) + ca_frames_to_ns(ao, frames);
-    int samples = ao_read_data_nonblocking(ao, planes, frames, end);
+    int samples = ao_read_data(ao, planes, frames, end);
```
Comment (ruihe774) [inline audio/out/ao_coreaudio.c:92]: I think we should not use `samples` returned from `ao_read_data`, which may be less than requested. The original implementation did not use it and always submit buffers of requested length to CoreAudio. CoreAudio *expect* the buffer length be equal to requested.

**Review by ruihe774 — CHANGES_REQUESTED** [review]

**Comment by sfan5** [comment]
> @kasper93 avfoundation can well handle audio buffer of variable length.

The point is that sleeping 10ms when no samples are returned makes no sense. You can as well just use the blocking variant.

**Comment by kasper93** [comment]
> @kasper93 avfoundation can well handle audio buffer of variable length.

That's cool. Let me rephrase me question. Could we remove this terrible hack of blocking the audio thread for 10 ms by all means necessary?

**Comment by ruihe774** [comment]
I don't think "sleeping 10ms" and "blocking variant" are the same thing. `ao_read_data`, the "blocking variant", does *not* block when "no samples are returned". It only blocks on mutex contention. We still need to sleep for "no samples are returned" even if `ao_read_data` is used.

**Comment by sfan5** [comment]
> I don't think "sleeping 10ms" and "blocking variant" are the same thing. `ao_read_data`, the "blocking variant", does _not_ block when "no samples are returned". It only blocks on mutex contention.

I assumed that the sleep was added after the author noticed that it would spuriously return zero (usually on mutex contention, like you said). If this isn't the case then that doesn't apply ofc.
I haven't investigated closely but if the lack of samples instead happens near EOF it sounds like the core is maybe not pausing the AO early enough?

**Comment by ruihe774** [comment]
> > I don't think "sleeping 10ms" and "blocking variant" are the same thing. `ao_read_data`, the "blocking variant", does _not_ block when "no samples are returned". It only blocks on mutex contention.
> 
> I assumed that the sleep was added after the author noticed that it would spuriously return zero (usually on mutex contention, like you said). If this isn't the case then that doesn't apply ofc. I haven't investigated closely but if the lack of samples instead happens near EOF it sounds like the core is maybe not pausing the AO early enough?

The core does not stop AO until EOF. In fact, there is no API for core to tell pull-based AO to "stop requesting data but continue playing enqueued data". Some AO, like pipewire, will starve and spin near EOF; but because pipewire usually has very short device buffer (1024 samples usually), it will not spin too many times. This is not the case for avfoundation, which can be starving more than 1 second near EOF.

**Comment by ruihe774** [comment]
@sfan5 why you've merged it? I have a ongoing review https://github.com/mpv-player/mpv/pull/13902#discussion_r1569279001

**Comment by sfan5** [comment]
> The core does not stop AO until EOF. In fact, there is no API for core to tell pull-based AO to "stop requesting data but continue playing enqueued data". Some AO, like pipewire, will starve and spin near EOF; but because pipewire usually has very short device buffer (1024 samples usually), it will not spin too many times.

I see. Maybe that'd be a good thing to address in the future. Just sleeping in the ao thread feels like a dirty fix.

> @sfan5 why you've merged it? I have a ongoing review [#13902 (comment)](https://github.com/mpv-player/mpv/pull/13902#discussion_r1569279001)

We decided on IRC that we are okay with merging the revert since OP confirmed that it helps their case.
The other change has been there longer (0341a6f1d39801160322d3fe16245f8387735f4b) and we're not aware of it causing issues yet. So that can be solved afterwards.

**Comment by Akemi** [comment]
it was actually because of me. i didn't see your comment and i felt like reverting to the state before would be reasonable. we were talking about the release and what is blocking it on irc and decided to merge it.

> 20:43	der_richter	from the comments on the issue it seems to fix the issue. can't really confirm since i didn't encounter it.
> 20:45		if you are fine with it, i would merge the revert commit for now. since we don't really have anyone who is well versed with the coreaudio stuff, i doubt we could get a better solution in a timely fashion? and if we do we can still merge another fix.

i am still very much interested in a proper solution, if possible.

**Comment by ruihe774** [comment]
> We decided on IRC that we are okay with merging the revert since OP confirmed that it helps their case. The other change has been there longer ([0341a6f](https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b)) and we're not aware of it causing issues yet. So that can be solved afterwards.

https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b is a hacky fix for https://github.com/mpv-player/mpv/commit/ae908a70cecebb2cac8354a3b4d8967af847bd3e (see https://github.com/mpv-player/mpv/pull/12643#issuecomment-1774264729). Since we've reverted https://github.com/mpv-player/mpv/commit/ae908a70cecebb2cac8354a3b4d8967af847bd3e, https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b is no longer necessary. Giving there are no issues reported for it, I'm OK with current solution.

**Comment by Akemi** [comment]
we actually have a problem with https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b, this one https://github.com/mpv-player/mpv/issues/13348, and i was contemplating of reverting it too.

should we revert it too or do you think there is a better way of handling it @ruihe774?

**Comment by ruihe774** [comment]
> we actually have a problem with [0341a6f](https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b), this one #13348, and i was contemplating of reverting it too.
> 
> should we revert it too or do you think there is a better way of handling it @ruihe774?

I think we need to revert it. cc @handlerug

**Comment by low-batt** [comment]
I just confirmed that #13348 still reproduces with `libmpv` built from the current master. This PR did not fix it.

**Comment by ruihe774** [comment]
> I just confirmed that #13348 still reproduces with `libmpv` built from the current master. This PR did not fix it.

Yes. We need another revert for https://github.com/mpv-player/mpv/commit/0341a6f1d39801160322d3fe16245f8387735f4b. I'm still waiting response from @handlerug.
