### PR TITLE
msg: print MSGL_WARN and higher error messages to stderr

### LINKED ISSUE #8608: Encoding mode: error messages generated during conf parsing appear at the beginning of the encoded output stream when piping output (--o=-)
### Important Information

- mpv version: git master latest

### Reproduction steps

mpv.conf:
```
af-add=non-existent-filter
```

Command line:

```
mpv --of=matroska --o=- "video.mp4" >out.mkv
```

But the resulting media is unplayable.

Opening out.mkv in a hex editor reveals the problem, observe the text error at the beginning before the matroska header bytes:

Frhed_Rs1TwNeQzN

So any errors generated during the conf loading stage are sent to the output stream when using `--o=-`, creating a corrupted media stream that cannot be read.

A similar command where we try to pipe the output to another process also fails:

```
mpv --of=matroska --o=- "video.mp4" | ffplay -i -
```

### PR DESCRIPTION
**Pull request by Dudemanguy**
mpv has a historical convention where it actually always prints stuff to stdout. When doing encoding mode and outputing it to stdout, there's logic during startup force all the output to stderr instead so it doesn't mess up the encode. This is well and good, but mpv can put messages into stdout before mp_msg_force_stderr is run (like parsing a config file and finding errors). That puts junk data in the encode and screws up the output. Fix it by simply running an fseek in mp_msg_force_stderr to mark that as the start of the stream. That function is only ever called by encode mode anyways.

Supersedes #9302 (see some discussion there).

### CODE REVIEW

File: common/msg.c [hunk 1]
```diff
@@ -713,13 +713,18 @@ void mp_msg_update_msglevels(struct mpv_global *global, struct MPOpts *opts)
...
-void mp_msg_force_stderr(struct mpv_global *global, bool force_stderr)
+bool mp_msg_force_stderr(struct mpv_global *global, bool force_stderr)
 {
     struct mp_log_root *root = global->log->root;
 
     pthread_mutex_lock(&root->lock);
     root->force_stderr = force_stderr;
     pthread_mutex_unlock(&root->lock);
+    if (force_stderr) {
+        if (fseek(stdout, 0, SEEK_SET))
```
Comment (N-R-K) [inline common/msg.c:724]: This would not work when stdout is a pipe.

Also causes a null-deref in failure case:

```
../common/encode_lavc.c:232:9: runtime error: member access within null pointer of type 'struct AVFormatContext'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==28820==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x7fef8e5f930b bp 0x000000000020 sp 0x7ffd962c8ea0 T0)
==28820==The signal is caused by a READ memory access.
==28820==Hint: address points to the zero page.
    #0 0x7fef8e5f930b in avio_closep (/usr/lib64/libavformat.so.58+0x6e30b)
    #1 0x490168 in encode_lavc_free ../common/encode_lavc.c:232
    #2 0x48e833 in encode_lavc_init ../common/encode_lavc.c:169
    #3 0x7e8f24 in mp_initialize ../player/main.c:404
    #4 0x7e971f in mpv_main ../player/main.c:436
    #5 0xa69f2d in main ../osdep/main-fn-unix.c:5
```

To reproduce:

```console
$ mpv --of=matroska --o=- "somevid.mp4" | tee /tmp/out.mkv >/dev/null
```

**Review by N-R-K — CHANGES_REQUESTED** [review]

File: common/msg.c (hunk 1 above)
Comment (Dudemanguy) [reply common/msg.c:724]: Ah dang good point there. Hmm.

**Comment by Dudemanguy** [comment]
I changed it so it tries to fseek the stream. This won't always work of course, and in those cases it will print a warning. I'm not really sure there's a practical way to make a perfect solution unless someone has some clever idea on how to get rid of the crap that's in stdout (avoiding it would probably be a lot of re-engineering that's not worth it).

**Comment by N-R-K** [comment]
> mpv has a historical convention where it actually always prints stuff to stdout.

IMO, proper fix would be to stop doing this. And output warning/errors to `stderr`, which is more appropriate anyways.

**Comment by Dudemanguy** [comment]
Putting warning and up on stderr would be pretty easy. I dunno if that would have any deep implications, but I'm not opposed to it in principle. I know that wm4 didn't like it for whatever reason (couldn't really find any explanations anywhere briefly searching around).

**Comment by N-R-K** [comment]
(Arguably) less hacky than fseeking stdout, and would work on non-seekable destination as well without (potentially) breaking anything since it'd be opt-in:

```diff
diff --git a/player/main.c b/player/main.c
index 8026f016a..c3aef8fca 100644
--- a/player/main.c
+++ b/player/main.c
@@ -283,6 +283,8 @@ struct MPContext *mp_create(void)
 
     // Nothing must call mp_msg*() and related before this
     mp_msg_init(mpctx->global);
+    if (getenv("MPV_FORCE_STDERR"))
+        mp_msg_force_stderr(mpctx->global, true);
     mpctx->log = mp_log_new(mpctx, mpctx->global->log, "!cplayer");
     mpctx->statusline = mp_log_new(mpctx, mpctx->log, "!statusline");
 
```

**Comment by avih** [comment]
> IMO, proper fix would be to stop doing this. And output warning/errors to `stderr`, which is more appropriate anyways.

I agree with that, but I also have no clue how much other things depend on errors/warnings going to stdout.

But I think it's worth a try. Either way, stdout already can't be used normally to capture mpv standard output, so that part is already b0rked for users.

Adding error messages where the standard output goes (that is, to `stderr`) is not likely to introduce regressions for _users_ that I can think of (and that's not intended for automatic processing anyway, but even then they could use the `--quiet` et al options if they try to capture some custom script output etc), though again, no idea what internal mpv things depend on this, if any.

**Comment by Dudemanguy** [comment]
>But I think it's worth a try.

I've gone ahead and changed this to exactly that: MSGL_WARN and greater get printed to stderr. Personally, I also can't think of any particular problems for a user, but I presume there was some reason for it previously being on stdout. Anyways, I'm perfectly fine with trying it if everyone else is OK with it.

**Comment by N-R-K** [comment]
This fixes the encoding issue for good, both seekable and non-seekable destinations work well, as expected. And from some light testing, things seem to be working OK.

> no idea what internal mpv things depend on this, if any.

I highly doubt anything *internal* would break. If it did, wouldn't it be already broken when encoding mode was being used?

**Review by sfan5 — APPROVED** [review]
