### PR TITLE
wayland: match x11 cursor behavior

### LINKED ISSUE #6185: Gnome Wayland: mpv only hides the cursor if I move it
```
Arch Linux 
GNOME Shell 3.30.0 on Wayland

$ mpv --version                                          
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Oct  2 22:30:49 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: n4.0.2

$ cat ~/.mpv/mpv.conf
hwdec=auto
gpu-context=wayland
cursor-autohide=100
fullscreen=yes
monitoraspect=16:9
osd-level=0
save-position-on-quit=yes
hr-seek=yes
volume=100
```

### Reproduction steps
I play any movie file

### Expected behavior
Hide the cursor after 100 ms 

### Actual behavior
It doesn't hide the cursor **until I move it**.

### Remark
If I put in config file `cursor-autohide=always`, it doesn't hide the cursor never even if I move the cursor.

### Log file
https://hastebin.com/zanipuhipi

### PR DESCRIPTION
**Pull request by Dudemanguy911**
This is forked from #6480 with just a few more lines to fix what I had mentioned there. I only made this since there didn't seem to be any activity from @t-8ch. This also fixes #6185. On wayland, the cursor should automatically hide without having to move it (which is the current behavior). Also, the cursor shouldn't reappear when going to fullscreen (which is what happened with @t-8ch's fix).

Also as a side note, I personally don't really think it's necessary to define a whole new `reset_cursor` function. I think the name is misleading and `set_cursor_visibility(wl, wl->cursor_visible)` is more than clear and sufficient. I left `reset_cursor` since like 50% of this is stolen from @t-8ch anyway, but I'll happily change it if the devs agree with me.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

File: video/out/wayland_common.c [hunk 1]
```diff
@@ -91,6 +92,11 @@ static int set_cursor_visibility(struct vo_wayland_state *wl, bool on)
     return VO_TRUE;
 }
 
+static void reset_cursor(struct vo_wayland_state *wl)
+{
+        set_cursor_visibility(wl, wl->cursor_visible);
```
Comment (haasn) [inline video/out/wayland_common.c]: Why add a 1-line function that you're only going to call once?

Comment (Dudemanguy911) [reply video/out/wayland_common.c]: I totally agree. Like I said earlier, I only left it in since it was originally forked from t-8ch's PR. I'll happily remove it.

**Comment by zc62** [comment]
Maybe better to edit the original commit so that the one line function never appears in the git history, rather than adding an extra commit to manually delete it later.

**Comment by Dudemanguy911** [comment]
The idea wasn't originally mine though (the reason why I forked it from the other PR to begin with), so I don't think it's appropriate to rewrite history like that.

**Comment by zc62** [comment]
It is not uncommon to slightly modify the commit while maintaining the original authorship of the that commit. I don't see why it is inappropriate to do that. Anyway, this is just my point of view. It's up to the members to decide if this is okay.

**Comment by Dudemanguy911** [comment]
Fair enough point. Personally, I prefer not to modify other people's commits directly, but certainly there are people that do modify them directly. And yeah, I'll happily go with whatever approach is preferred by mpv devs.

**Comment by Dudemanguy911** [comment]
Revisiting this, I changed my mind and figured zc62 was right. It looks much cleaner. I went ahead and squashed those commits so now it's just two. Pinging @haasn and/or @atomnuker to take another look at this.

**Comment by t-8ch** [comment]
@jeeb Any chance you could have a look at this?
