### PR TITLE
demux/codec_tags: support more WAVEFORMATEXTENSIBLE tags

### LINKED ISSUE #10757: mpv plays atrac9 in Matroska as noise.
_mpv version
Platform and Version
Source of the mpv binary_

{{
mpv 0.34.0-501-g161bdd9359 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 09 12:28:45 2022
FFmpeg library versions:
   libavutil       57.39.100
   libavcodec      59.50.100
   libavformat     59.34.101
   libswscale      6.8.112
   libavfilter     8.49.101
   libswresample   4.9.100
FFmpeg version: git-2022-10-08-94644343a
}}

_Reproduction steps + Expected behavior + Actual behavior_

**mpv ACSW-01-sample.wav** = plays O.K.
**mpv gq-acsw-01-introd.mka** = outputs noise.

_Log file_
**0.039][d][cplayer] Run command: define-section, flags=64, args=[name="input_osc", contents="", flags="default"]
[   0.039][d][cplayer] Run command: enable-section, flags=64, args=[name="input_osc", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.039][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_osc", contents="", flags="force"]
[   0.039][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_osc", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.039][v][cplayer] Running hook: ytdl_hook/on_preloaded
[   0.039][v][mkv] select track 0
[   0.040][i][cplayer]  (+) Audio --aid=1 --alang=eng (*) (dfpwm 2ch 48000Hz)
[   0.042][v][ad] Codec list:
[   0.042][v][ad]     dfpwm - DFPWM1a audio
[   0.042][v][ad] Opening decoder dfpwm
[   0.043][v][ad] Requesting 1 threads for decoding.
[   0.043][v][ad] Selected codec: dfpwm (DFPWM1a audio)
[   0.043][v][af] User filter list:
[   0.043][v][af]   (empty)
[   0.043][v][cplayer] Starting playback...**

### Sample files

[atrac9sample.zip](https://github.com/mpv-player/mpv/files/9804597/atrac9sample.zip)
*Sample .WAV and sample .MKA in the archive attached to this post.*

### PR DESCRIPTION
**Pull request by thebombzen**
This patch adds support for two extra WAVEFORMATEXTENSIBLE GUID tags that can appear inside RIFF headers. It also adds support for extra codec IDs that may appear as their own unique wSubFormats inside RIFF headers, such as ATRAC9 inside matroska, as one example.

Fixes #10757.

### CODE REVIEW

File: demux/codec_tags.c [hunk 1]
```diff
@@ -45,14 +45,55 @@ static const char *lookup_tag(int type, uint32_t tag)
 }
 
 // Corresponds to WMMEDIASUBTYPE_Base.
```
Comment (sfan5) [inline demux/codec_tags.c:47]: comment needs to be updated presumably

File: demux/codec_tags.c [hunk 2]
```diff
@@ -45,14 +45,55 @@ static const char *lookup_tag(int type, uint32_t tag)
...
-static const unsigned char guid_ext_base[16] =
+static const unsigned char guid_ext_base[3][16] = {
     {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00,
-     0x80, 0x00, 0x00, 0xAA, 0x00, 0x38, 0x9B, 0x71};
+     0x80, 0x00, 0x00, 0xAA, 0x00, 0x38, 0x9B, 0x71},
+    {0x00, 0x00, 0x00, 0x00, 0x21, 0x07, 0xD3, 0x11,
+     0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00},
```
Comment (sfan5) [inline demux/codec_tags.c:52]: can't find anything for 2107-d311-8644-c8c1ca000000 on the web

File: demux/codec_tags.c [hunk 3]
```diff
@@ -45,14 +45,55 @@ static const char *lookup_tag(int type, uint32_t tag)
...
+    {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
+     0x00, 0x00, 0x10, 0x00, 0x80, 0x00, 0x00, 0xAA}
```
Comment (sfan5) [inline demux/codec_tags.c:54]: neither can I for 0000-0000-0000-1000800000aa
where do these come from?

Comment (thebombzen) [reply demux/codec_tags.c:54]: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/riff.h#L114

File: demux/codec_tags.c (hunk 2 above)
Comment (thebombzen) [reply demux/codec_tags.c:52]: See Section 5.5.1 of this dissertation; https://ria.ua.pt/bitstream/10773/11364/1/disserta%C3%A7%C3%A3o.pdf
